// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.lang {
public class LinkageError: global::java.lang.Error {
private static long _fserialVersionUID = 3579600108157160122L;

public void @this(){
//XMLVM_BEGIN_WRAPPER[java.lang.LinkageError: void <init>()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    ((global::java.lang.Error) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[java.lang.LinkageError: void <init>()]
}

public void @this(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[java.lang.LinkageError: void <init>(java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::java.lang.Error) _r0_o).@this((global::java.lang.String) _r1_o);
    return;
//XMLVM_END_WRAPPER[java.lang.LinkageError: void <init>(java.lang.String)]
}

//XMLVM_BEGIN_WRAPPER[java.lang.LinkageError]
//XMLVM_END_WRAPPER[java.lang.LinkageError]

} // end of class: LinkageError

} // end of namespace: java.lang
