// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.lang {
public class NullPointerException: global::java.lang.RuntimeException {

public void @this(){
//XMLVM_BEGIN_WRAPPER[java.lang.NullPointerException: void <init>()]
    global::System.Object _r0_o = null;
    _r0_o = this;
    ((global::java.lang.RuntimeException) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[java.lang.NullPointerException: void <init>()]
}

public void @this(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[java.lang.NullPointerException: void <init>(java.lang.String)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::java.lang.RuntimeException) _r0_o).@this((global::java.lang.String) _r1_o);
    return;
//XMLVM_END_WRAPPER[java.lang.NullPointerException: void <init>(java.lang.String)]
}

//XMLVM_BEGIN_WRAPPER[java.lang.NullPointerException]
//XMLVM_END_WRAPPER[java.lang.NullPointerException]

} // end of class: NullPointerException

} // end of namespace: java.lang
