// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace org.xml.sax.ext {
public class DefaultHandler2: global::org.xml.sax.helpers.DefaultHandler,global::org.xml.sax.ext.LexicalHandler,global::org.xml.sax.ext.DeclHandler,global::org.xml.sax.ext.EntityResolver2 {
public void @this(){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: void <init>()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    ((global::org.xml.sax.helpers.DefaultHandler) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: void <init>()]
}

public virtual void startCDATA(){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: void startCDATA()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    return;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: void startCDATA()]
}

public virtual void endCDATA(){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: void endCDATA()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    return;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: void endCDATA()]
}

public virtual void startDTD(global::java.lang.String n1, global::java.lang.String n2, global::java.lang.String n3){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: void startDTD(java.lang.String, java.lang.String, java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    _r2_o = n2;
    _r3_o = n3;
    return;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: void startDTD(java.lang.String, java.lang.String, java.lang.String)]
}

public virtual void endDTD(){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: void endDTD()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    return;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: void endDTD()]
}

public virtual void startEntity(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: void startEntity(java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    return;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: void startEntity(java.lang.String)]
}

public virtual void endEntity(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: void endEntity(java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    return;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: void endEntity(java.lang.String)]
}

public virtual void comment(global::org.xmlvm._nArrayAdapter<char> n1, int n2, int n3){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: void comment(char[], int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    _r2.i = n2;
    _r3.i = n3;
    return;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: void comment(char[], int, int)]
}

public virtual void attributeDecl(global::java.lang.String n1, global::java.lang.String n2, global::java.lang.String n3, global::java.lang.String n4, global::java.lang.String n5){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: void attributeDecl(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    _r2_o = n2;
    _r3_o = n3;
    _r4_o = n4;
    _r5_o = n5;
    return;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: void attributeDecl(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)]
}

public virtual void elementDecl(global::java.lang.String n1, global::java.lang.String n2){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: void elementDecl(java.lang.String, java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    _r2_o = n2;
    return;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: void elementDecl(java.lang.String, java.lang.String)]
}

public virtual void externalEntityDecl(global::java.lang.String n1, global::java.lang.String n2, global::java.lang.String n3){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: void externalEntityDecl(java.lang.String, java.lang.String, java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    _r2_o = n2;
    _r3_o = n3;
    return;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: void externalEntityDecl(java.lang.String, java.lang.String, java.lang.String)]
}

public virtual void internalEntityDecl(global::java.lang.String n1, global::java.lang.String n2){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: void internalEntityDecl(java.lang.String, java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    _r2_o = n2;
    return;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: void internalEntityDecl(java.lang.String, java.lang.String)]
}

public virtual global::System.Object getExternalSubset(global::java.lang.String n1, global::java.lang.String n2){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: org.xml.sax.InputSource getExternalSubset(java.lang.String, java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r2_o = n1;
    _r3_o = n2;
    _r0_o = null;
    return (global::org.xml.sax.InputSource) _r0_o;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: org.xml.sax.InputSource getExternalSubset(java.lang.String, java.lang.String)]
}

public virtual global::System.Object resolveEntity(global::java.lang.String n1, global::java.lang.String n2, global::java.lang.String n3, global::java.lang.String n4){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: org.xml.sax.InputSource resolveEntity(java.lang.String, java.lang.String, java.lang.String, java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r2_o = n1;
    _r3_o = n2;
    _r4_o = n3;
    _r5_o = n4;
    _r0_o = null;
    return (global::org.xml.sax.InputSource) _r0_o;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: org.xml.sax.InputSource resolveEntity(java.lang.String, java.lang.String, java.lang.String, java.lang.String)]
}

public override global::System.Object resolveEntity(global::java.lang.String n1, global::java.lang.String n2){
//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2: org.xml.sax.InputSource resolveEntity(java.lang.String, java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r2_o = n1;
    _r3_o = n2;
    _r0_o = null;
    _r0_o = ((global::org.xml.sax.ext.DefaultHandler2) _r1_o).resolveEntity((global::java.lang.String) _r0_o, (global::java.lang.String) _r2_o, (global::java.lang.String) _r0_o, (global::java.lang.String) _r3_o);
    return (global::org.xml.sax.InputSource) _r0_o;
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2: org.xml.sax.InputSource resolveEntity(java.lang.String, java.lang.String)]
}

//XMLVM_BEGIN_WRAPPER[org.xml.sax.ext.DefaultHandler2]
//XMLVM_END_WRAPPER[org.xml.sax.ext.DefaultHandler2]

} // end of class: DefaultHandler2

} // end of namespace: org.xml.sax.ext
