// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.nio.charset {
public class Charset_21: global::java.lang.Object,global::java.security.PrivilegedAction {
public void @this(){
//XMLVM_BEGIN_WRAPPER[java.nio.charset.Charset$1: void <init>()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    ((global::java.lang.Object) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[java.nio.charset.Charset$1: void <init>()]
}

public virtual global::System.Object run(){
//XMLVM_BEGIN_WRAPPER[java.nio.charset.Charset$1: org.apache.harmony.niochar.CharsetProviderImpl run()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0_o = new global::org.apache.harmony.niochar.CharsetProviderImpl();
    ((global::org.apache.harmony.niochar.CharsetProviderImpl) _r0_o).@this();
    return (global::org.apache.harmony.niochar.CharsetProviderImpl) _r0_o;
//XMLVM_END_WRAPPER[java.nio.charset.Charset$1: org.apache.harmony.niochar.CharsetProviderImpl run()]
}

//XMLVM_BEGIN_WRAPPER[java.nio.charset.Charset$1]
//XMLVM_END_WRAPPER[java.nio.charset.Charset$1]

} // end of class: Charset_21

} // end of namespace: java.nio.charset
