// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace com.codename1.components {
public class StorageImage: global::com.codename1.ui.EncodedImage {
private global::java.lang.String _ffileName;

private bool _fkeep;

private global::org.xmlvm._nArrayAdapter<sbyte> _fdata;

private global::java.lang.Object _fweak;

private void @this(global::java.lang.String n1, int n2, int n3, bool n4){
//XMLVM_BEGIN_WRAPPER[com.codename1.components.StorageImage: void <init>(java.lang.String, int, int, boolean)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::org.xmlvm._nElement _r3;
    global::org.xmlvm._nElement _r4;
    _r0_o = this;
    _r1_o = n1;
    _r2.i = n2;
    _r3.i = n3;
    _r4.i = n4 ? 1 : 0;
    ((global::com.codename1.ui.EncodedImage) _r0_o).@this((int) _r2.i, (int) _r3.i);
    ((global::com.codename1.components.StorageImage) _r0_o)._ffileName = (global::java.lang.String) _r1_o;
    ((global::com.codename1.components.StorageImage) _r0_o)._fkeep = 0!=_r4.i;
    return;
//XMLVM_END_WRAPPER[com.codename1.components.StorageImage: void <init>(java.lang.String, int, int, boolean)]
}

public override global::System.Object getImageData(){
//XMLVM_BEGIN_WRAPPER[com.codename1.components.StorageImage: byte[] getImageData()]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    _r5_o = this;
    _r3_o = ((global::com.codename1.components.StorageImage) _r5_o)._fdata;
    if (_r3_o == null) goto label7;
    _r3_o = ((global::com.codename1.components.StorageImage) _r5_o)._fdata;
    label6:;
    return (global::org.xmlvm._nArrayAdapter<sbyte>) _r3_o;
    label7:;
    _r3_o = ((global::com.codename1.components.StorageImage) _r5_o)._fweak;
    if (_r3_o == null) goto label31;
    _r3_o = global::com.codename1.ui.Display.getInstance();
    _r4_o = ((global::com.codename1.components.StorageImage) _r5_o)._fweak;
    _r3_o = ((global::com.codename1.ui.Display) _r3_o).extractHardRef((global::java.lang.Object) _r4_o);
    _r0_o = _r3_o;
    _r1_o = _r0_o;
    if (_r1_o == null) goto label31;
    _r3_o = _r1_o;
    goto label6;
    label31:;
    _r3_o = global::com.codename1.io.Storage.getInstance();
    _r4_o = ((global::com.codename1.components.StorageImage) _r5_o)._ffileName;
    _r3_o = ((global::com.codename1.io.Storage) _r3_o).readObject((global::java.lang.String) _r4_o);
    _r0_o = _r3_o;
    _r2_o = _r0_o;
    _r3.i = ((global::com.codename1.components.StorageImage) _r5_o)._fkeep ? 1 : 0;
    if (_r3.i == 0) goto label55;
    ((global::com.codename1.components.StorageImage) _r5_o)._fdata = (global::org.xmlvm._nArrayAdapter<sbyte>) _r2_o;
    label53:;
    _r3_o = _r2_o;
    goto label6;
    label55:;
    _r3_o = global::com.codename1.ui.Display.getInstance();
    _r3_o = ((global::com.codename1.ui.Display) _r3_o).createSoftWeakRef((global::java.lang.Object) _r2_o);
    ((global::com.codename1.components.StorageImage) _r5_o)._fweak = (global::java.lang.Object) _r3_o;
    goto label53;
//XMLVM_END_WRAPPER[com.codename1.components.StorageImage: byte[] getImageData()]
}

public static global::System.Object create(global::java.lang.String n1, global::org.xmlvm._nArrayAdapter<sbyte> n2, int n3, int n4){
//XMLVM_BEGIN_WRAPPER[com.codename1.components.StorageImage: com.codename1.components.StorageImage create(java.lang.String, byte[], int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::org.xmlvm._nElement _r5;
    _r2_o = n1;
    _r3_o = n2;
    _r4.i = n3;
    _r5.i = n4;
    _r0_o = global::com.codename1.io.Storage.getInstance();
    _r0.i = ((global::com.codename1.io.Storage) _r0_o).writeObject((global::java.lang.String) _r2_o, (global::java.lang.Object) _r3_o) ? 1 : 0;
    if (_r0.i == 0) goto label17;
    _r0_o = new global::com.codename1.components.StorageImage();
    _r1.i = 1;
    ((global::com.codename1.components.StorageImage) _r0_o).@this((global::java.lang.String) _r2_o, (int) _r4.i, (int) _r5.i, 0!=_r1.i);
    label16:;
    return (global::com.codename1.components.StorageImage) _r0_o;
    label17:;
    _r0_o = null;
    goto label16;
//XMLVM_END_WRAPPER[com.codename1.components.StorageImage: com.codename1.components.StorageImage create(java.lang.String, byte[], int, int)]
}

public static global::System.Object create(global::java.lang.String n1, global::org.xmlvm._nArrayAdapter<sbyte> n2, int n3, int n4, bool n5){
//XMLVM_BEGIN_WRAPPER[com.codename1.components.StorageImage: com.codename1.components.StorageImage create(java.lang.String, byte[], int, int, boolean)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::org.xmlvm._nElement _r4;
    global::org.xmlvm._nElement _r5;
    _r1_o = n1;
    _r2_o = n2;
    _r3.i = n3;
    _r4.i = n4;
    _r5.i = n5 ? 1 : 0;
    _r0_o = global::com.codename1.io.Storage.getInstance();
    _r0.i = ((global::com.codename1.io.Storage) _r0_o).writeObject((global::java.lang.String) _r1_o, (global::java.lang.Object) _r2_o) ? 1 : 0;
    if (_r0.i == 0) goto label16;
    _r0_o = new global::com.codename1.components.StorageImage();
    ((global::com.codename1.components.StorageImage) _r0_o).@this((global::java.lang.String) _r1_o, (int) _r3.i, (int) _r4.i, 0!=_r5.i);
    label15:;
    return (global::com.codename1.components.StorageImage) _r0_o;
    label16:;
    _r0_o = null;
    goto label15;
//XMLVM_END_WRAPPER[com.codename1.components.StorageImage: com.codename1.components.StorageImage create(java.lang.String, byte[], int, int, boolean)]
}

public static global::System.Object create(global::java.lang.String n1, global::java.io.InputStream n2, int n3, int n4){
//XMLVM_BEGIN_WRAPPER[com.codename1.components.StorageImage: com.codename1.components.StorageImage create(java.lang.String, java.io.InputStream, int, int)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::org.xmlvm._nElement _r5;
    _r2_o = n1;
    _r3_o = n2;
    _r4.i = n3;
    _r5.i = n4;
    _r0_o = global::com.codename1.ui.EncodedImage.create((global::java.io.InputStream) _r3_o);
    _r1_o = ((global::com.codename1.ui.EncodedImage) _r0_o).getImageData();
    _r1_o = global::com.codename1.components.StorageImage.create((global::java.lang.String) _r2_o, (global::org.xmlvm._nArrayAdapter<sbyte>) _r1_o, (int) _r4.i, (int) _r5.i);
    return (global::com.codename1.components.StorageImage) _r1_o;
//XMLVM_END_WRAPPER[com.codename1.components.StorageImage: com.codename1.components.StorageImage create(java.lang.String, java.io.InputStream, int, int)]
}

public static global::System.Object create(global::java.lang.String n1, int n2, int n3){
//XMLVM_BEGIN_WRAPPER[com.codename1.components.StorageImage: com.codename1.components.StorageImage create(java.lang.String, int, int)]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::org.xmlvm._nElement _r4;
    _r2_o = n1;
    _r3.i = n2;
    _r4.i = n3;
    _r0_o = new global::com.codename1.components.StorageImage();
    _r1.i = 1;
    ((global::com.codename1.components.StorageImage) _r0_o).@this((global::java.lang.String) _r2_o, (int) _r3.i, (int) _r4.i, 0!=_r1.i);
    return (global::com.codename1.components.StorageImage) _r0_o;
//XMLVM_END_WRAPPER[com.codename1.components.StorageImage: com.codename1.components.StorageImage create(java.lang.String, int, int)]
}

public static global::System.Object create(global::java.lang.String n1, int n2, int n3, bool n4){
//XMLVM_BEGIN_WRAPPER[com.codename1.components.StorageImage: com.codename1.components.StorageImage create(java.lang.String, int, int, boolean)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::org.xmlvm._nElement _r3;
    global::org.xmlvm._nElement _r4;
    _r1_o = n1;
    _r2.i = n2;
    _r3.i = n3;
    _r4.i = n4 ? 1 : 0;
    _r0_o = new global::com.codename1.components.StorageImage();
    ((global::com.codename1.components.StorageImage) _r0_o).@this((global::java.lang.String) _r1_o, (int) _r2.i, (int) _r3.i, 0!=_r4.i);
    return (global::com.codename1.components.StorageImage) _r0_o;
//XMLVM_END_WRAPPER[com.codename1.components.StorageImage: com.codename1.components.StorageImage create(java.lang.String, int, int, boolean)]
}

//XMLVM_BEGIN_WRAPPER[com.codename1.components.StorageImage]
//XMLVM_END_WRAPPER[com.codename1.components.StorageImage]

} // end of class: StorageImage

} // end of namespace: com.codename1.components
