// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace com.codename1.share {
public abstract class ShareService: global::com.codename1.ui.Command {
private global::java.lang.String _fmessage;

private global::java.lang.String _fimage;

private global::java.lang.String _fmimeType;

private global::com.codename1.ui.Form _foriginal;

public void @this(global::java.lang.String n1, global::com.codename1.ui.Image n2){
//XMLVM_BEGIN_WRAPPER[com.codename1.share.ShareService: void <init>(java.lang.String, com.codename1.ui.Image)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    _r2_o = n2;
    ((global::com.codename1.ui.Command) _r0_o).@this((global::java.lang.String) _r1_o, (global::com.codename1.ui.Image) _r2_o);
    return;
//XMLVM_END_WRAPPER[com.codename1.share.ShareService: void <init>(java.lang.String, com.codename1.ui.Image)]
}

public override void actionPerformed(global::com.codename1.ui.events.ActionEvent n1){
//XMLVM_BEGIN_WRAPPER[com.codename1.share.ShareService: void actionPerformed(com.codename1.ui.events.ActionEvent)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r3_o = this;
    _r4_o = n1;
    _r0_o = ((global::com.codename1.share.ShareService) _r3_o)._fimage;
    if (_r0_o == null) goto label14;
    _r0_o = ((global::com.codename1.share.ShareService) _r3_o)._fmessage;
    _r1_o = ((global::com.codename1.share.ShareService) _r3_o)._fimage;
    _r2_o = ((global::com.codename1.share.ShareService) _r3_o)._fmimeType;
    ((global::com.codename1.share.ShareService) _r3_o).share((global::java.lang.String) _r0_o, (global::java.lang.String) _r1_o, (global::java.lang.String) _r2_o);
    label13:;
    return;
    label14:;
    _r0_o = ((global::com.codename1.share.ShareService) _r3_o)._fmessage;
    ((global::com.codename1.share.ShareService) _r3_o).share((global::java.lang.String) _r0_o);
    goto label13;
//XMLVM_END_WRAPPER[com.codename1.share.ShareService: void actionPerformed(com.codename1.ui.events.ActionEvent)]
}

public abstract void share(global::java.lang.String n1);

public virtual void share(global::java.lang.String n1, global::java.lang.String n2, global::java.lang.String n3){
//XMLVM_BEGIN_WRAPPER[com.codename1.share.ShareService: void share(java.lang.String, java.lang.String, java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    _r2_o = n2;
    _r3_o = n3;
    return;
//XMLVM_END_WRAPPER[com.codename1.share.ShareService: void share(java.lang.String, java.lang.String, java.lang.String)]
}

public abstract bool canShareImage();

public virtual void setMessage(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[com.codename1.share.ShareService: void setMessage(java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::com.codename1.share.ShareService) _r0_o)._fmessage = (global::java.lang.String) _r1_o;
    return;
//XMLVM_END_WRAPPER[com.codename1.share.ShareService: void setMessage(java.lang.String)]
}

public virtual void setImage(global::java.lang.String n1, global::java.lang.String n2){
//XMLVM_BEGIN_WRAPPER[com.codename1.share.ShareService: void setImage(java.lang.String, java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    _r2_o = n2;
    ((global::com.codename1.share.ShareService) _r0_o)._fimage = (global::java.lang.String) _r1_o;
    ((global::com.codename1.share.ShareService) _r0_o)._fmimeType = (global::java.lang.String) _r2_o;
    return;
//XMLVM_END_WRAPPER[com.codename1.share.ShareService: void setImage(java.lang.String, java.lang.String)]
}

public virtual void setOriginalForm(global::com.codename1.ui.Form n1){
//XMLVM_BEGIN_WRAPPER[com.codename1.share.ShareService: void setOriginalForm(com.codename1.ui.Form)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::com.codename1.share.ShareService) _r0_o)._foriginal = (global::com.codename1.ui.Form) _r1_o;
    return;
//XMLVM_END_WRAPPER[com.codename1.share.ShareService: void setOriginalForm(com.codename1.ui.Form)]
}

public virtual global::System.Object getOriginal(){
//XMLVM_BEGIN_WRAPPER[com.codename1.share.ShareService: com.codename1.ui.Form getOriginal()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0_o = ((global::com.codename1.share.ShareService) _r1_o)._foriginal;
    return (global::com.codename1.ui.Form) _r0_o;
//XMLVM_END_WRAPPER[com.codename1.share.ShareService: com.codename1.ui.Form getOriginal()]
}

public virtual void finish(){
//XMLVM_BEGIN_WRAPPER[com.codename1.share.ShareService: void finish()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0_o = ((global::com.codename1.share.ShareService) _r1_o)._foriginal;
    ((global::com.codename1.ui.Form) _r0_o).showBack();
    return;
//XMLVM_END_WRAPPER[com.codename1.share.ShareService: void finish()]
}

//XMLVM_BEGIN_WRAPPER[com.codename1.share.ShareService]
//XMLVM_END_WRAPPER[com.codename1.share.ShareService]

} // end of class: ShareService

} // end of namespace: com.codename1.share
