// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace com.codename1.ui.list {
public class MultiList: global::com.codename1.ui.List {
private global::com.codename1.components.MultiButton _fsel;

private global::com.codename1.components.MultiButton _funsel;

private global::com.codename1.ui.Image _fplaceholder;

public void @this(){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.list.MultiList: void <init>()]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r3_o = null;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    global::System.Object _r6_o = null;
    _r6_o = this;
    // Value=more...
    _r5_o = new global::java.lang.String();
    ((global::java.lang.String)_r5_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)109)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 46)), unchecked((char) unchecked((uint) 46)), unchecked((char) unchecked((uint) 46))}));
    _r0_o = new global::com.codename1.ui.list.DefaultListModel();
    _r1.i = 3;
    _r1_o = new global::org.xmlvm._nArrayAdapter<global::System.Object>(new global::System.Object[_r1.i]);
    _r2.i = 0;
    // Value=Entry 1
    _r3_o = new global::java.lang.String();
    ((global::java.lang.String)_r3_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)69)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 121)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 49))}));
    // Value=more...
    _r4_o = new global::java.lang.String();
    ((global::java.lang.String)_r4_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)109)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 46)), unchecked((char) unchecked((uint) 46)), unchecked((char) unchecked((uint) 46))}));
    _r3_o = global::com.codename1.ui.list.MultiList.h((global::java.lang.String) _r3_o, (global::java.lang.String) _r5_o);
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r1_o)[_r2.i] = _r3_o;
    _r2.i = 1;
    // Value=Entry 2
    _r3_o = new global::java.lang.String();
    ((global::java.lang.String)_r3_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)69)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 121)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 50))}));
    // Value=more...
    _r4_o = new global::java.lang.String();
    ((global::java.lang.String)_r4_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)109)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 46)), unchecked((char) unchecked((uint) 46)), unchecked((char) unchecked((uint) 46))}));
    _r3_o = global::com.codename1.ui.list.MultiList.h((global::java.lang.String) _r3_o, (global::java.lang.String) _r5_o);
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r1_o)[_r2.i] = _r3_o;
    _r2.i = 2;
    // Value=Entry 3
    _r3_o = new global::java.lang.String();
    ((global::java.lang.String)_r3_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)69)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 121)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 51))}));
    // Value=more...
    _r4_o = new global::java.lang.String();
    ((global::java.lang.String)_r4_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)109)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 46)), unchecked((char) unchecked((uint) 46)), unchecked((char) unchecked((uint) 46))}));
    _r3_o = global::com.codename1.ui.list.MultiList.h((global::java.lang.String) _r3_o, (global::java.lang.String) _r5_o);
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r1_o)[_r2.i] = _r3_o;
    ((global::com.codename1.ui.list.DefaultListModel) _r0_o).@this((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r1_o);
    ((global::com.codename1.ui.List) _r6_o).@this((global::com.codename1.ui.list.ListModel) _r0_o);
    _r0_o = new global::com.codename1.components.MultiButton();
    ((global::com.codename1.components.MultiButton) _r0_o).@this();
    ((global::com.codename1.ui.list.MultiList) _r6_o)._fsel = (global::com.codename1.components.MultiButton) _r0_o;
    _r0_o = new global::com.codename1.components.MultiButton();
    ((global::com.codename1.components.MultiButton) _r0_o).@this();
    ((global::com.codename1.ui.list.MultiList) _r6_o)._funsel = (global::com.codename1.components.MultiButton) _r0_o;
    return;
//XMLVM_END_WRAPPER[com.codename1.ui.list.MultiList: void <init>()]
}

public override void initComponent(){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.list.MultiList: void initComponent()]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    _r3_o = this;
    base.initComponent();
    _r0_o = new global::com.codename1.ui.list.GenericListCellRenderer();
    _r1_o = ((global::com.codename1.ui.list.MultiList) _r3_o)._fsel;
    _r2_o = ((global::com.codename1.ui.list.MultiList) _r3_o)._funsel;
    ((global::com.codename1.ui.list.GenericListCellRenderer) _r0_o).@this((global::com.codename1.ui.Component) _r1_o, (global::com.codename1.ui.Component) _r2_o);
    ((global::com.codename1.ui.list.MultiList) _r3_o).setRenderer((global::com.codename1.ui.list.ListCellRenderer) _r0_o);
    return;
//XMLVM_END_WRAPPER[com.codename1.ui.list.MultiList: void initComponent()]
}

private static global::System.Object h(global::java.lang.String n1, global::java.lang.String n2){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.list.MultiList: java.util.Hashtable h(java.lang.String, java.lang.String)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    _r2_o = n1;
    _r3_o = n2;
    _r0_o = new global::java.util.Hashtable();
    ((global::java.util.Hashtable) _r0_o).@this();
    // Value=Line1
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)76)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 49))}));
    ((global::java.util.Hashtable) _r0_o).put((global::java.lang.Object) _r1_o, (global::java.lang.Object) _r2_o);
    // Value=Line2
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)76)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 50))}));
    ((global::java.util.Hashtable) _r0_o).put((global::java.lang.Object) _r1_o, (global::java.lang.Object) _r3_o);
    return (global::java.util.Hashtable) _r0_o;
//XMLVM_END_WRAPPER[com.codename1.ui.list.MultiList: java.util.Hashtable h(java.lang.String, java.lang.String)]
}

public virtual global::System.Object getSelectedButton(){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.list.MultiList: com.codename1.components.MultiButton getSelectedButton()]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    _r1_o = this;
    _r0_o = ((global::com.codename1.ui.list.MultiList) _r1_o)._fsel;
    return (global::com.codename1.components.MultiButton) _r0_o;
//XMLVM_END_WRAPPER[com.codename1.ui.list.MultiList: com.codename1.components.MultiButton getSelectedButton()]
}

public virtual global::System.Object getUnselectedButton(){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.list.MultiList: com.codename1.components.MultiButton getUnselectedButton()]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    _r1_o = this;
    _r0_o = ((global::com.codename1.ui.list.MultiList) _r1_o)._funsel;
    return (global::com.codename1.components.MultiButton) _r0_o;
//XMLVM_END_WRAPPER[com.codename1.ui.list.MultiList: com.codename1.components.MultiButton getUnselectedButton()]
}

public override global::System.Object getPropertyNames(){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.list.MultiList: java.lang.String[] getPropertyNames()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    _r3_o = this;
    _r0.i = 20;
    _r0_o = new global::org.xmlvm._nArrayAdapter<global::System.Object>(new global::System.Object[_r0.i]);
    _r1.i = 0;
    // Value=name1
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)110)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 49))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 1;
    // Value=name2
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)110)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 50))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 2;
    // Value=name3
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)110)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 51))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 3;
    // Value=name4
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)110)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 52))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 4;
    // Value=uiid1
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)117)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 100)), unchecked((char) unchecked((uint) 49))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 5;
    // Value=uiid2
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)117)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 100)), unchecked((char) unchecked((uint) 50))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 6;
    // Value=uiid3
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)117)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 100)), unchecked((char) unchecked((uint) 51))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 7;
    // Value=uiid4
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)117)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 100)), unchecked((char) unchecked((uint) 52))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 8;
    // Value=iconName
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)105)), unchecked((char) unchecked((uint) 99)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 78)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 101))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 9;
    // Value=iconUiid
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)105)), unchecked((char) unchecked((uint) 99)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 85)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 100))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 10;
    // Value=iconPosition
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)105)), unchecked((char) unchecked((uint) 99)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 80)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 115)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 110))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 11;
    // Value=emblemName
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)101)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 98)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 78)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 101))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 12;
    // Value=emblemUiid
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)101)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 98)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 85)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 100))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 13;
    // Value=emblemPosition
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)101)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 98)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 80)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 115)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 110))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 14;
    // Value=horizontalLayout
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)104)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 122)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 76)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 121)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 117)), unchecked((char) unchecked((uint) 116))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 15;
    // Value=invertFirstTwoEntries
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)105)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 118)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 70)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 115)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 84)), unchecked((char) unchecked((uint) 119)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 69)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 115))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 16;
    // Value=checkBox
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)99)), unchecked((char) unchecked((uint) 104)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 99)), unchecked((char) unchecked((uint) 107)), unchecked((char) unchecked((uint) 66)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 120))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 17;
    // Value=radioButton
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)114)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 100)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 66)), unchecked((char) unchecked((uint) 117)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 110))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 18;
    // Value=maskName
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)109)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 115)), unchecked((char) unchecked((uint) 107)), unchecked((char) unchecked((uint) 78)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 101))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 19;
    // Value=Placeholder
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)80)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 99)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 104)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 100)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 114))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    return (global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o;
//XMLVM_END_WRAPPER[com.codename1.ui.list.MultiList: java.lang.String[] getPropertyNames()]
}

public override global::System.Object getPropertyTypes(){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.list.MultiList: java.lang.Class[] getPropertyTypes()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    _r5_o = this;
    _r4_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.Boolean));
    _r3_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    _r0.i = 20;
    _r0_o = new global::org.xmlvm._nArrayAdapter<global::System.Object>(new global::System.Object[_r0.i]);
    _r1.i = 0;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 1;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 2;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 3;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 4;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 5;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 6;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 7;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 8;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 9;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 10;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 11;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 12;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 13;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 14;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.Boolean));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r4_o;
    _r1.i = 15;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.Boolean));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r4_o;
    _r1.i = 16;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.Boolean));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r4_o;
    _r1.i = 17;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.Boolean));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r4_o;
    _r1.i = 18;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::java.lang.String));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    _r1.i = 19;
    _r2_o = global::org.xmlvm._nTIB.getClass(typeof(global::com.codename1.ui.Image));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    return (global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o;
//XMLVM_END_WRAPPER[com.codename1.ui.list.MultiList: java.lang.Class[] getPropertyTypes()]
}

public override global::System.Object getPropertyValue(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.list.MultiList: java.lang.Object getPropertyValue(java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    _r1_o = this;
    _r2_o = n1;
    // Value=placeholder
    _r0_o = new global::java.lang.String();
    ((global::java.lang.String)_r0_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)112)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 99)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 104)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 100)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 114))}));
    _r0.i = ((global::java.lang.String) _r2_o).equals((global::java.lang.Object) _r0_o) ? 1 : 0;
    if (_r0.i == 0) goto label11;
    _r0_o = ((global::com.codename1.ui.list.MultiList) _r1_o)._fplaceholder;
    label10:;
    return (global::java.lang.Object) _r0_o;
    label11:;
    _r0_o = ((global::com.codename1.ui.list.MultiList) _r1_o)._funsel;
    _r0_o = ((global::com.codename1.components.MultiButton) _r0_o).getPropertyValue((global::java.lang.String) _r2_o);
    goto label10;
//XMLVM_END_WRAPPER[com.codename1.ui.list.MultiList: java.lang.Object getPropertyValue(java.lang.String)]
}

public override global::System.Object setPropertyValue(global::java.lang.String n1, global::java.lang.Object n2){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.list.MultiList: java.lang.String setPropertyValue(java.lang.String, java.lang.Object)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    global::System.Object _r6_o = null;
    _r4_o = this;
    _r5_o = n1;
    _r6_o = n2;
    // Value=placeholder
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)112)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 99)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 104)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 100)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 114))}));
    _r2.i = ((global::java.lang.String) _r5_o).equals((global::java.lang.Object) _r2_o) ? 1 : 0;
    if (_r2.i == 0) goto label49;
    ((global::com.codename1.ui.list.MultiList) _r4_o)._fplaceholder = (global::com.codename1.ui.Image) _r6_o;
    _r2_o = ((global::com.codename1.ui.list.MultiList) _r4_o)._funsel;
    if (_r2_o == null) goto label30;
    _r2_o = ((global::com.codename1.ui.list.MultiList) _r4_o)._funsel;
    _r3_o = ((global::com.codename1.ui.list.MultiList) _r4_o)._fplaceholder;
    ((global::com.codename1.components.MultiButton) _r2_o).setIcon((global::com.codename1.ui.Image) _r3_o);
    _r2_o = ((global::com.codename1.ui.list.MultiList) _r4_o)._fsel;
    _r3_o = ((global::com.codename1.ui.list.MultiList) _r4_o)._fplaceholder;
    ((global::com.codename1.components.MultiButton) _r2_o).setIcon((global::com.codename1.ui.Image) _r3_o);
    label30:;
    _r2_o = ((global::com.codename1.ui.list.MultiList) _r4_o).getRenderer();
    _r2.i = ((_r2_o != null) && (_r2_o is global::com.codename1.ui.list.GenericListCellRenderer)) ? 1 : 0;
    if (_r2.i == 0) goto label47;
    _r4_o = ((global::com.codename1.ui.list.MultiList) _r4_o).getRenderer();
    ((global::com.codename1.ui.list.GenericListCellRenderer) _r4_o).updateIconPlaceholders();
    label47:;
    _r2_o = null;
    label48:;
    return (global::java.lang.String) _r2_o;
    label49:;
    _r2_o = ((global::com.codename1.ui.list.MultiList) _r4_o)._funsel;
    ((global::com.codename1.components.MultiButton) _r2_o).setPropertyValue((global::java.lang.String) _r5_o, (global::java.lang.Object) _r6_o);
    _r2_o = ((global::com.codename1.ui.list.MultiList) _r4_o)._fsel;
    _r1_o = ((global::com.codename1.components.MultiButton) _r2_o).setPropertyValue((global::java.lang.String) _r5_o, (global::java.lang.Object) _r6_o);
    _r2.i = ((global::com.codename1.ui.list.MultiList) _r4_o).isInitialized() ? 1 : 0;
    if (_r2.i == 0) goto label78;
    _r0_o = new global::com.codename1.ui.list.GenericListCellRenderer();
    _r2_o = ((global::com.codename1.ui.list.MultiList) _r4_o)._fsel;
    _r3_o = ((global::com.codename1.ui.list.MultiList) _r4_o)._funsel;
    ((global::com.codename1.ui.list.GenericListCellRenderer) _r0_o).@this((global::com.codename1.ui.Component) _r2_o, (global::com.codename1.ui.Component) _r3_o);
    ((global::com.codename1.ui.list.MultiList) _r4_o).setRenderer((global::com.codename1.ui.list.ListCellRenderer) _r0_o);
    label78:;
    _r2_o = _r1_o;
    goto label48;
//XMLVM_END_WRAPPER[com.codename1.ui.list.MultiList: java.lang.String setPropertyValue(java.lang.String, java.lang.Object)]
}

//XMLVM_BEGIN_WRAPPER[com.codename1.ui.list.MultiList]
//XMLVM_END_WRAPPER[com.codename1.ui.list.MultiList]

} // end of class: MultiList

} // end of namespace: com.codename1.ui.list
