// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.util {
public class AbstractList_2SubAbstractList: global::java.util.AbstractList {
private global::java.util.AbstractList _ffullList;

private int _foffset;

private int _fsize;

public void @this(global::java.util.AbstractList n1, int n2, int n3){
//XMLVM_BEGIN_WRAPPER[java.util.AbstractList$SubAbstractList: void <init>(java.util.AbstractList, int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::org.xmlvm._nElement _r4;
    _r1_o = this;
    _r2_o = n1;
    _r3.i = n2;
    _r4.i = n3;
    ((global::java.util.AbstractList) _r1_o).@this();
    ((global::java.util.AbstractList_2SubAbstractList) _r1_o)._ffullList = (global::java.util.AbstractList) _r2_o;
    _r0_o = ((global::java.util.AbstractList_2SubAbstractList) _r1_o)._ffullList;
    _r0.i = ((global::java.util.AbstractList) _r0_o)._fmodCount;
    ((global::java.util.AbstractList_2SubAbstractList) _r1_o)._fmodCount = _r0.i;
    ((global::java.util.AbstractList_2SubAbstractList) _r1_o)._foffset = _r3.i;
    _r0.i = _r4.i - _r3.i;
    ((global::java.util.AbstractList_2SubAbstractList) _r1_o)._fsize = _r0.i;
    return;
//XMLVM_END_WRAPPER[java.util.AbstractList$SubAbstractList: void <init>(java.util.AbstractList, int, int)]
}

public override void add(int n1, global::java.lang.Object n2){
//XMLVM_BEGIN_WRAPPER[java.util.AbstractList$SubAbstractList: void add(int, java.lang.Object)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r4_o = null;
    _r2_o = this;
    _r3.i = n1;
    _r4_o = n2;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fmodCount;
    _r1_o = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList) _r1_o)._fmodCount;
    if (_r0.i != _r1.i) goto label41;
    if (_r3.i < 0) goto label35;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fsize;
    if (_r3.i > _r0.i) goto label35;
    _r0_o = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._foffset;
    _r1.i = _r1.i + _r3.i;
    ((global::java.util.AbstractList) _r0_o).add((int) _r1.i, (global::java.lang.Object) _r4_o);
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fsize;
    _r0.i = _r0.i + 1;
    ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fsize = _r0.i;
    _r0_o = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._ffullList;
    _r0.i = ((global::java.util.AbstractList) _r0_o)._fmodCount;
    ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fmodCount = _r0.i;
    return;
    label35:;
    _r0_o = new global::java.lang.IndexOutOfBoundsException();
    ((global::java.lang.IndexOutOfBoundsException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IndexOutOfBoundsException) _r0_o);
    label41:;
    _r0_o = new global::java.util.ConcurrentModificationException();
    ((global::java.util.ConcurrentModificationException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.util.ConcurrentModificationException) _r0_o);
//XMLVM_END_WRAPPER[java.util.AbstractList$SubAbstractList: void add(int, java.lang.Object)]
}

public override bool addAll(int n1, global::java.util.Collection n2){
//XMLVM_BEGIN_WRAPPER[java.util.AbstractList$SubAbstractList: boolean addAll(int, java.util.Collection)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r5_o = null;
    _r3_o = this;
    _r4.i = n1;
    _r5_o = n2;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fmodCount;
    _r1_o = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList) _r1_o)._fmodCount;
    if (_r0.i != _r1.i) goto label47;
    if (_r4.i < 0) goto label41;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fsize;
    if (_r4.i > _r0.i) goto label41;
    _r0_o = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._foffset;
    _r1.i = _r1.i + _r4.i;
    _r0.i = ((global::java.util.AbstractList) _r0_o).addAll((int) _r1.i, (global::java.util.Collection) _r5_o) ? 1 : 0;
    if (_r0.i == 0) goto label40;
    _r1.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fsize;
    _r2.i = ((global::java.util.Collection) _r5_o).size();
    _r1.i = _r1.i + _r2.i;
    ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fsize = _r1.i;
    _r1_o = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList) _r1_o)._fmodCount;
    ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fmodCount = _r1.i;
    label40:;
    return _r0.i!=0;
    label41:;
    _r0_o = new global::java.lang.IndexOutOfBoundsException();
    ((global::java.lang.IndexOutOfBoundsException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IndexOutOfBoundsException) _r0_o);
    label47:;
    _r0_o = new global::java.util.ConcurrentModificationException();
    ((global::java.util.ConcurrentModificationException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.util.ConcurrentModificationException) _r0_o);
//XMLVM_END_WRAPPER[java.util.AbstractList$SubAbstractList: boolean addAll(int, java.util.Collection)]
}

public override bool addAll(global::java.util.Collection n1){
//XMLVM_BEGIN_WRAPPER[java.util.AbstractList$SubAbstractList: boolean addAll(java.util.Collection)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r3_o = null;
    global::System.Object _r4_o = null;
    _r3_o = this;
    _r4_o = n1;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fmodCount;
    _r1_o = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList) _r1_o)._fmodCount;
    if (_r0.i != _r1.i) goto label37;
    _r0_o = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._foffset;
    _r2.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fsize;
    _r1.i = _r1.i + _r2.i;
    _r0.i = ((global::java.util.AbstractList) _r0_o).addAll((int) _r1.i, (global::java.util.Collection) _r4_o) ? 1 : 0;
    if (_r0.i == 0) goto label36;
    _r1.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fsize;
    _r2.i = ((global::java.util.Collection) _r4_o).size();
    _r1.i = _r1.i + _r2.i;
    ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fsize = _r1.i;
    _r1_o = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList) _r1_o)._fmodCount;
    ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fmodCount = _r1.i;
    label36:;
    return _r0.i!=0;
    label37:;
    _r0_o = new global::java.util.ConcurrentModificationException();
    ((global::java.util.ConcurrentModificationException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.util.ConcurrentModificationException) _r0_o);
//XMLVM_END_WRAPPER[java.util.AbstractList$SubAbstractList: boolean addAll(java.util.Collection)]
}

public override global::System.Object get(int n1){
//XMLVM_BEGIN_WRAPPER[java.util.AbstractList$SubAbstractList: java.lang.Object get(int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    _r2_o = this;
    _r3.i = n1;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fmodCount;
    _r1_o = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList) _r1_o)._fmodCount;
    if (_r0.i != _r1.i) goto label30;
    if (_r3.i < 0) goto label24;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fsize;
    if (_r3.i >= _r0.i) goto label24;
    _r0_o = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._foffset;
    _r1.i = _r1.i + _r3.i;
    _r0_o = ((global::java.util.AbstractList) _r0_o).get((int) _r1.i);
    return (global::java.lang.Object) _r0_o;
    label24:;
    _r0_o = new global::java.lang.IndexOutOfBoundsException();
    ((global::java.lang.IndexOutOfBoundsException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IndexOutOfBoundsException) _r0_o);
    label30:;
    _r0_o = new global::java.util.ConcurrentModificationException();
    ((global::java.util.ConcurrentModificationException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.util.ConcurrentModificationException) _r0_o);
//XMLVM_END_WRAPPER[java.util.AbstractList$SubAbstractList: java.lang.Object get(int)]
}

public override global::System.Object iterator(){
//XMLVM_BEGIN_WRAPPER[java.util.AbstractList$SubAbstractList: java.util.Iterator iterator()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    _r1_o = this;
    _r0.i = 0;
    _r0_o = ((global::java.util.AbstractList_2SubAbstractList) _r1_o).listIterator((int) _r0.i);
    return (global::java.util.Iterator) _r0_o;
//XMLVM_END_WRAPPER[java.util.AbstractList$SubAbstractList: java.util.Iterator iterator()]
}

public override global::System.Object listIterator(int n1){
//XMLVM_BEGIN_WRAPPER[java.util.AbstractList$SubAbstractList: java.util.ListIterator listIterator(int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    _r4_o = this;
    _r5.i = n1;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r4_o)._fmodCount;
    _r1_o = ((global::java.util.AbstractList_2SubAbstractList) _r4_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList) _r1_o)._fmodCount;
    if (_r0.i != _r1.i) goto label39;
    if (_r5.i < 0) goto label33;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r4_o)._fsize;
    if (_r5.i > _r0.i) goto label33;
    _r0_o = new global::java.util.AbstractList_2SubAbstractList_2SubAbstractListIterator();
    _r1_o = ((global::java.util.AbstractList_2SubAbstractList) _r4_o)._ffullList;
    _r2.i = ((global::java.util.AbstractList_2SubAbstractList) _r4_o)._foffset;
    _r2.i = _r2.i + _r5.i;
    _r1_o = ((global::java.util.AbstractList) _r1_o).listIterator((int) _r2.i);
    _r2.i = ((global::java.util.AbstractList_2SubAbstractList) _r4_o)._foffset;
    _r3.i = ((global::java.util.AbstractList_2SubAbstractList) _r4_o)._fsize;
    ((global::java.util.AbstractList_2SubAbstractList_2SubAbstractListIterator) _r0_o).@this((global::java.util.ListIterator) _r1_o, (global::java.util.AbstractList_2SubAbstractList) _r4_o, (int) _r2.i, (int) _r3.i);
    return (global::java.util.ListIterator) _r0_o;
    label33:;
    _r0_o = new global::java.lang.IndexOutOfBoundsException();
    ((global::java.lang.IndexOutOfBoundsException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IndexOutOfBoundsException) _r0_o);
    label39:;
    _r0_o = new global::java.util.ConcurrentModificationException();
    ((global::java.util.ConcurrentModificationException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.util.ConcurrentModificationException) _r0_o);
//XMLVM_END_WRAPPER[java.util.AbstractList$SubAbstractList: java.util.ListIterator listIterator(int)]
}

public override global::System.Object remove(int n1){
//XMLVM_BEGIN_WRAPPER[java.util.AbstractList$SubAbstractList: java.lang.Object remove(int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    _r3_o = this;
    _r4.i = n1;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fmodCount;
    _r1_o = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList) _r1_o)._fmodCount;
    if (_r0.i != _r1.i) goto label42;
    if (_r4.i < 0) goto label36;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fsize;
    if (_r4.i >= _r0.i) goto label36;
    _r0_o = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._foffset;
    _r1.i = _r1.i + _r4.i;
    _r0_o = ((global::java.util.AbstractList) _r0_o).remove((int) _r1.i);
    _r1.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fsize;
    _r2.i = 1;
    _r1.i = _r1.i - _r2.i;
    ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fsize = _r1.i;
    _r1_o = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList) _r1_o)._fmodCount;
    ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fmodCount = _r1.i;
    return (global::java.lang.Object) _r0_o;
    label36:;
    _r0_o = new global::java.lang.IndexOutOfBoundsException();
    ((global::java.lang.IndexOutOfBoundsException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IndexOutOfBoundsException) _r0_o);
    label42:;
    _r0_o = new global::java.util.ConcurrentModificationException();
    ((global::java.util.ConcurrentModificationException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.util.ConcurrentModificationException) _r0_o);
//XMLVM_END_WRAPPER[java.util.AbstractList$SubAbstractList: java.lang.Object remove(int)]
}

public override void removeRange(int n1, int n2){
//XMLVM_BEGIN_WRAPPER[java.util.AbstractList$SubAbstractList: void removeRange(int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::org.xmlvm._nElement _r5;
    _r3_o = this;
    _r4.i = n1;
    _r5.i = n2;
    if (_r4.i == _r5.i) goto label34;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fmodCount;
    _r1_o = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList) _r1_o)._fmodCount;
    if (_r0.i != _r1.i) goto label35;
    _r0_o = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._foffset;
    _r1.i = _r1.i + _r4.i;
    _r2.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._foffset;
    _r2.i = _r2.i + _r5.i;
    ((global::java.util.AbstractList) _r0_o).removeRange((int) _r1.i, (int) _r2.i);
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fsize;
    _r1.i = _r5.i - _r4.i;
    _r0.i = _r0.i - _r1.i;
    ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fsize = _r0.i;
    _r0_o = ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._ffullList;
    _r0.i = ((global::java.util.AbstractList) _r0_o)._fmodCount;
    ((global::java.util.AbstractList_2SubAbstractList) _r3_o)._fmodCount = _r0.i;
    label34:;
    return;
    label35:;
    _r0_o = new global::java.util.ConcurrentModificationException();
    ((global::java.util.ConcurrentModificationException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.util.ConcurrentModificationException) _r0_o);
//XMLVM_END_WRAPPER[java.util.AbstractList$SubAbstractList: void removeRange(int, int)]
}

public override global::System.Object set(int n1, global::java.lang.Object n2){
//XMLVM_BEGIN_WRAPPER[java.util.AbstractList$SubAbstractList: java.lang.Object set(int, java.lang.Object)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r4_o = null;
    _r2_o = this;
    _r3.i = n1;
    _r4_o = n2;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fmodCount;
    _r1_o = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList) _r1_o)._fmodCount;
    if (_r0.i != _r1.i) goto label30;
    if (_r3.i < 0) goto label24;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fsize;
    if (_r3.i >= _r0.i) goto label24;
    _r0_o = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._foffset;
    _r1.i = _r1.i + _r3.i;
    _r0_o = ((global::java.util.AbstractList) _r0_o).set((int) _r1.i, (global::java.lang.Object) _r4_o);
    return (global::java.lang.Object) _r0_o;
    label24:;
    _r0_o = new global::java.lang.IndexOutOfBoundsException();
    ((global::java.lang.IndexOutOfBoundsException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IndexOutOfBoundsException) _r0_o);
    label30:;
    _r0_o = new global::java.util.ConcurrentModificationException();
    ((global::java.util.ConcurrentModificationException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.util.ConcurrentModificationException) _r0_o);
//XMLVM_END_WRAPPER[java.util.AbstractList$SubAbstractList: java.lang.Object set(int, java.lang.Object)]
}

public override int size(){
//XMLVM_BEGIN_WRAPPER[java.util.AbstractList$SubAbstractList: int size()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    _r2_o = this;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fmodCount;
    _r1_o = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._ffullList;
    _r1.i = ((global::java.util.AbstractList) _r1_o)._fmodCount;
    if (_r0.i != _r1.i) goto label11;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fsize;
    return _r0.i;
    label11:;
    _r0_o = new global::java.util.ConcurrentModificationException();
    ((global::java.util.ConcurrentModificationException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.util.ConcurrentModificationException) _r0_o);
//XMLVM_END_WRAPPER[java.util.AbstractList$SubAbstractList: int size()]
}

public virtual void sizeChanged(bool n1){
//XMLVM_BEGIN_WRAPPER[java.util.AbstractList$SubAbstractList: void sizeChanged(boolean)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    _r2_o = this;
    _r3.i = n1 ? 1 : 0;
    if (_r3.i == 0) goto label15;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fsize;
    _r0.i = _r0.i + 1;
    ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fsize = _r0.i;
    label8:;
    _r0_o = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._ffullList;
    _r0.i = ((global::java.util.AbstractList) _r0_o)._fmodCount;
    ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fmodCount = _r0.i;
    return;
    label15:;
    _r0.i = ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fsize;
    _r1.i = 1;
    _r0.i = _r0.i - _r1.i;
    ((global::java.util.AbstractList_2SubAbstractList) _r2_o)._fsize = _r0.i;
    goto label8;
//XMLVM_END_WRAPPER[java.util.AbstractList$SubAbstractList: void sizeChanged(boolean)]
}

//XMLVM_BEGIN_WRAPPER[java.util.AbstractList$SubAbstractList]
//XMLVM_END_WRAPPER[java.util.AbstractList$SubAbstractList]

} // end of class: AbstractList_2SubAbstractList

} // end of namespace: java.util
