// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.util {
public class Date: global::java.lang.Object,global::java.io.Serializable,global::java.lang.Cloneable,global::java.lang.Comparable {

static Date() {
    @static();
}


private static int _fcreationYear;

private long _fmilliseconds;

private static global::org.xmlvm._nArrayAdapter<global::System.Object> _fdayOfWeekNames;

private static global::org.xmlvm._nArrayAdapter<global::System.Object> _fmonthNames;

public static void @static(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void <clinit>()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::org.xmlvm._nElement _r4;
    global::org.xmlvm._nElement _r5;
    global::org.xmlvm._nElement _r6;
    global::org.xmlvm._nElement _r7;
    _r7.i = 4;
    _r6.i = 3;
    _r5.i = 2;
    _r4.i = 1;
    _r3.i = 0;
    _r0_o = new global::java.util.Date();
    ((global::java.util.Date) _r0_o).@this();
    _r0.i = ((global::java.util.Date) _r0_o).getYear();
    global::java.util.Date._fcreationYear = _r0.i;
    _r0.i = 7;
    _r0_o = new global::org.xmlvm._nArrayAdapter<global::System.Object>(new global::System.Object[_r0.i]);
    // Value=Sun
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)83)), unchecked((char) unchecked((uint) 117)), unchecked((char) unchecked((uint) 110))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r3.i] = _r1_o;
    // Value=Mon
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)77)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 110))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r4.i] = _r1_o;
    // Value=Tue
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)84)), unchecked((char) unchecked((uint) 117)), unchecked((char) unchecked((uint) 101))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r5.i] = _r1_o;
    // Value=Wed
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)87)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 100))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r6.i] = _r1_o;
    // Value=Thu
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)84)), unchecked((char) unchecked((uint) 104)), unchecked((char) unchecked((uint) 117))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r7.i] = _r1_o;
    _r1.i = 5;
    // Value=Fri
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)70)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 105))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 6;
    // Value=Sat
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)83)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 116))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    global::java.util.Date._fdayOfWeekNames = (global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o;
    _r0.i = 12;
    _r0_o = new global::org.xmlvm._nArrayAdapter<global::System.Object>(new global::System.Object[_r0.i]);
    // Value=Jan
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)74)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 110))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r3.i] = _r1_o;
    // Value=Feb
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)70)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 98))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r4.i] = _r1_o;
    // Value=Mar
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)77)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 114))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r5.i] = _r1_o;
    // Value=Apr
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)65)), unchecked((char) unchecked((uint) 112)), unchecked((char) unchecked((uint) 114))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r6.i] = _r1_o;
    // Value=May
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)77)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 121))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r7.i] = _r1_o;
    _r1.i = 5;
    // Value=Jun
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)74)), unchecked((char) unchecked((uint) 117)), unchecked((char) unchecked((uint) 110))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 6;
    // Value=Jul
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)74)), unchecked((char) unchecked((uint) 117)), unchecked((char) unchecked((uint) 108))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 7;
    // Value=Aug
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)65)), unchecked((char) unchecked((uint) 117)), unchecked((char) unchecked((uint) 103))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 8;
    // Value=Sep
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)83)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 112))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 9;
    // Value=Oct
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)79)), unchecked((char) unchecked((uint) 99)), unchecked((char) unchecked((uint) 116))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 10;
    // Value=Nov
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)78)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 118))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    _r1.i = 11;
    // Value=Dec
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)68)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 99))}));
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r2_o;
    global::java.util.Date._fmonthNames = (global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o;
    return;
//XMLVM_END_WRAPPER[java.util.Date: void <clinit>()]
}

public void @this(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void <init>()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r2_o = null;
    _r2_o = this;
    _r0.l = global::java.lang.System.currentTimeMillis();
    ((global::java.util.Date) _r2_o).@this((long) _r0.l);
    return;
//XMLVM_END_WRAPPER[java.util.Date: void <init>()]
}

public void @this(int n1, int n2, int n3){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void <init>(int, int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::org.xmlvm._nElement _r4;
    global::org.xmlvm._nElement _r5;
    _r2_o = this;
    _r3.i = n1;
    _r4.i = n2;
    _r5.i = n3;
    ((global::java.lang.Object) _r2_o).@this();
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.i = 0;
    ((global::java.util.GregorianCalendar) _r0_o).@this(0!=_r1.i);
    _r1.i = _r3.i + 1900;
    ((global::java.util.GregorianCalendar) _r0_o).set((int) _r1.i, (int) _r4.i, (int) _r5.i);
    _r0.l = ((global::java.util.GregorianCalendar) _r0_o).getTimeInMillis();
    ((global::java.util.Date) _r2_o)._fmilliseconds = _r0.l;
    return;
//XMLVM_END_WRAPPER[java.util.Date: void <init>(int, int, int)]
}

public void @this(int n1, int n2, int n3, int n4, int n5){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void <init>(int, int, int, int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    global::org.xmlvm._nElement _r3;
    global::org.xmlvm._nElement _r4;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::org.xmlvm._nElement _r8;
    global::org.xmlvm._nElement _r9;
    global::org.xmlvm._nElement _r10;
    global::org.xmlvm._nElement _r11;
    _r6_o = this;
    _r7.i = n1;
    _r8.i = n2;
    _r9.i = n3;
    _r10.i = n4;
    _r11.i = n5;
    ((global::java.lang.Object) _r6_o).@this();
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.i = 0;
    ((global::java.util.GregorianCalendar) _r0_o).@this(0!=_r1.i);
    _r1.i = _r7.i + 1900;
    _r2.i = _r8.i;
    _r3.i = _r9.i;
    _r4.i = _r10.i;
    _r5.i = _r11.i;
    ((global::java.util.GregorianCalendar) _r0_o).set((int) _r1.i, (int) _r2.i, (int) _r3.i, (int) _r4.i, (int) _r5.i);
    _r0.l = ((global::java.util.GregorianCalendar) _r0_o).getTimeInMillis();
    ((global::java.util.Date) _r6_o)._fmilliseconds = _r0.l;
    return;
//XMLVM_END_WRAPPER[java.util.Date: void <init>(int, int, int, int, int)]
}

public void @this(int n1, int n2, int n3, int n4, int n5, int n6){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void <init>(int, int, int, int, int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    global::org.xmlvm._nElement _r3;
    global::org.xmlvm._nElement _r4;
    global::org.xmlvm._nElement _r5;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::org.xmlvm._nElement _r9;
    global::org.xmlvm._nElement _r10;
    global::org.xmlvm._nElement _r11;
    global::org.xmlvm._nElement _r12;
    global::org.xmlvm._nElement _r13;
    _r7_o = this;
    _r8.i = n1;
    _r9.i = n2;
    _r10.i = n3;
    _r11.i = n4;
    _r12.i = n5;
    _r13.i = n6;
    ((global::java.lang.Object) _r7_o).@this();
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.i = 0;
    ((global::java.util.GregorianCalendar) _r0_o).@this(0!=_r1.i);
    _r1.i = _r8.i + 1900;
    _r2.i = _r9.i;
    _r3.i = _r10.i;
    _r4.i = _r11.i;
    _r5.i = _r12.i;
    _r6.i = _r13.i;
    ((global::java.util.GregorianCalendar) _r0_o).set((int) _r1.i, (int) _r2.i, (int) _r3.i, (int) _r4.i, (int) _r5.i, (int) _r6.i);
    _r0.l = ((global::java.util.GregorianCalendar) _r0_o).getTimeInMillis();
    ((global::java.util.Date) _r7_o)._fmilliseconds = _r0.l;
    return;
//XMLVM_END_WRAPPER[java.util.Date: void <init>(int, int, int, int, int, int)]
}

public void @this(long n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void <init>(long)]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    _r0_o = this;
    _r1.l = n1;
    ((global::java.lang.Object) _r0_o).@this();
    ((global::java.util.Date) _r0_o)._fmilliseconds = _r1.l;
    return;
//XMLVM_END_WRAPPER[java.util.Date: void <init>(long)]
}

public void @this(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void <init>(java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    _r2_o = this;
    _r3_o = n1;
    ((global::java.lang.Object) _r2_o).@this();
    _r0.l = global::java.util.Date.parse((global::java.lang.String) _r3_o);
    ((global::java.util.Date) _r2_o)._fmilliseconds = _r0.l;
    return;
//XMLVM_END_WRAPPER[java.util.Date: void <init>(java.lang.String)]
}

public virtual bool after(global::java.util.Date n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: boolean after(java.util.Date)]
    global::org.xmlvm._nElement _r0;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    _r4_o = this;
    _r5_o = n1;
    _r0.l = ((global::java.util.Date) _r4_o)._fmilliseconds;
    _r2.l = ((global::java.util.Date) _r5_o)._fmilliseconds;
    _r0.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r0.i <= 0) goto label10;
    _r0.i = 1;
    label9:;
    return _r0.i!=0;
    label10:;
    _r0.i = 0;
    goto label9;
//XMLVM_END_WRAPPER[java.util.Date: boolean after(java.util.Date)]
}

public virtual bool before(global::java.util.Date n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: boolean before(java.util.Date)]
    global::org.xmlvm._nElement _r0;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    _r4_o = this;
    _r5_o = n1;
    _r0.l = ((global::java.util.Date) _r4_o)._fmilliseconds;
    _r2.l = ((global::java.util.Date) _r5_o)._fmilliseconds;
    _r0.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r0.i >= 0) goto label10;
    _r0.i = 1;
    label9:;
    return _r0.i!=0;
    label10:;
    _r0.i = 0;
    goto label9;
//XMLVM_END_WRAPPER[java.util.Date: boolean before(java.util.Date)]
}

public override global::System.Object clone(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: java.lang.Object clone()]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    try {
    _r0_o = base.clone();
    }
    catch (global::System.Exception e) {
 global::org.xmlvm._nExceptionAdapter ex = e as global::org.xmlvm._nExceptionAdapter ?? new global::org.xmlvm._nExceptionAdapter(e.ToString(), e.ToJavaException());
        global::System.Object _java_exception = ex.getJavaException();
        if (_java_exception is global::java.lang.CloneNotSupportedException) {
            _ex = ex;
            goto label5;
        }
        throw ex;
    } // end catch
    label4:;
    return (global::java.lang.Object) _r0_o;
    label5:;
    _r0_o = _ex.getJavaException();
    _ex = null;
    _r0_o = null;
    goto label4;
//XMLVM_END_WRAPPER[java.util.Date: java.lang.Object clone()]
}

public virtual int compareTo(global::java.util.Date n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: int compareTo(java.util.Date)]
    global::org.xmlvm._nElement _r0;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    _r4_o = this;
    _r5_o = n1;
    _r0.l = ((global::java.util.Date) _r4_o)._fmilliseconds;
    _r2.l = ((global::java.util.Date) _r5_o)._fmilliseconds;
    _r0.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r0.i >= 0) goto label10;
    _r0.i = -1;
    label9:;
    return _r0.i;
    label10:;
    _r0.l = ((global::java.util.Date) _r4_o)._fmilliseconds;
    _r2.l = ((global::java.util.Date) _r5_o)._fmilliseconds;
    _r0.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r0.i != 0) goto label20;
    _r0.i = 0;
    goto label9;
    label20:;
    _r0.i = 1;
    goto label9;
//XMLVM_END_WRAPPER[java.util.Date: int compareTo(java.util.Date)]
}

public override bool equals(global::java.lang.Object n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: boolean equals(java.lang.Object)]
    global::org.xmlvm._nElement _r0;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    _r4_o = this;
    _r5_o = n1;
    if (_r5_o == _r4_o) goto label18;
    _r0.i = ((_r5_o != null) && (_r5_o is global::java.util.Date)) ? 1 : 0;
    if (_r0.i == 0) goto label16;
    _r0.l = ((global::java.util.Date) _r4_o)._fmilliseconds;
    _r2.l = ((global::java.util.Date) _r5_o)._fmilliseconds;
    _r0.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r0.i == 0) goto label18;
    label16:;
    _r0.i = 0;
    label17:;
    return _r0.i!=0;
    label18:;
    _r0.i = 1;
    goto label17;
//XMLVM_END_WRAPPER[java.util.Date: boolean equals(java.lang.Object)]
}

public virtual int getDate(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: int getDate()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r3_o = null;
    _r3_o = this;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 5;
    _r0.i = ((global::java.util.GregorianCalendar) _r0_o).get((int) _r1.i);
    return _r0.i;
//XMLVM_END_WRAPPER[java.util.Date: int getDate()]
}

public virtual int getDay(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: int getDay()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r3_o = null;
    _r3_o = this;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 7;
    _r0.i = ((global::java.util.GregorianCalendar) _r0_o).get((int) _r1.i);
    _r1.i = 1;
    _r0.i = _r0.i - _r1.i;
    return _r0.i;
//XMLVM_END_WRAPPER[java.util.Date: int getDay()]
}

public virtual int getHours(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: int getHours()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r3_o = null;
    _r3_o = this;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 11;
    _r0.i = ((global::java.util.GregorianCalendar) _r0_o).get((int) _r1.i);
    return _r0.i;
//XMLVM_END_WRAPPER[java.util.Date: int getHours()]
}

public virtual int getMinutes(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: int getMinutes()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r3_o = null;
    _r3_o = this;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 12;
    _r0.i = ((global::java.util.GregorianCalendar) _r0_o).get((int) _r1.i);
    return _r0.i;
//XMLVM_END_WRAPPER[java.util.Date: int getMinutes()]
}

public virtual int getMonth(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: int getMonth()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r3_o = null;
    _r3_o = this;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 2;
    _r0.i = ((global::java.util.GregorianCalendar) _r0_o).get((int) _r1.i);
    return _r0.i;
//XMLVM_END_WRAPPER[java.util.Date: int getMonth()]
}

public virtual int getSeconds(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: int getSeconds()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r3_o = null;
    _r3_o = this;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 13;
    _r0.i = ((global::java.util.GregorianCalendar) _r0_o).get((int) _r1.i);
    return _r0.i;
//XMLVM_END_WRAPPER[java.util.Date: int getSeconds()]
}

public virtual long getTime(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: long getTime()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r2_o = null;
    _r2_o = this;
    _r0.l = ((global::java.util.Date) _r2_o)._fmilliseconds;
    return _r0.l;
//XMLVM_END_WRAPPER[java.util.Date: long getTime()]
}

public virtual int getTimezoneOffset(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: int getTimezoneOffset()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r3_o = null;
    _r3_o = this;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 15;
    _r1.i = ((global::java.util.GregorianCalendar) _r0_o).get((int) _r1.i);
    _r2.i = 16;
    _r0.i = ((global::java.util.GregorianCalendar) _r0_o).get((int) _r2.i);
    _r0.i = _r0.i + _r1.i;
    _r0.i = -_r0.i;
    _r1.i = 60000;
    _r0.i = _r0.i / _r1.i;
    return _r0.i;
//XMLVM_END_WRAPPER[java.util.Date: int getTimezoneOffset()]
}

public virtual int getYear(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: int getYear()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r3_o = null;
    _r3_o = this;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 1;
    _r0.i = ((global::java.util.GregorianCalendar) _r0_o).get((int) _r1.i);
    _r1.i = 1900;
    _r0.i = _r0.i - _r1.i;
    return _r0.i;
//XMLVM_END_WRAPPER[java.util.Date: int getYear()]
}

public override int hashCode(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: int hashCode()]
    global::org.xmlvm._nElement _r0;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r3_o = null;
    _r3_o = this;
    _r0.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    _r2.i = 32;
    _r0.l = (long) (((ulong) _r0.l) >> (0x3f & (_r2.i)));
    _r0.i = (int) _r0.l;
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    _r1.i = (int) _r1.l;
    _r0.i = _r0.i ^ _r1.i;
    return _r0.i;
//XMLVM_END_WRAPPER[java.util.Date: int hashCode()]
}

private static int parse(global::java.lang.String n1, global::org.xmlvm._nArrayAdapter<global::System.Object> n2){
//XMLVM_BEGIN_WRAPPER[java.util.Date: int parse(java.lang.String, java.lang.String[])]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::org.xmlvm._nElement _r5;
    global::org.xmlvm._nElement _r6;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r8_o = null;
    global::System.Object _r9_o = null;
    _r8_o = n1;
    _r9_o = n2;
    _r2.i = 0;
    _r6.i = ((global::org.xmlvm._nIArray) _r9_o).Length;
    _r5.i = ((global::java.lang.String) _r8_o).length();
    _r7.i = _r2.i;
    label7:;
    if (_r7.i < _r6.i) goto label11;
    _r0.i = -1;
    label10:;
    return _r0.i;
    label11:;
    _r1.i = 1;
    _r3_o = ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r9_o)[_r7.i];
    _r0_o = _r8_o;
    _r4.i = _r2.i;
    _r0.i = ((global::java.lang.String) _r0_o).regionMatches(0!=_r1.i, (int) _r2.i, (global::java.lang.String) _r3_o, (int) _r4.i, (int) _r5.i) ? 1 : 0;
    if (_r0.i == 0) goto label24;
    _r0.i = _r7.i;
    goto label10;
    label24:;
    _r0.i = _r7.i + 1;
    _r7.i = _r0.i;
    goto label7;
//XMLVM_END_WRAPPER[java.util.Date: int parse(java.lang.String, java.lang.String[])]
}

public static long parse(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: long parse(java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::org.xmlvm._nElement _r6;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::org.xmlvm._nElement _r9;
    global::System.Object _r9_o = null;
    global::org.xmlvm._nElement _r10;
    global::org.xmlvm._nElement _r11;
    global::org.xmlvm._nElement _r12;
    global::org.xmlvm._nElement _r13;
    global::System.Object _r13_o = null;
    global::org.xmlvm._nElement _r14;
    global::org.xmlvm._nElement _r15;
    global::org.xmlvm._nElement _r16;
    global::System.Object _r17_o = null;
    global::org.xmlvm._nElement _r18;
    global::org.xmlvm._nElement _r19;
    global::org.xmlvm._nElement _r20;
    global::System.Object _r20_o = null;
    global::org.xmlvm._nElement _r21;
    global::System.Object _r21_o = null;
    global::org.xmlvm._nElement _r22;
    global::org.xmlvm._nElement _r23;
    global::org.xmlvm._nElement _r24;
    global::org.xmlvm._nElement _r25;
    global::System.Object _r25_o = null;
    _r25_o = n1;
    if (_r25_o != null) goto label17;
    _r25_o = new global::java.lang.IllegalArgumentException();
    // Value=luni.06
    _r3_o = new global::java.lang.String();
    ((global::java.lang.String)_r3_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)108)), unchecked((char) unchecked((uint) 117)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 46)), unchecked((char) unchecked((uint) 48)), unchecked((char) unchecked((uint) 54))}));
    _r3_o = global::org.apache.harmony.luni.@internal.nls.Messages.getString((global::java.lang.String) _r3_o);
    _r0_o = _r25_o;
    _r1_o = _r3_o;
    ((global::java.lang.IllegalArgumentException) _r0_o).@this((global::java.lang.String) _r1_o);
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r25_o);
    label17:;
    _r3.i = 0;
    _r4.i = 0;
    _r5.i = 0;
    _r6.i = ((global::java.lang.String) _r25_o).length();
    _r7.i = 0;
    _r8.i = -1;
    _r9.i = -1;
    _r10.i = -1;
    _r11.i = -1;
    _r12.i = -1;
    _r13.i = -1;
    _r14.i = 0;
    _r15.i = 0;
    _r16.i = 0;
    _r17_o = new global::java.lang.StringBuilder();
    ((global::java.lang.StringBuilder) _r17_o).@this();
    _r23.i = _r16.i;
    _r16.i = _r3.i;
    _r3.i = _r23.i;
    _r24.i = _r14.i;
    _r14.i = _r5.i;
    _r5.i = _r10.i;
    _r10.i = _r12.i;
    _r12.i = _r8.i;
    _r8.i = _r13.i;
    _r13.i = _r7.i;
    _r7.i = _r15.i;
    _r15.i = _r4.i;
    _r4.i = _r9.i;
    _r9.i = _r24.i;
    label59:;
    if (_r14.i <= _r6.i) goto label155;
    _r25.i = -1;
    _r0.i = _r12.i;
    _r1.i = _r25.i;
    if (_r0.i == _r1.i) goto label1111;
    _r25.i = -1;
    _r0.i = _r4.i;
    _r1.i = _r25.i;
    if (_r0.i == _r1.i) goto label1111;
    _r25.i = -1;
    _r0.i = _r5.i;
    _r1.i = _r25.i;
    if (_r0.i == _r1.i) goto label1111;
    _r25.i = -1;
    _r0.i = _r11.i;
    _r1.i = _r25.i;
    if (_r0.i != _r1.i) goto label1124;
    _r25.i = 0;
    _r13.i = _r25.i;
    label93:;
    _r25.i = -1;
    _r0.i = _r10.i;
    _r1.i = _r25.i;
    if (_r0.i != _r1.i) goto label1120;
    _r25.i = 0;
    label102:;
    _r6.i = -1;
    if (_r8.i != _r6.i) goto label107;
    _r6.i = 0;
    _r8.i = _r6.i;
    label107:;
    _r6.i = global::java.util.Date._fcreationYear;
    _r10.i = 80;
    _r6.i = _r6.i - _r10.i;
    if (_r12.i >= _r6.i) goto label1077;
    _r6.i = _r12.i + 2000;
    _r10.i = _r6.i;
    label117:;
    _r14.i = _r25.i - _r7.i;
    if (_r3.i == 0) goto label1093;
    _r25.i = 24;
    _r0.i = _r9.i;
    _r1.i = _r25.i;
    if (_r0.i >= _r1.i) goto label135;
    _r25.i = -24;
    _r0.i = _r9.i;
    _r1.i = _r25.i;
    if (_r0.i > _r1.i) goto label1086;
    label135:;
    _r25.i = _r9.i / 100;
    _r25.i = _r13.i - _r25.i;
    _r3.i = _r9.i % 100;
    _r3.i = _r14.i - _r3.i;
    _r7.i = _r3.i;
    _r6.i = _r25.i;
    label146:;
    _r25.i = 1900;
    _r3.i = _r10.i - _r25.i;
    _r3.l = global::java.util.Date.UTC((int) _r3.i, (int) _r4.i, (int) _r5.i, (int) _r6.i, (int) _r7.i, (int) _r8.i);
    label154:;
    return _r3.l;
    label155:;
    if (_r14.i >= _r6.i) goto label392;
    _r0_o = _r25_o;
    _r1.i = _r14.i;
    _r18.i = ((global::java.lang.String) _r0_o).charAt((int) _r1.i);
    label164:;
    _r14.i = _r14.i + 1;
    _r19.i = 40;
    _r0.i = _r18.i;
    _r1.i = _r19.i;
    if (_r0.i != _r1.i) goto label176;
    _r15.i = _r15.i + 1;
    label176:;
    if (_r15.i <= 0) goto label1145;
    _r19.i = 41;
    _r0.i = _r18.i;
    _r1.i = _r19.i;
    if (_r0.i != _r1.i) goto label188;
    _r15.i = _r15.i + -1;
    label188:;
    if (_r15.i != 0) goto label59;
    _r18.i = 32;
    _r23.i = _r18.i;
    _r18.i = _r15.i;
    _r15.i = _r23.i;
    label198:;
    _r19.i = 0;
    _r20.i = 97;
    _r0.i = _r20.i;
    _r1.i = _r15.i;
    if (_r0.i > _r1.i) goto label214;
    _r20.i = 122;
    _r0.i = _r15.i;
    _r1.i = _r20.i;
    if (_r0.i <= _r1.i) goto label228;
    label214:;
    _r20.i = 65;
    _r0.i = _r20.i;
    _r1.i = _r15.i;
    if (_r0.i > _r1.i) goto label396;
    _r20.i = 90;
    _r0.i = _r15.i;
    _r1.i = _r20.i;
    if (_r0.i > _r1.i) goto label396;
    label228:;
    _r19.i = 1;
    label230:;
    _r20.i = 2;
    _r0.i = _r13.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label789;
    _r20.i = 2;
    _r0.i = _r19.i;
    _r1.i = _r20.i;
    if (_r0.i == _r1.i) goto label789;
    _r13_o = ((global::java.lang.StringBuilder) _r17_o).toString();
    _r13.i = global::java.lang.Integer.parseInt((global::java.lang.String) _r13_o);
    _r20.i = 0;
    _r0_o = _r17_o;
    _r1.i = _r20.i;
    ((global::java.lang.StringBuilder) _r0_o).setLength((int) _r1.i);
    _r20.i = 43;
    _r0.i = _r16.i;
    _r1.i = _r20.i;
    if (_r0.i == _r1.i) goto label278;
    _r20.i = 45;
    _r0.i = _r16.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label465;
    label278:;
    if (_r9.i != 0) goto label459;
    _r3.i = 1;
    _r9.i = 58;
    if (_r15.i != _r9.i) goto label1142;
    _r7.i = 45;
    _r0.i = _r16.i;
    _r1.i = _r7.i;
    if (_r0.i != _r1.i) goto label443;
    _r7.i = _r14.i + 2;
    _r0_o = _r25_o;
    _r1.i = _r14.i;
    _r2.i = _r7.i;
    _r7_o = ((global::java.lang.String) _r0_o).substring((int) _r1.i, (int) _r2.i);
    _r7.i = global::java.lang.Integer.parseInt((global::java.lang.String) _r7_o);
    _r7.i = -_r7.i;
    label307:;
    _r9.i = _r14.i + 2;
    label309:;
    _r14.i = 45;
    _r0.i = _r16.i;
    _r1.i = _r14.i;
    if (_r0.i != _r1.i) goto label317;
    _r13.i = -_r13.i;
    label317:;
    _r14.i = 0;
    _r23.i = _r7.i;
    _r7.i = _r8.i;
    _r8.i = _r10.i;
    _r10.i = _r5.i;
    _r5.i = _r13.i;
    _r13.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r4.i;
    _r4.i = _r23.i;
    label329:;
    _r16.i = 43;
    _r0.i = _r15.i;
    _r1.i = _r16.i;
    if (_r0.i == _r1.i) goto label350;
    _r16.i = -1;
    _r0.i = _r12.i;
    _r1.i = _r16.i;
    if (_r0.i == _r1.i) goto label1053;
    _r16.i = 45;
    _r0.i = _r15.i;
    _r1.i = _r16.i;
    if (_r0.i != _r1.i) goto label1053;
    label350:;
    _r14.i = _r15.i;
    label351:;
    _r16.i = 1;
    _r0.i = _r19.i;
    _r1.i = _r16.i;
    if (_r0.i == _r1.i) goto label367;
    _r16.i = 2;
    _r0.i = _r19.i;
    _r1.i = _r16.i;
    if (_r0.i != _r1.i) goto label373;
    label367:;
    _r0_o = _r17_o;
    _r1.i = _r15.i;
    ((global::java.lang.StringBuilder) _r0_o).append((char) _r1.i);
    label373:;
    _r15.i = _r18.i;
    _r16.i = _r14.i;
    _r14.i = _r13.i;
    _r13.i = _r19.i;
    _r23.i = _r9.i;
    _r9.i = _r5.i;
    _r5.i = _r10.i;
    _r10.i = _r8.i;
    _r8.i = _r7.i;
    _r7.i = _r4.i;
    _r4.i = _r11.i;
    _r11.i = _r23.i;
    goto label59;
    label392:;
    _r18.i = 13;
    goto label164;
    label396:;
    _r20.i = 48;
    _r0.i = _r20.i;
    _r1.i = _r15.i;
    if (_r0.i > _r1.i) goto label414;
    _r20.i = 57;
    _r0.i = _r15.i;
    _r1.i = _r20.i;
    if (_r0.i > _r1.i) goto label414;
    _r19.i = 2;
    goto label230;
    label414:;
    _r20.i = global::java.lang.Character.isSpace((char) _r15.i) ? 1 : 0;
    if (_r20.i != 0) goto label230;
    // Value=,+-:/
    _r20_o = new global::java.lang.String();
    ((global::java.lang.String)_r20_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)44)), unchecked((char) unchecked((uint) 43)), unchecked((char) unchecked((uint) 45)), unchecked((char) unchecked((uint) 58)), unchecked((char) unchecked((uint) 47))}));
    _r0_o = _r20_o;
    _r1.i = _r15.i;
    _r20.i = ((global::java.lang.String) _r0_o).indexOf((int) _r1.i);
    _r21.i = -1;
    _r0.i = _r20.i;
    _r1.i = _r21.i;
    if (_r0.i != _r1.i) goto label230;
    _r25_o = new global::java.lang.IllegalArgumentException();
    ((global::java.lang.IllegalArgumentException) _r25_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r25_o);
    label443:;
    _r7.i = _r14.i + 2;
    _r0_o = _r25_o;
    _r1.i = _r14.i;
    _r2.i = _r7.i;
    _r7_o = ((global::java.lang.String) _r0_o).substring((int) _r1.i, (int) _r2.i);
    _r7.i = global::java.lang.Integer.parseInt((global::java.lang.String) _r7_o);
    goto label307;
    label459:;
    _r25_o = new global::java.lang.IllegalArgumentException();
    ((global::java.lang.IllegalArgumentException) _r25_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r25_o);
    label465:;
    _r20.i = 70;
    _r0.i = _r13.i;
    _r1.i = _r20.i;
    if (_r0.i < _r1.i) goto label519;
    _r20.i = -1;
    _r0.i = _r12.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label513;
    _r12.i = global::java.lang.Character.isSpace((char) _r15.i) ? 1 : 0;
    if (_r12.i != 0) goto label497;
    _r12.i = 44;
    if (_r15.i == _r12.i) goto label497;
    _r12.i = 47;
    if (_r15.i == _r12.i) goto label497;
    _r12.i = 13;
    if (_r15.i != _r12.i) goto label513;
    label497:;
    _r12.i = _r13.i;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    _r23.i = _r10.i;
    _r10.i = _r5.i;
    _r5.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r8.i;
    _r8.i = _r23.i;
    goto label329;
    label513:;
    _r25_o = new global::java.lang.IllegalArgumentException();
    ((global::java.lang.IllegalArgumentException) _r25_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r25_o);
    label519:;
    _r20.i = 58;
    _r0.i = _r15.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label570;
    _r20.i = -1;
    _r0.i = _r11.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label545;
    _r11.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r8.i;
    _r8.i = _r10.i;
    _r10.i = _r5.i;
    _r5.i = _r9.i;
    _r9.i = _r13.i;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    goto label329;
    label545:;
    _r20.i = -1;
    _r0.i = _r10.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label564;
    _r10.i = _r5.i;
    _r5.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r8.i;
    _r8.i = _r13.i;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    goto label329;
    label564:;
    _r25_o = new global::java.lang.IllegalArgumentException();
    ((global::java.lang.IllegalArgumentException) _r25_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r25_o);
    label570:;
    _r20.i = 47;
    _r0.i = _r15.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label627;
    _r20.i = -1;
    _r0.i = _r4.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label602;
    _r4.i = 1;
    _r4.i = _r13.i - _r4.i;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    _r23.i = _r8.i;
    _r8.i = _r10.i;
    _r10.i = _r5.i;
    _r5.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r23.i;
    goto label329;
    label602:;
    _r20.i = -1;
    _r0.i = _r5.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label621;
    _r5.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r8.i;
    _r8.i = _r10.i;
    _r10.i = _r13.i;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    goto label329;
    label621:;
    _r25_o = new global::java.lang.IllegalArgumentException();
    ((global::java.lang.IllegalArgumentException) _r25_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r25_o);
    label627:;
    _r20.i = global::java.lang.Character.isSpace((char) _r15.i) ? 1 : 0;
    if (_r20.i != 0) goto label654;
    _r20.i = 44;
    _r0.i = _r15.i;
    _r1.i = _r20.i;
    if (_r0.i == _r1.i) goto label654;
    _r20.i = 45;
    _r0.i = _r15.i;
    _r1.i = _r20.i;
    if (_r0.i == _r1.i) goto label654;
    _r20.i = 13;
    _r0.i = _r15.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label754;
    label654:;
    _r20.i = -1;
    _r0.i = _r11.i;
    _r1.i = _r20.i;
    if (_r0.i == _r1.i) goto label680;
    _r20.i = -1;
    _r0.i = _r10.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label680;
    _r10.i = _r5.i;
    _r5.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r8.i;
    _r8.i = _r13.i;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    goto label329;
    label680:;
    _r20.i = -1;
    _r0.i = _r10.i;
    _r1.i = _r20.i;
    if (_r0.i == _r1.i) goto label706;
    _r20.i = -1;
    _r0.i = _r8.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label706;
    _r8.i = _r10.i;
    _r10.i = _r5.i;
    _r5.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r13.i;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    goto label329;
    label706:;
    _r20.i = -1;
    _r0.i = _r5.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label725;
    _r5.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r8.i;
    _r8.i = _r10.i;
    _r10.i = _r13.i;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    goto label329;
    label725:;
    _r20.i = -1;
    _r0.i = _r12.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label748;
    _r12.i = _r13.i;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    _r23.i = _r10.i;
    _r10.i = _r5.i;
    _r5.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r8.i;
    _r8.i = _r23.i;
    goto label329;
    label748:;
    _r25_o = new global::java.lang.IllegalArgumentException();
    ((global::java.lang.IllegalArgumentException) _r25_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r25_o);
    label754:;
    _r20.i = -1;
    _r0.i = _r12.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label783;
    _r12.i = -1;
    if (_r4.i == _r12.i) goto label783;
    _r12.i = -1;
    if (_r5.i == _r12.i) goto label783;
    _r12.i = _r13.i;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    _r23.i = _r10.i;
    _r10.i = _r5.i;
    _r5.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r8.i;
    _r8.i = _r23.i;
    goto label329;
    label783:;
    _r25_o = new global::java.lang.IllegalArgumentException();
    ((global::java.lang.IllegalArgumentException) _r25_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r25_o);
    label789:;
    _r20.i = 1;
    _r0.i = _r13.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label1127;
    _r13.i = 1;
    _r0.i = _r19.i;
    _r1.i = _r13.i;
    if (_r0.i == _r1.i) goto label1127;
    _r13_o = ((global::java.lang.StringBuilder) _r17_o).toString();
    _r13_o = ((global::java.lang.String) _r13_o).toUpperCase();
    _r20.i = 0;
    _r0_o = _r17_o;
    _r1.i = _r20.i;
    ((global::java.lang.StringBuilder) _r0_o).setLength((int) _r1.i);
    _r20.i = ((global::java.lang.String) _r13_o).length();
    _r21.i = 1;
    _r0.i = _r20.i;
    _r1.i = _r21.i;
    if (_r0.i != _r1.i) goto label837;
    _r25_o = new global::java.lang.IllegalArgumentException();
    ((global::java.lang.IllegalArgumentException) _r25_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r25_o);
    label837:;
    // Value=AM
    _r20_o = new global::java.lang.String();
    ((global::java.lang.String)_r20_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)65)), unchecked((char) unchecked((uint) 77))}));
    _r0_o = _r13_o;
    _r1_o = _r20_o;
    _r20.i = ((global::java.lang.String) _r0_o).equals((global::java.lang.Object) _r1_o) ? 1 : 0;
    if (_r20.i == 0) goto label881;
    _r13.i = 12;
    if (_r11.i != _r13.i) goto label868;
    _r11.i = 0;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    _r23.i = _r8.i;
    _r8.i = _r10.i;
    _r10.i = _r5.i;
    _r5.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r23.i;
    goto label329;
    label868:;
    _r13.i = 1;
    if (_r11.i < _r13.i) goto label875;
    _r13.i = 12;
    if (_r11.i <= _r13.i) goto label1127;
    label875:;
    _r25_o = new global::java.lang.IllegalArgumentException();
    ((global::java.lang.IllegalArgumentException) _r25_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r25_o);
    label881:;
    // Value=PM
    _r20_o = new global::java.lang.String();
    ((global::java.lang.String)_r20_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)80)), unchecked((char) unchecked((uint) 77))}));
    _r0_o = _r13_o;
    _r1_o = _r20_o;
    _r20.i = ((global::java.lang.String) _r0_o).equals((global::java.lang.Object) _r1_o) ? 1 : 0;
    if (_r20.i == 0) goto label927;
    _r13.i = 12;
    if (_r11.i != _r13.i) goto label914;
    _r11.i = 0;
    label897:;
    _r11.i = _r11.i + 12;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    _r23.i = _r8.i;
    _r8.i = _r10.i;
    _r10.i = _r5.i;
    _r5.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r23.i;
    goto label329;
    label914:;
    _r13.i = 1;
    if (_r11.i < _r13.i) goto label921;
    _r13.i = 12;
    if (_r11.i <= _r13.i) goto label897;
    label921:;
    _r25_o = new global::java.lang.IllegalArgumentException();
    ((global::java.lang.IllegalArgumentException) _r25_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r25_o);
    label927:;
// Red class access removed: java.text.DateFormatSymbols new-instance
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.DateFormatSymbols new-instance");
    _r21_o = global::java.util.Locale._fUS;
// Red class access removed: java.text.DateFormatSymbols <init>
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.DateFormatSymbols <init>");
// Red class access removed: java.text.DateFormatSymbols getWeekdays
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.DateFormatSymbols getWeekdays");
// Red class access removed: java.text.DateFormatSymbols getMonths
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.DateFormatSymbols getMonths");
    _r0_o = _r13_o;
    _r1_o = _r21_o;
    _r21.i = global::java.util.Date.parse((global::java.lang.String) _r0_o, (global::org.xmlvm._nArrayAdapter<global::System.Object>) _r1_o);
    _r22.i = -1;
    _r0.i = _r21.i;
    _r1.i = _r22.i;
    if (_r0.i != _r1.i) goto label1127;
    _r21.i = -1;
    _r0.i = _r4.i;
    _r1.i = _r21.i;
    if (_r0.i != _r1.i) goto label978;
    _r0_o = _r13_o;
    _r1_o = _r20_o;
    _r4.i = global::java.util.Date.parse((global::java.lang.String) _r0_o, (global::org.xmlvm._nArrayAdapter<global::System.Object>) _r1_o);
    _r20.i = -1;
    _r0.i = _r4.i;
    _r1.i = _r20.i;
    if (_r0.i != _r1.i) goto label1127;
    label978:;
    _r3.i = _r4.i;
    // Value=GMT
    _r4_o = new global::java.lang.String();
    ((global::java.lang.String)_r4_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)71)), unchecked((char) unchecked((uint) 77)), unchecked((char) unchecked((uint) 84))}));
    _r4.i = ((global::java.lang.String) _r13_o).equals((global::java.lang.Object) _r4_o) ? 1 : 0;
    if (_r4.i != 0) goto label1003;
    // Value=UT
    _r4_o = new global::java.lang.String();
    ((global::java.lang.String)_r4_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)85)), unchecked((char) unchecked((uint) 84))}));
    _r4.i = ((global::java.lang.String) _r13_o).equals((global::java.lang.Object) _r4_o) ? 1 : 0;
    if (_r4.i != 0) goto label1003;
    // Value=UTC
    _r4_o = new global::java.lang.String();
    ((global::java.lang.String)_r4_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)85)), unchecked((char) unchecked((uint) 84)), unchecked((char) unchecked((uint) 67))}));
    _r4.i = ((global::java.lang.String) _r13_o).equals((global::java.lang.Object) _r4_o) ? 1 : 0;
    if (_r4.i == 0) goto label1021;
    label1003:;
    _r4.i = 1;
    _r9.i = 0;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    _r23.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r3.i;
    _r3.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r8.i;
    _r8.i = _r10.i;
    _r10.i = _r5.i;
    _r5.i = _r23.i;
    goto label329;
    label1021:;
    _r4.i = global::java.util.Date.zone((global::java.lang.String) _r13_o);
    if (_r4.i == 0) goto label1047;
    _r9.i = 1;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    _r23.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r8.i;
    _r8.i = _r10.i;
    _r10.i = _r5.i;
    _r5.i = _r23.i;
    _r24.i = _r3.i;
    _r3.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r24.i;
    goto label329;
    label1047:;
    _r25_o = new global::java.lang.IllegalArgumentException();
    ((global::java.lang.IllegalArgumentException) _r25_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r25_o);
    label1053:;
    _r16.i = global::java.lang.Character.isSpace((char) _r15.i) ? 1 : 0;
    if (_r16.i != 0) goto label351;
    _r16.i = 44;
    _r0.i = _r15.i;
    _r1.i = _r16.i;
    if (_r0.i == _r1.i) goto label351;
    _r16.i = 2;
    _r0.i = _r19.i;
    _r1.i = _r16.i;
    if (_r0.i == _r1.i) goto label351;
    _r14.i = 0;
    goto label351;
    label1077:;
    _r6.i = 100;
    if (_r12.i >= _r6.i) goto label1117;
    _r6.i = _r12.i + 1900;
    _r10.i = _r6.i;
    goto label117;
    label1086:;
    _r25.i = _r13.i - _r9.i;
    _r7.i = _r14.i;
    _r6.i = _r25.i;
    goto label146;
    label1093:;
    _r9_o = new global::java.util.Date();
    _r25.i = 1900;
    _r10.i = _r10.i - _r25.i;
    _r11.i = _r4.i;
    _r12.i = _r5.i;
    _r15.i = _r8.i;
    ((global::java.util.Date) _r9_o).@this((int) _r10.i, (int) _r11.i, (int) _r12.i, (int) _r13.i, (int) _r14.i, (int) _r15.i);
    _r3.l = ((global::java.util.Date) _r9_o).getTime();
    goto label154;
    label1111:;
    _r25_o = new global::java.lang.IllegalArgumentException();
    ((global::java.lang.IllegalArgumentException) _r25_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r25_o);
    label1117:;
    _r10.i = _r12.i;
    goto label117;
    label1120:;
    _r25.i = _r10.i;
    goto label102;
    label1124:;
    _r13.i = _r11.i;
    goto label93;
    label1127:;
    _r13.i = _r14.i;
    _r14.i = _r16.i;
    _r23.i = _r8.i;
    _r8.i = _r10.i;
    _r10.i = _r5.i;
    _r5.i = _r9.i;
    _r9.i = _r11.i;
    _r11.i = _r4.i;
    _r4.i = _r7.i;
    _r7.i = _r23.i;
    goto label329;
    label1142:;
    _r9.i = _r14.i;
    goto label309;
    label1145:;
    _r23.i = _r18.i;
    _r18.i = _r15.i;
    _r15.i = _r23.i;
    goto label198;
//XMLVM_END_WRAPPER[java.util.Date: long parse(java.lang.String)]
}

public virtual void setDate(int n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void setDate(int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    _r3_o = this;
    _r4.i = n1;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 5;
    ((global::java.util.GregorianCalendar) _r0_o).set((int) _r1.i, (int) _r4.i);
    _r0.l = ((global::java.util.GregorianCalendar) _r0_o).getTimeInMillis();
    ((global::java.util.Date) _r3_o)._fmilliseconds = _r0.l;
    return;
//XMLVM_END_WRAPPER[java.util.Date: void setDate(int)]
}

public virtual void setHours(int n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void setHours(int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    _r3_o = this;
    _r4.i = n1;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 11;
    ((global::java.util.GregorianCalendar) _r0_o).set((int) _r1.i, (int) _r4.i);
    _r0.l = ((global::java.util.GregorianCalendar) _r0_o).getTimeInMillis();
    ((global::java.util.Date) _r3_o)._fmilliseconds = _r0.l;
    return;
//XMLVM_END_WRAPPER[java.util.Date: void setHours(int)]
}

public virtual void setMinutes(int n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void setMinutes(int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    _r3_o = this;
    _r4.i = n1;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 12;
    ((global::java.util.GregorianCalendar) _r0_o).set((int) _r1.i, (int) _r4.i);
    _r0.l = ((global::java.util.GregorianCalendar) _r0_o).getTimeInMillis();
    ((global::java.util.Date) _r3_o)._fmilliseconds = _r0.l;
    return;
//XMLVM_END_WRAPPER[java.util.Date: void setMinutes(int)]
}

public virtual void setMonth(int n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void setMonth(int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    _r3_o = this;
    _r4.i = n1;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 2;
    ((global::java.util.GregorianCalendar) _r0_o).set((int) _r1.i, (int) _r4.i);
    _r0.l = ((global::java.util.GregorianCalendar) _r0_o).getTimeInMillis();
    ((global::java.util.Date) _r3_o)._fmilliseconds = _r0.l;
    return;
//XMLVM_END_WRAPPER[java.util.Date: void setMonth(int)]
}

public virtual void setSeconds(int n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void setSeconds(int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    _r3_o = this;
    _r4.i = n1;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 13;
    ((global::java.util.GregorianCalendar) _r0_o).set((int) _r1.i, (int) _r4.i);
    _r0.l = ((global::java.util.GregorianCalendar) _r0_o).getTimeInMillis();
    ((global::java.util.Date) _r3_o)._fmilliseconds = _r0.l;
    return;
//XMLVM_END_WRAPPER[java.util.Date: void setSeconds(int)]
}

public virtual void setTime(long n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void setTime(long)]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    _r0_o = this;
    _r1.l = n1;
    ((global::java.util.Date) _r0_o)._fmilliseconds = _r1.l;
    return;
//XMLVM_END_WRAPPER[java.util.Date: void setTime(long)]
}

public virtual void setYear(int n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void setYear(int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    _r3_o = this;
    _r4.i = n1;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r3_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1.i = 1;
    _r2.i = _r4.i + 1900;
    ((global::java.util.GregorianCalendar) _r0_o).set((int) _r1.i, (int) _r2.i);
    _r0.l = ((global::java.util.GregorianCalendar) _r0_o).getTimeInMillis();
    ((global::java.util.Date) _r3_o)._fmilliseconds = _r0.l;
    return;
//XMLVM_END_WRAPPER[java.util.Date: void setYear(int)]
}

public virtual global::System.Object toGMTString(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: java.lang.String toGMTString()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r6_o = null;
    _r6_o = this;
// Red class access removed: java.text.SimpleDateFormat new-instance
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.SimpleDateFormat new-instance");
    // Value=d MMM 
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)100)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 77)), unchecked((char) unchecked((uint) 77)), unchecked((char) unchecked((uint) 77)), unchecked((char) unchecked((uint) 32))}));
    _r2_o = global::java.util.Locale._fUS;
// Red class access removed: java.text.SimpleDateFormat <init>
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.SimpleDateFormat <init>");
// Red class access removed: java.text.SimpleDateFormat new-instance
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.SimpleDateFormat new-instance");
    // Value= HH:mm:ss 'GMT'
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)32)), unchecked((char) unchecked((uint) 72)), unchecked((char) unchecked((uint) 72)), unchecked((char) unchecked((uint) 58)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 58)), unchecked((char) unchecked((uint) 115)), unchecked((char) unchecked((uint) 115)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 39)), unchecked((char) unchecked((uint) 71)), unchecked((char) unchecked((uint) 77)), unchecked((char) unchecked((uint) 84)), unchecked((char) unchecked((uint) 39))}));
    _r3_o = global::java.util.Locale._fUS;
// Red class access removed: java.text.SimpleDateFormat <init>
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.SimpleDateFormat <init>");
    // Value=GMT
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)71)), unchecked((char) unchecked((uint) 77)), unchecked((char) unchecked((uint) 84))}));
    _r2_o = global::java.util.TimeZone.getTimeZone((global::java.lang.String) _r2_o);
// Red class access removed: java.text.SimpleDateFormat setTimeZone
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.SimpleDateFormat setTimeZone");
// Red class access removed: java.text.SimpleDateFormat setTimeZone
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.SimpleDateFormat setTimeZone");
    _r3_o = new global::java.util.GregorianCalendar();
    ((global::java.util.GregorianCalendar) _r3_o).@this((global::java.util.TimeZone) _r2_o);
    _r4.l = ((global::java.util.Date) _r6_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r3_o).setTimeInMillis((long) _r4.l);
    _r2_o = new global::java.lang.StringBuilder();
// Red class access removed: java.text.SimpleDateFormat format
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.SimpleDateFormat format");
    _r0_o = global::java.lang.String.valueOf((global::java.lang.Object) _r0_o);
    ((global::java.lang.StringBuilder) _r2_o).@this((global::java.lang.String) _r0_o);
    _r0.i = 1;
    _r0.i = ((global::java.util.GregorianCalendar) _r3_o).get((int) _r0.i);
    _r0_o = ((global::java.lang.StringBuilder) _r2_o).append((int) _r0.i);
// Red class access removed: java.text.SimpleDateFormat format
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.SimpleDateFormat format");
    _r0_o = ((global::java.lang.StringBuilder) _r0_o).append((global::java.lang.String) _r1_o);
    _r0_o = ((global::java.lang.StringBuilder) _r0_o).toString();
    return (global::java.lang.String) _r0_o;
//XMLVM_END_WRAPPER[java.util.Date: java.lang.String toGMTString()]
}

public virtual global::System.Object toLocaleString(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: java.lang.String toLocaleString()]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    _r1_o = this;
// Red class access removed: java.text.DateFormat getDateTimeInstance
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.DateFormat getDateTimeInstance");
// Red class access removed: java.text.DateFormat format
throw new global::org.xmlvm._nNotYetImplementedException("Red class access removed: java.text.DateFormat format");
    return (global::java.lang.String) _r0_o;
//XMLVM_END_WRAPPER[java.util.Date: java.lang.String toLocaleString()]
}

public override global::System.Object toString(){
//XMLVM_BEGIN_WRAPPER[java.util.Date: java.lang.String toString()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::org.xmlvm._nElement _r6;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r8_o = null;
    _r8_o = this;
    _r7.i = 58;
    _r6.i = 1;
    _r5.i = 32;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.l = ((global::java.util.Date) _r8_o)._fmilliseconds;
    ((global::java.util.GregorianCalendar) _r0_o).@this((long) _r1.l);
    _r1_o = ((global::java.util.Calendar) _r0_o).getTimeZone();
    _r2.i = ((global::java.util.TimeZone) _r1_o).inDaylightTime((global::java.util.Date) _r8_o) ? 1 : 0;
    _r3.i = 0;
    _r4_o = global::java.util.Locale.getDefault();
    _r1_o = ((global::java.util.TimeZone) _r1_o).getDisplayName(0!=_r2.i, (int) _r3.i, (global::java.util.Locale) _r4_o);
    _r2_o = new global::java.lang.StringBuilder();
    _r3.i = 34;
    ((global::java.lang.StringBuilder) _r2_o).@this((int) _r3.i);
    _r3_o = global::java.util.Date._fdayOfWeekNames;
    _r4.i = 7;
    _r4.i = ((global::java.util.Calendar) _r0_o).get((int) _r4.i);
    _r4.i = _r4.i - _r6.i;
    _r3_o = ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r3_o)[_r4.i];
    ((global::java.lang.StringBuilder) _r2_o).append((global::java.lang.String) _r3_o);
    ((global::java.lang.StringBuilder) _r2_o).append((char) _r5.i);
    _r3_o = global::java.util.Date._fmonthNames;
    _r4.i = 2;
    _r4.i = ((global::java.util.Calendar) _r0_o).get((int) _r4.i);
    _r3_o = ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r3_o)[_r4.i];
    ((global::java.lang.StringBuilder) _r2_o).append((global::java.lang.String) _r3_o);
    ((global::java.lang.StringBuilder) _r2_o).append((char) _r5.i);
    _r3.i = 5;
    _r3.i = ((global::java.util.Calendar) _r0_o).get((int) _r3.i);
    _r3_o = ((global::java.util.Date) _r8_o).toTwoDigits((int) _r3.i);
    ((global::java.lang.StringBuilder) _r2_o).append((global::java.lang.String) _r3_o);
    ((global::java.lang.StringBuilder) _r2_o).append((char) _r5.i);
    _r3.i = 11;
    _r3.i = ((global::java.util.Calendar) _r0_o).get((int) _r3.i);
    _r3_o = ((global::java.util.Date) _r8_o).toTwoDigits((int) _r3.i);
    ((global::java.lang.StringBuilder) _r2_o).append((global::java.lang.String) _r3_o);
    ((global::java.lang.StringBuilder) _r2_o).append((char) _r7.i);
    _r3.i = 12;
    _r3.i = ((global::java.util.Calendar) _r0_o).get((int) _r3.i);
    _r3_o = ((global::java.util.Date) _r8_o).toTwoDigits((int) _r3.i);
    ((global::java.lang.StringBuilder) _r2_o).append((global::java.lang.String) _r3_o);
    ((global::java.lang.StringBuilder) _r2_o).append((char) _r7.i);
    _r3.i = 13;
    _r3.i = ((global::java.util.Calendar) _r0_o).get((int) _r3.i);
    _r3_o = ((global::java.util.Date) _r8_o).toTwoDigits((int) _r3.i);
    ((global::java.lang.StringBuilder) _r2_o).append((global::java.lang.String) _r3_o);
    ((global::java.lang.StringBuilder) _r2_o).append((char) _r5.i);
    ((global::java.lang.StringBuilder) _r2_o).append((global::java.lang.String) _r1_o);
    ((global::java.lang.StringBuilder) _r2_o).append((char) _r5.i);
    _r0.i = ((global::java.util.Calendar) _r0_o).get((int) _r6.i);
    ((global::java.lang.StringBuilder) _r2_o).append((int) _r0.i);
    _r0_o = ((global::java.lang.StringBuilder) _r2_o).toString();
    return (global::java.lang.String) _r0_o;
//XMLVM_END_WRAPPER[java.util.Date: java.lang.String toString()]
}

private global::System.Object toTwoDigits(int n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: java.lang.String toTwoDigits(int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    _r2_o = this;
    _r3.i = n1;
    _r0.i = 10;
    if (_r3.i < _r0.i) goto label18;
    _r0_o = new global::java.lang.StringBuilder();
    ((global::java.lang.StringBuilder) _r0_o).@this();
    _r0_o = ((global::java.lang.StringBuilder) _r0_o).append((int) _r3.i);
    _r0_o = ((global::java.lang.StringBuilder) _r0_o).toString();
    label17:;
    return (global::java.lang.String) _r0_o;
    label18:;
    _r0_o = new global::java.lang.StringBuilder();
    // Value=0
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)48))}));
    ((global::java.lang.StringBuilder) _r0_o).@this((global::java.lang.String) _r1_o);
    _r0_o = ((global::java.lang.StringBuilder) _r0_o).append((int) _r3.i);
    _r0_o = ((global::java.lang.StringBuilder) _r0_o).toString();
    goto label17;
//XMLVM_END_WRAPPER[java.util.Date: java.lang.String toTwoDigits(int)]
}

public static long UTC(int n1, int n2, int n3, int n4, int n5, int n6){
//XMLVM_BEGIN_WRAPPER[java.util.Date: long UTC(int, int, int, int, int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::org.xmlvm._nElement _r3;
    global::org.xmlvm._nElement _r4;
    global::org.xmlvm._nElement _r5;
    global::org.xmlvm._nElement _r6;
    global::org.xmlvm._nElement _r7;
    global::org.xmlvm._nElement _r8;
    global::org.xmlvm._nElement _r9;
    global::org.xmlvm._nElement _r10;
    global::org.xmlvm._nElement _r11;
    global::org.xmlvm._nElement _r12;
    _r7.i = n1;
    _r8.i = n2;
    _r9.i = n3;
    _r10.i = n4;
    _r11.i = n5;
    _r12.i = n6;
    _r0_o = new global::java.util.GregorianCalendar();
    _r1.i = 0;
    ((global::java.util.GregorianCalendar) _r0_o).@this(0!=_r1.i);
    // Value=GMT
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)71)), unchecked((char) unchecked((uint) 77)), unchecked((char) unchecked((uint) 84))}));
    _r1_o = global::java.util.TimeZone.getTimeZone((global::java.lang.String) _r1_o);
    ((global::java.util.GregorianCalendar) _r0_o).setTimeZone((global::java.util.TimeZone) _r1_o);
    _r1.i = _r7.i + 1900;
    _r2.i = _r8.i;
    _r3.i = _r9.i;
    _r4.i = _r10.i;
    _r5.i = _r11.i;
    _r6.i = _r12.i;
    ((global::java.util.GregorianCalendar) _r0_o).set((int) _r1.i, (int) _r2.i, (int) _r3.i, (int) _r4.i, (int) _r5.i, (int) _r6.i);
    _r0.l = ((global::java.util.GregorianCalendar) _r0_o).getTimeInMillis();
    return _r0.l;
//XMLVM_END_WRAPPER[java.util.Date: long UTC(int, int, int, int, int, int)]
}

private static int zone(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: int zone(java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r4_o = null;
    _r4_o = n1;
    _r3.i = -5;
    _r2.i = -6;
    _r1.i = -7;
    // Value=EST
    _r0_o = new global::java.lang.String();
    ((global::java.lang.String)_r0_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)69)), unchecked((char) unchecked((uint) 83)), unchecked((char) unchecked((uint) 84))}));
    _r0.i = ((global::java.lang.String) _r4_o).equals((global::java.lang.Object) _r0_o) ? 1 : 0;
    if (_r0.i == 0) goto label13;
    _r0.i = _r3.i;
    label12:;
    return _r0.i;
    label13:;
    // Value=EDT
    _r0_o = new global::java.lang.String();
    ((global::java.lang.String)_r0_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)69)), unchecked((char) unchecked((uint) 68)), unchecked((char) unchecked((uint) 84))}));
    _r0.i = ((global::java.lang.String) _r4_o).equals((global::java.lang.Object) _r0_o) ? 1 : 0;
    if (_r0.i == 0) goto label23;
    _r0.i = -4;
    goto label12;
    label23:;
    // Value=CST
    _r0_o = new global::java.lang.String();
    ((global::java.lang.String)_r0_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)67)), unchecked((char) unchecked((uint) 83)), unchecked((char) unchecked((uint) 84))}));
    _r0.i = ((global::java.lang.String) _r4_o).equals((global::java.lang.Object) _r0_o) ? 1 : 0;
    if (_r0.i == 0) goto label33;
    _r0.i = _r2.i;
    goto label12;
    label33:;
    // Value=CDT
    _r0_o = new global::java.lang.String();
    ((global::java.lang.String)_r0_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)67)), unchecked((char) unchecked((uint) 68)), unchecked((char) unchecked((uint) 84))}));
    _r0.i = ((global::java.lang.String) _r4_o).equals((global::java.lang.Object) _r0_o) ? 1 : 0;
    if (_r0.i == 0) goto label43;
    _r0.i = _r3.i;
    goto label12;
    label43:;
    // Value=MST
    _r0_o = new global::java.lang.String();
    ((global::java.lang.String)_r0_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)77)), unchecked((char) unchecked((uint) 83)), unchecked((char) unchecked((uint) 84))}));
    _r0.i = ((global::java.lang.String) _r4_o).equals((global::java.lang.Object) _r0_o) ? 1 : 0;
    if (_r0.i == 0) goto label53;
    _r0.i = _r1.i;
    goto label12;
    label53:;
    // Value=MDT
    _r0_o = new global::java.lang.String();
    ((global::java.lang.String)_r0_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)77)), unchecked((char) unchecked((uint) 68)), unchecked((char) unchecked((uint) 84))}));
    _r0.i = ((global::java.lang.String) _r4_o).equals((global::java.lang.Object) _r0_o) ? 1 : 0;
    if (_r0.i == 0) goto label63;
    _r0.i = _r2.i;
    goto label12;
    label63:;
    // Value=PST
    _r0_o = new global::java.lang.String();
    ((global::java.lang.String)_r0_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)80)), unchecked((char) unchecked((uint) 83)), unchecked((char) unchecked((uint) 84))}));
    _r0.i = ((global::java.lang.String) _r4_o).equals((global::java.lang.Object) _r0_o) ? 1 : 0;
    if (_r0.i == 0) goto label73;
    _r0.i = -8;
    goto label12;
    label73:;
    // Value=PDT
    _r0_o = new global::java.lang.String();
    ((global::java.lang.String)_r0_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)80)), unchecked((char) unchecked((uint) 68)), unchecked((char) unchecked((uint) 84))}));
    _r0.i = ((global::java.lang.String) _r4_o).equals((global::java.lang.Object) _r0_o) ? 1 : 0;
    if (_r0.i == 0) goto label83;
    _r0.i = _r1.i;
    goto label12;
    label83:;
    _r0.i = 0;
    goto label12;
//XMLVM_END_WRAPPER[java.util.Date: int zone(java.lang.String)]
}

private void writeObject(global::java.io.ObjectOutputStream n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void writeObject(java.io.ObjectOutputStream)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    _r2_o = this;
    _r3_o = n1;
    ((global::java.io.ObjectOutputStream) _r3_o).defaultWriteObject();
    _r0.l = ((global::java.util.Date) _r2_o).getTime();
    ((global::java.io.ObjectOutputStream) _r3_o).writeLong((long) _r0.l);
    return;
//XMLVM_END_WRAPPER[java.util.Date: void writeObject(java.io.ObjectOutputStream)]
}

private void readObject(global::java.io.ObjectInputStream n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: void readObject(java.io.ObjectInputStream)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    _r2_o = this;
    _r3_o = n1;
    ((global::java.io.ObjectInputStream) _r3_o).defaultReadObject();
    _r0.l = ((global::java.io.ObjectInputStream) _r3_o).readLong();
    ((global::java.util.Date) _r2_o).setTime((long) _r0.l);
    return;
//XMLVM_END_WRAPPER[java.util.Date: void readObject(java.io.ObjectInputStream)]
}

public virtual int compareTo(global::java.lang.Object n1){
//XMLVM_BEGIN_WRAPPER[java.util.Date: int compareTo(java.lang.Object)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    _r1_o = this;
    _r2_o = n1;
    _r0.i = ((global::java.util.Date) _r1_o).compareTo((global::java.util.Date) _r2_o);
    return _r0.i;
//XMLVM_END_WRAPPER[java.util.Date: int compareTo(java.lang.Object)]
}

//XMLVM_BEGIN_WRAPPER[java.util.Date]
//XMLVM_END_WRAPPER[java.util.Date]

} // end of class: Date

} // end of namespace: java.util
