// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.util {
public class MissingFormatArgumentException: global::java.util.IllegalFormatException {

private global::java.lang.String _fs;

new public void @this(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[java.util.MissingFormatArgumentException: void <init>(java.lang.String)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    _r1_o = this;
    _r2_o = n1;
    ((global::java.util.IllegalFormatException) _r1_o).@this();
    if (_r2_o != null) goto label11;
    _r0_o = new global::java.lang.NullPointerException();
    ((global::java.lang.NullPointerException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.NullPointerException) _r0_o);
    label11:;
    ((global::java.util.MissingFormatArgumentException) _r1_o)._fs = (global::java.lang.String) _r2_o;
    return;
//XMLVM_END_WRAPPER[java.util.MissingFormatArgumentException: void <init>(java.lang.String)]
}

public virtual global::System.Object getFormatSpecifier(){
//XMLVM_BEGIN_WRAPPER[java.util.MissingFormatArgumentException: java.lang.String getFormatSpecifier()]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    _r1_o = this;
    _r0_o = ((global::java.util.MissingFormatArgumentException) _r1_o)._fs;
    return (global::java.lang.String) _r0_o;
//XMLVM_END_WRAPPER[java.util.MissingFormatArgumentException: java.lang.String getFormatSpecifier()]
}

public override global::System.Object getMessage(){
//XMLVM_BEGIN_WRAPPER[java.util.MissingFormatArgumentException: java.lang.String getMessage()]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    _r2_o = this;
    // Value=luni.39
    _r0_o = new global::java.lang.String();
    ((global::java.lang.String)_r0_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)108)), unchecked((char) unchecked((uint) 117)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 46)), unchecked((char) unchecked((uint) 51)), unchecked((char) unchecked((uint) 57))}));
    _r1_o = ((global::java.util.MissingFormatArgumentException) _r2_o)._fs;
    _r0_o = global::org.apache.harmony.luni.@internal.nls.Messages.getString((global::java.lang.String) _r0_o, (global::java.lang.Object) _r1_o);
    return (global::java.lang.String) _r0_o;
//XMLVM_END_WRAPPER[java.util.MissingFormatArgumentException: java.lang.String getMessage()]
}

//XMLVM_BEGIN_WRAPPER[java.util.MissingFormatArgumentException]
//XMLVM_END_WRAPPER[java.util.MissingFormatArgumentException]

} // end of class: MissingFormatArgumentException

} // end of namespace: java.util
