// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.util {
public abstract class TreeMap_2DescendingSubMapIterator: global::java.util.TreeMap_2AbstractSubMapIterator {
new public void @this(global::java.util.TreeMap_2NavigableSubMap n1){
//XMLVM_BEGIN_WRAPPER[java.util.TreeMap$DescendingSubMapIterator: void <init>(java.util.TreeMap$NavigableSubMap)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    global::System.Object _r6_o = null;
    _r5_o = this;
    _r6_o = n1;
    _r4_o = null;
    ((global::java.util.TreeMap_2AbstractSubMapIterator) _r5_o).@this((global::java.util.TreeMap_2NavigableSubMap) _r6_o);
    _r0.i = ((global::java.util.TreeMap_2NavigableSubMap) _r6_o)._ffromStart ? 1 : 0;
    if (_r0.i == 0) goto label42;
    _r0.i = ((global::java.util.TreeMap_2NavigableSubMap) _r6_o)._floInclusive ? 1 : 0;
    if (_r0.i == 0) goto label33;
    _r0_o = ((global::java.util.TreeMap_2NavigableSubMap) _r6_o)._fm;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r6_o)._flo;
    _r0_o = ((global::java.util.TreeMap) _r0_o).findFloorEntry((global::java.lang.Object) _r1_o);
    label20:;
    if (_r0_o == null) goto label106;
    _r1_o = ((global::java.util.TreeMap_2Entry) _r0_o)._fkey;
    _r1.i = ((global::java.util.TreeMap_2NavigableSubMap) _r6_o).isInRange((global::java.lang.Object) _r1_o) ? 1 : 0;
    if (_r1.i != 0) goto label49;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fnode = (global::java.util.TreeMap_2Node) _r4_o;
    label32:;
    return;
    label33:;
    _r0_o = ((global::java.util.TreeMap_2NavigableSubMap) _r6_o)._fm;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r6_o)._flo;
    _r0_o = ((global::java.util.TreeMap) _r0_o).findLowerEntry((global::java.lang.Object) _r1_o);
    goto label20;
    label42:;
    _r0_o = ((global::java.util.TreeMap_2NavigableSubMap) _r6_o)._fm;
    _r0_o = ((global::java.util.TreeMap) _r0_o).findBiggestEntry();
    goto label20;
    label49:;
    _r1_o = ((global::java.util.TreeMap_2Entry) _r0_o)._fnode;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fnode = (global::java.util.TreeMap_2Node) _r1_o;
    _r1.i = ((global::java.util.TreeMap_2Entry) _r0_o)._findex;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._foffset = _r1.i;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o).getBoundaryNode();
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fboundaryPair = (global::java.util.TreeMap_2Entry) _r1_o;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fboundaryPair;
    if (_r1_o == null) goto label83;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r6_o)._fm;
    _r2_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fboundaryPair;
    _r2_o = ((global::java.util.TreeMap_2Entry) _r2_o)._fkey;
    _r3_o = ((global::java.util.TreeMap_2Entry) _r0_o)._fkey;
    _r1.i = ((global::java.util.TreeMap) _r1_o).keyCompare((global::java.lang.Object) _r2_o, (global::java.lang.Object) _r3_o);
    if (_r1.i <= 0) goto label83;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fnode = (global::java.util.TreeMap_2Node) _r4_o;
    label83:;
    _r1.i = ((global::java.util.TreeMap_2NavigableSubMap) _r6_o)._ftoEnd ? 1 : 0;
    if (_r1.i == 0) goto label32;
    _r1.i = ((global::java.util.TreeMap_2NavigableSubMap) _r6_o)._fhiInclusive ? 1 : 0;
    if (_r1.i != 0) goto label32;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r6_o)._fm;
    _r2_o = ((global::java.util.TreeMap_2NavigableSubMap) _r6_o)._fhi;
    _r0_o = ((global::java.util.TreeMap_2Entry) _r0_o)._fkey;
    _r0.i = ((global::java.util.TreeMap) _r1_o).keyCompare((global::java.lang.Object) _r2_o, (global::java.lang.Object) _r0_o);
    if (_r0.i != 0) goto label32;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fnode = (global::java.util.TreeMap_2Node) _r4_o;
    goto label32;
    label106:;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fnode = (global::java.util.TreeMap_2Node) _r4_o;
    goto label32;
//XMLVM_END_WRAPPER[java.util.TreeMap$DescendingSubMapIterator: void <init>(java.util.TreeMap$NavigableSubMap)]
}

public override global::System.Object getStartNode(){
//XMLVM_BEGIN_WRAPPER[java.util.TreeMap$DescendingSubMapIterator: java.util.TreeMap$Entry getStartNode()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    _r2_o = this;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r0.i = ((global::java.util.TreeMap_2NavigableSubMap) _r0_o)._ftoEnd ? 1 : 0;
    if (_r0.i == 0) goto label34;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r0.i = ((global::java.util.TreeMap_2NavigableSubMap) _r0_o)._fhiInclusive ? 1 : 0;
    if (_r0.i == 0) goto label23;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r1_o)._fhi;
    _r0_o = ((global::java.util.TreeMap_2NavigableSubMap) _r0_o).smallerOrEqualEntry((global::java.lang.Object) _r1_o);
    label22:;
    return (global::java.util.TreeMap_2Entry) _r0_o;
    label23:;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r1_o)._fhi;
    _r0_o = ((global::java.util.TreeMap_2NavigableSubMap) _r0_o).smallerEntry((global::java.lang.Object) _r1_o);
    goto label22;
    label34:;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r0_o = ((global::java.util.TreeMap_2NavigableSubMap) _r0_o).theBiggestEntry();
    goto label22;
//XMLVM_END_WRAPPER[java.util.TreeMap$DescendingSubMapIterator: java.util.TreeMap$Entry getStartNode()]
}

public override global::System.Object getBoundaryNode(){
//XMLVM_BEGIN_WRAPPER[java.util.TreeMap$DescendingSubMapIterator: java.util.TreeMap$Entry getBoundaryNode()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    _r2_o = this;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r0.i = ((global::java.util.TreeMap_2NavigableSubMap) _r0_o)._ftoEnd ? 1 : 0;
    if (_r0.i == 0) goto label38;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r0.i = ((global::java.util.TreeMap_2NavigableSubMap) _r0_o)._fhiInclusive ? 1 : 0;
    if (_r0.i == 0) goto label25;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r0_o = ((global::java.util.TreeMap_2NavigableSubMap) _r0_o)._fm;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r1_o)._fhi;
    _r0_o = ((global::java.util.TreeMap) _r0_o).findCeilingEntry((global::java.lang.Object) _r1_o);
    label24:;
    return (global::java.util.TreeMap_2Entry) _r0_o;
    label25:;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r0_o = ((global::java.util.TreeMap_2NavigableSubMap) _r0_o)._fm;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r1_o)._fhi;
    _r0_o = ((global::java.util.TreeMap) _r0_o).findHigherEntry((global::java.lang.Object) _r1_o);
    goto label24;
    label38:;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r0_o = ((global::java.util.TreeMap_2NavigableSubMap) _r0_o)._fm;
    _r0_o = ((global::java.util.TreeMap) _r0_o).findSmallestEntry();
    goto label24;
//XMLVM_END_WRAPPER[java.util.TreeMap$DescendingSubMapIterator: java.util.TreeMap$Entry getBoundaryNode()]
}

public virtual global::System.Object getNext(){
//XMLVM_BEGIN_WRAPPER[java.util.TreeMap$DescendingSubMapIterator: java.util.TreeMap$Entry getNext()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    _r2_o = this;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fnode;
    if (_r0_o != null) goto label10;
    _r0_o = new global::java.util.NoSuchElementException();
    ((global::java.util.NoSuchElementException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.util.NoSuchElementException) _r0_o);
    label10:;
    _r0.i = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fexpectedModCount;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fsubMap;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r1_o)._fm;
    _r1.i = ((global::java.util.TreeMap) _r1_o)._fmodCount;
    if (_r0.i == _r1.i) goto label26;
    _r0_o = new global::java.util.ConcurrentModificationException();
    ((global::java.util.ConcurrentModificationException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.util.ConcurrentModificationException) _r0_o);
    label26:;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fnode;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._flastNode = (global::java.util.TreeMap_2Node) _r0_o;
    _r0.i = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._foffset;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._flastOffset = _r0.i;
    _r0.i = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._foffset;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fnode;
    _r1.i = ((global::java.util.TreeMap_2Node) _r1_o)._fleft_1idx;
    if (_r0.i == _r1.i) goto label86;
    _r0.i = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._foffset;
    _r1.i = 1;
    _r0.i = _r0.i - _r1.i;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._foffset = _r0.i;
    label48:;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o).getBoundaryNode();
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fboundaryPair = (global::java.util.TreeMap_2Entry) _r0_o;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fboundaryPair;
    if (_r0_o == null) goto label77;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fboundaryPair;
    _r0_o = ((global::java.util.TreeMap_2Entry) _r0_o)._fnode;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._flastNode;
    if (_r0_o != _r1_o) goto label77;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fboundaryPair;
    _r0.i = ((global::java.util.TreeMap_2Entry) _r0_o)._findex;
    _r1.i = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._flastOffset;
    if (_r0.i != _r1.i) goto label77;
    _r0_o = null;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fnode = (global::java.util.TreeMap_2Node) _r0_o;
    label77:;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._flastNode;
    _r1.i = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._flastOffset;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o).createEntry((global::java.util.TreeMap_2Node) _r0_o, (int) _r1.i);
    return (global::java.util.TreeMap_2Entry) _r0_o;
    label86:;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fnode;
    _r0_o = ((global::java.util.TreeMap_2Node) _r0_o)._fprev;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fnode = (global::java.util.TreeMap_2Node) _r0_o;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fnode;
    if (_r0_o == null) goto label48;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._fnode;
    _r0.i = ((global::java.util.TreeMap_2Node) _r0_o)._fright_1idx;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r2_o)._foffset = _r0.i;
    goto label48;
//XMLVM_END_WRAPPER[java.util.TreeMap$DescendingSubMapIterator: java.util.TreeMap$Entry getNext()]
}

public override bool hasNext(){
//XMLVM_BEGIN_WRAPPER[java.util.TreeMap$DescendingSubMapIterator: boolean hasNext()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    _r1_o = this;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r1_o)._fnode;
    if (_r0_o == null) goto label6;
    _r0.i = 1;
    label5:;
    return _r0.i!=0;
    label6:;
    _r0.i = 0;
    goto label5;
//XMLVM_END_WRAPPER[java.util.TreeMap$DescendingSubMapIterator: boolean hasNext()]
}

public override void remove(){
//XMLVM_BEGIN_WRAPPER[java.util.TreeMap$DescendingSubMapIterator: void remove()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    _r5_o = this;
    _r4_o = null;
    _r0.i = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fexpectedModCount;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fsubMap;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r1_o)._fm;
    _r1.i = ((global::java.util.TreeMap) _r1_o)._fmodCount;
    if (_r0.i != _r1.i) goto label124;
    _r0.i = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fexpectedModCount;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fsubMap;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r1_o)._fm;
    _r1.i = ((global::java.util.TreeMap) _r1_o)._fmodCount;
    if (_r0.i != _r1.i) goto label86;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fnode;
    if (_r0_o == null) goto label87;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fnode;
    _r0_o = ((global::java.util.TreeMap_2Node) _r0_o)._fkeys;
    _r1.i = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._foffset;
    _r0_o = ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i];
    label33:;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._flastNode;
    if (_r1_o == null) goto label118;
    _r1.i = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._flastOffset;
    _r2_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._flastNode;
    _r2.i = ((global::java.util.TreeMap_2Node) _r2_o)._fleft_1idx;
    if (_r1.i != _r2.i) goto label89;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fsubMap;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r1_o)._fm;
    _r2_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._flastNode;
    ((global::java.util.TreeMap) _r1_o).removeLeftmost((global::java.util.TreeMap_2Node) _r2_o);
    label54:;
    if (_r0_o == null) goto label115;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fsubMap;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r1_o)._fm;
    _r0_o = ((global::java.util.TreeMap) _r1_o).find((global::java.lang.Object) _r0_o);
    _r1_o = ((global::java.util.TreeMap_2Entry) _r0_o)._fnode;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fnode = (global::java.util.TreeMap_2Node) _r1_o;
    _r0.i = ((global::java.util.TreeMap_2Entry) _r0_o)._findex;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._foffset = _r0.i;
    _r0_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o).getBoundaryNode();
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fboundaryPair = (global::java.util.TreeMap_2Entry) _r0_o;
    label78:;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._flastNode = (global::java.util.TreeMap_2Node) _r4_o;
    _r0.i = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fexpectedModCount;
    _r0.i = _r0.i + 1;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fexpectedModCount = _r0.i;
    label86:;
    return;
    label87:;
    _r0_o = _r4_o;
    goto label33;
    label89:;
    _r2_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._flastNode;
    _r2.i = ((global::java.util.TreeMap_2Node) _r2_o)._fright_1idx;
    if (_r1.i != _r2.i) goto label105;
    _r1_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fsubMap;
    _r1_o = ((global::java.util.TreeMap_2NavigableSubMap) _r1_o)._fm;
    _r2_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._flastNode;
    ((global::java.util.TreeMap) _r1_o).removeRightmost((global::java.util.TreeMap_2Node) _r2_o);
    goto label54;
    label105:;
    _r2_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fsubMap;
    _r2_o = ((global::java.util.TreeMap_2NavigableSubMap) _r2_o)._fm;
    _r3_o = ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._flastNode;
    ((global::java.util.TreeMap) _r2_o).removeMiddleElement((global::java.util.TreeMap_2Node) _r3_o, (int) _r1.i);
    goto label54;
    label115:;
    ((global::java.util.TreeMap_2DescendingSubMapIterator) _r5_o)._fnode = (global::java.util.TreeMap_2Node) _r4_o;
    goto label78;
    label118:;
    _r0_o = new global::java.lang.IllegalStateException();
    ((global::java.lang.IllegalStateException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalStateException) _r0_o);
    label124:;
    _r0_o = new global::java.util.ConcurrentModificationException();
    ((global::java.util.ConcurrentModificationException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.util.ConcurrentModificationException) _r0_o);
//XMLVM_END_WRAPPER[java.util.TreeMap$DescendingSubMapIterator: void remove()]
}

//XMLVM_BEGIN_WRAPPER[java.util.TreeMap$DescendingSubMapIterator]
//XMLVM_END_WRAPPER[java.util.TreeMap$DescendingSubMapIterator]

} // end of class: TreeMap_2DescendingSubMapIterator

} // end of namespace: java.util
