// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.util {
public class TreeMap_2UnboundedEntryIterator: global::java.util.TreeMap_2AbstractMapIterator,global::java.util.Iterator {
public void @this(global::java.util.TreeMap n1, global::java.util.TreeMap_2Node n2, int n3){
//XMLVM_BEGIN_WRAPPER[java.util.TreeMap$UnboundedEntryIterator: void <init>(java.util.TreeMap, java.util.TreeMap$Node, int)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    _r0_o = this;
    _r1_o = n1;
    _r2_o = n2;
    _r3.i = n3;
    ((global::java.util.TreeMap_2AbstractMapIterator) _r0_o).@this((global::java.util.TreeMap) _r1_o, (global::java.util.TreeMap_2Node) _r2_o, (int) _r3.i);
    return;
//XMLVM_END_WRAPPER[java.util.TreeMap$UnboundedEntryIterator: void <init>(java.util.TreeMap, java.util.TreeMap$Node, int)]
}

public void @this(global::java.util.TreeMap n1){
//XMLVM_BEGIN_WRAPPER[java.util.TreeMap$UnboundedEntryIterator: void <init>(java.util.TreeMap)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::java.util.TreeMap_2AbstractMapIterator) _r0_o).@this((global::java.util.TreeMap) _r1_o);
    return;
//XMLVM_END_WRAPPER[java.util.TreeMap$UnboundedEntryIterator: void <init>(java.util.TreeMap)]
}

public virtual global::System.Object next(){
//XMLVM_BEGIN_WRAPPER[java.util.TreeMap$UnboundedEntryIterator: java.util.Map$Entry next()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    _r5_o = this;
    ((global::java.util.TreeMap_2UnboundedEntryIterator) _r5_o).makeNext();
    _r0.i = ((global::java.util.TreeMap_2UnboundedEntryIterator) _r5_o)._flastOffset;
    _r1_o = new global::java.util.TreeMap_2TreeMapEntry();
    _r2_o = ((global::java.util.TreeMap_2UnboundedEntryIterator) _r5_o)._flastNode;
    _r2_o = ((global::java.util.TreeMap_2Node) _r2_o)._fkeys;
    _r2_o = ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r2_o)[_r0.i];
    _r3_o = ((global::java.util.TreeMap_2UnboundedEntryIterator) _r5_o)._flastNode;
    _r3_o = ((global::java.util.TreeMap_2Node) _r3_o)._fvalues;
    _r3_o = ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r3_o)[_r0.i];
    _r4_o = ((global::java.util.TreeMap_2UnboundedEntryIterator) _r5_o)._flastNode;
    ((global::java.util.TreeMap_2TreeMapEntry) _r1_o).@this((global::java.lang.Object) _r2_o, (global::java.lang.Object) _r3_o, (global::java.util.TreeMap_2Node) _r4_o, (int) _r0.i);
    return (global::java.util.Map_2Entry) _r1_o;
//XMLVM_END_WRAPPER[java.util.TreeMap$UnboundedEntryIterator: java.util.Map$Entry next()]
}

//XMLVM_BEGIN_WRAPPER[java.util.TreeMap$UnboundedEntryIterator]
//XMLVM_END_WRAPPER[java.util.TreeMap$UnboundedEntryIterator]

} // end of class: TreeMap_2UnboundedEntryIterator

} // end of namespace: java.util
