// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.nio {
public abstract class CharArrayBuffer: global::java.nio.CharBuffer {
public global::org.xmlvm._nArrayAdapter<char> _fbackingArray;

public int _foffset;

public void @this(global::org.xmlvm._nArrayAdapter<char> n1){
//XMLVM_BEGIN_WRAPPER[java.nio.CharArrayBuffer: void <init>(char[])]
    global::org.xmlvm._nElement _r0;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    _r2_o = this;
    _r3_o = n1;
    _r0.i = ((global::org.xmlvm._nIArray) _r3_o).Length;
    _r1.i = 0;
    ((global::java.nio.CharArrayBuffer) _r2_o).@this((int) _r0.i, (global::org.xmlvm._nArrayAdapter<char>) _r3_o, (int) _r1.i);
    return;
//XMLVM_END_WRAPPER[java.nio.CharArrayBuffer: void <init>(char[])]
}

public void @this(int n1){
//XMLVM_BEGIN_WRAPPER[java.nio.CharArrayBuffer: void <init>(int)]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    _r2_o = this;
    _r3.i = n1;
    _r0_o = new global::org.xmlvm._nArrayAdapter<char>(new char[_r3.i]);
    _r1.i = 0;
    ((global::java.nio.CharArrayBuffer) _r2_o).@this((int) _r3.i, (global::org.xmlvm._nArrayAdapter<char>) _r0_o, (int) _r1.i);
    return;
//XMLVM_END_WRAPPER[java.nio.CharArrayBuffer: void <init>(int)]
}

public void @this(int n1, global::org.xmlvm._nArrayAdapter<char> n2, int n3){
//XMLVM_BEGIN_WRAPPER[java.nio.CharArrayBuffer: void <init>(int, char[], int)]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    _r0_o = this;
    _r1.i = n1;
    _r2_o = n2;
    _r3.i = n3;
    ((global::java.nio.CharBuffer) _r0_o).@this((int) _r1.i);
    ((global::java.nio.CharArrayBuffer) _r0_o)._fbackingArray = (global::org.xmlvm._nArrayAdapter<char>) _r2_o;
    ((global::java.nio.CharArrayBuffer) _r0_o)._foffset = _r3.i;
    return;
//XMLVM_END_WRAPPER[java.nio.CharArrayBuffer: void <init>(int, char[], int)]
}

public override char get(){
//XMLVM_BEGIN_WRAPPER[java.nio.CharArrayBuffer: char get()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r4_o = null;
    _r4_o = this;
    _r0.i = ((global::java.nio.CharArrayBuffer) _r4_o)._fposition;
    _r1.i = ((global::java.nio.CharArrayBuffer) _r4_o)._flimit;
    if (_r0.i != _r1.i) goto label12;
    _r0_o = new global::java.nio.BufferUnderflowException();
    ((global::java.nio.BufferUnderflowException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.nio.BufferUnderflowException) _r0_o);
    label12:;
    _r0_o = ((global::java.nio.CharArrayBuffer) _r4_o)._fbackingArray;
    _r1.i = ((global::java.nio.CharArrayBuffer) _r4_o)._foffset;
    _r2.i = ((global::java.nio.CharArrayBuffer) _r4_o)._fposition;
    _r3.i = _r2.i + 1;
    ((global::java.nio.CharArrayBuffer) _r4_o)._fposition = _r3.i;
    _r1.i = _r1.i + _r2.i;
    _r0.i = ((global::org.xmlvm._nArrayAdapter<char>) _r0_o)[_r1.i];
    return (char) _r0.i;
//XMLVM_END_WRAPPER[java.nio.CharArrayBuffer: char get()]
}

public override char get(int n1){
//XMLVM_BEGIN_WRAPPER[java.nio.CharArrayBuffer: char get(int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    _r2_o = this;
    _r3.i = n1;
    if (_r3.i < 0) goto label6;
    _r0.i = ((global::java.nio.CharArrayBuffer) _r2_o)._flimit;
    if (_r3.i < _r0.i) goto label12;
    label6:;
    _r0_o = new global::java.lang.IndexOutOfBoundsException();
    ((global::java.lang.IndexOutOfBoundsException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IndexOutOfBoundsException) _r0_o);
    label12:;
    _r0_o = ((global::java.nio.CharArrayBuffer) _r2_o)._fbackingArray;
    _r1.i = ((global::java.nio.CharArrayBuffer) _r2_o)._foffset;
    _r1.i = _r1.i + _r3.i;
    _r0.i = ((global::org.xmlvm._nArrayAdapter<char>) _r0_o)[_r1.i];
    return (char) _r0.i;
//XMLVM_END_WRAPPER[java.nio.CharArrayBuffer: char get(int)]
}

public override global::System.Object get(global::org.xmlvm._nArrayAdapter<char> n1, int n2, int n3){
//XMLVM_BEGIN_WRAPPER[java.nio.CharArrayBuffer: java.nio.CharBuffer get(char[], int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r5_o = null;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::org.xmlvm._nElement _r8;
    _r5_o = this;
    _r6_o = n1;
    _r7.i = n2;
    _r8.i = n3;
    _r0.i = ((global::org.xmlvm._nIArray) _r6_o).Length;
    if (_r7.i < 0) goto label13;
    if (_r8.i < 0) goto label13;
    _r1.l = (long) _r7.i;
    _r3.l = (long) _r8.i;
    _r1.l = _r1.l + _r3.l;
    _r3.l = (long) _r0.i;
    _r0.i = _r1.l > _r3.l ? 1 : (_r1.l == _r3.l ? 0 : -1);
    if (_r0.i <= 0) goto label19;
    label13:;
    _r0_o = new global::java.lang.IndexOutOfBoundsException();
    ((global::java.lang.IndexOutOfBoundsException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IndexOutOfBoundsException) _r0_o);
    label19:;
    _r0.i = ((global::java.nio.CharArrayBuffer) _r5_o).remaining();
    if (_r8.i <= _r0.i) goto label31;
    _r0_o = new global::java.nio.BufferUnderflowException();
    ((global::java.nio.BufferUnderflowException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.nio.BufferUnderflowException) _r0_o);
    label31:;
    _r0_o = ((global::java.nio.CharArrayBuffer) _r5_o)._fbackingArray;
    _r1.i = ((global::java.nio.CharArrayBuffer) _r5_o)._foffset;
    _r2.i = ((global::java.nio.CharArrayBuffer) _r5_o)._fposition;
    _r1.i = _r1.i + _r2.i;
    global::java.lang.System.arraycopy((global::java.lang.Object) _r0_o, (int) _r1.i, (global::java.lang.Object) _r6_o, (int) _r7.i, (int) _r8.i);
    _r0.i = ((global::java.nio.CharArrayBuffer) _r5_o)._fposition;
    _r0.i = _r0.i + _r8.i;
    ((global::java.nio.CharArrayBuffer) _r5_o)._fposition = _r0.i;
    return (global::java.nio.CharBuffer) _r5_o;
//XMLVM_END_WRAPPER[java.nio.CharArrayBuffer: java.nio.CharBuffer get(char[], int, int)]
}

public override bool isDirect(){
//XMLVM_BEGIN_WRAPPER[java.nio.CharArrayBuffer: boolean isDirect()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r1_o = null;
    _r1_o = this;
    _r0.i = 0;
    return _r0.i!=0;
//XMLVM_END_WRAPPER[java.nio.CharArrayBuffer: boolean isDirect()]
}

public override global::System.Object order(){
//XMLVM_BEGIN_WRAPPER[java.nio.CharArrayBuffer: java.nio.ByteOrder order()]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    _r1_o = this;
    _r0_o = global::java.nio.ByteOrder.nativeOrder();
    return (global::java.nio.ByteOrder) _r0_o;
//XMLVM_END_WRAPPER[java.nio.CharArrayBuffer: java.nio.ByteOrder order()]
}

public override global::System.Object subSequence(int n1, int n2){
//XMLVM_BEGIN_WRAPPER[java.nio.CharArrayBuffer: java.lang.CharSequence subSequence(int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::org.xmlvm._nElement _r4;
    _r2_o = this;
    _r3.i = n1;
    _r4.i = n2;
    if (_r3.i < 0) goto label10;
    if (_r4.i < _r3.i) goto label10;
    _r0.i = ((global::java.nio.CharArrayBuffer) _r2_o).remaining();
    if (_r4.i <= _r0.i) goto label16;
    label10:;
    _r0_o = new global::java.lang.IndexOutOfBoundsException();
    ((global::java.lang.IndexOutOfBoundsException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IndexOutOfBoundsException) _r0_o);
    label16:;
    _r0_o = ((global::java.nio.CharArrayBuffer) _r2_o).duplicate();
    _r1.i = ((global::java.nio.CharArrayBuffer) _r2_o)._fposition;
    _r1.i = _r1.i + _r4.i;
    ((global::java.nio.CharBuffer) _r0_o).limit((int) _r1.i);
    _r1.i = ((global::java.nio.CharArrayBuffer) _r2_o)._fposition;
    _r1.i = _r1.i + _r3.i;
    ((global::java.nio.CharBuffer) _r0_o).position((int) _r1.i);
    return (global::java.lang.CharSequence) _r0_o;
//XMLVM_END_WRAPPER[java.nio.CharArrayBuffer: java.lang.CharSequence subSequence(int, int)]
}

public override global::System.Object toString(){
//XMLVM_BEGIN_WRAPPER[java.nio.CharArrayBuffer: java.lang.String toString()]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r3_o = null;
    _r3_o = this;
    _r0_o = ((global::java.nio.CharArrayBuffer) _r3_o)._fbackingArray;
    _r1.i = ((global::java.nio.CharArrayBuffer) _r3_o)._foffset;
    _r2.i = ((global::java.nio.CharArrayBuffer) _r3_o)._fposition;
    _r1.i = _r1.i + _r2.i;
    _r2.i = ((global::java.nio.CharArrayBuffer) _r3_o).remaining();
    _r0_o = global::java.lang.String.copyValueOf((global::org.xmlvm._nArrayAdapter<char>) _r0_o, (int) _r1.i, (int) _r2.i);
    return (global::java.lang.String) _r0_o;
//XMLVM_END_WRAPPER[java.nio.CharArrayBuffer: java.lang.String toString()]
}

//XMLVM_BEGIN_WRAPPER[java.nio.CharArrayBuffer]
//XMLVM_END_WRAPPER[java.nio.CharArrayBuffer]

} // end of class: CharArrayBuffer

} // end of namespace: java.nio
