// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace org.w3c.dom.xpath {
public abstract class _iXPathEvaluator {

} // end of abstract class: _iXPathEvaluator

public interface XPathEvaluator {
 global::System.Object createExpression(global::java.lang.String n1, global::org.w3c.dom.xpath.XPathNSResolver n2);

 global::System.Object createNSResolver(global::org.w3c.dom.Node n1);

 global::System.Object evaluate(global::java.lang.String n1, global::org.w3c.dom.Node n2, global::org.w3c.dom.xpath.XPathNSResolver n3, short n4, global::java.lang.Object n5);

//XMLVM_BEGIN_WRAPPER[org.w3c.dom.xpath.XPathEvaluator]
//XMLVM_END_WRAPPER[org.w3c.dom.xpath.XPathEvaluator]

} // end of interface: XPathEvaluator

} // end of namespace: org.w3c.dom.xpath
