// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace com.codename1.charts.models {
public class SeriesSelection: global::java.lang.Object {
private int _fmSeriesIndex;

private int _fmPointIndex;

private double _fmXValue;

private double _fmValue;

public void @this(int n1, int n2, double n3, double n4){
//XMLVM_BEGIN_WRAPPER[com.codename1.charts.models.SeriesSelection: void <init>(int, int, double, double)]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    global::org.xmlvm._nElement _r3;
    global::org.xmlvm._nElement _r5;
    _r0_o = this;
    _r1.i = n1;
    _r2.i = n2;
    _r3.d = n3;
    _r5.d = n4;
    ((global::java.lang.Object) _r0_o).@this();
    ((global::com.codename1.charts.models.SeriesSelection) _r0_o)._fmSeriesIndex = _r1.i;
    ((global::com.codename1.charts.models.SeriesSelection) _r0_o)._fmPointIndex = _r2.i;
    ((global::com.codename1.charts.models.SeriesSelection) _r0_o)._fmXValue = _r3.d;
    ((global::com.codename1.charts.models.SeriesSelection) _r0_o)._fmValue = _r5.d;
    return;
//XMLVM_END_WRAPPER[com.codename1.charts.models.SeriesSelection: void <init>(int, int, double, double)]
}

public virtual int getSeriesIndex(){
//XMLVM_BEGIN_WRAPPER[com.codename1.charts.models.SeriesSelection: int getSeriesIndex()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r1_o = null;
    _r1_o = this;
    _r0.i = ((global::com.codename1.charts.models.SeriesSelection) _r1_o)._fmSeriesIndex;
    return _r0.i;
//XMLVM_END_WRAPPER[com.codename1.charts.models.SeriesSelection: int getSeriesIndex()]
}

public virtual int getPointIndex(){
//XMLVM_BEGIN_WRAPPER[com.codename1.charts.models.SeriesSelection: int getPointIndex()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r1_o = null;
    _r1_o = this;
    _r0.i = ((global::com.codename1.charts.models.SeriesSelection) _r1_o)._fmPointIndex;
    return _r0.i;
//XMLVM_END_WRAPPER[com.codename1.charts.models.SeriesSelection: int getPointIndex()]
}

public virtual double getXValue(){
//XMLVM_BEGIN_WRAPPER[com.codename1.charts.models.SeriesSelection: double getXValue()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r2_o = null;
    _r2_o = this;
    _r0.d = ((global::com.codename1.charts.models.SeriesSelection) _r2_o)._fmXValue;
    return _r0.d;
//XMLVM_END_WRAPPER[com.codename1.charts.models.SeriesSelection: double getXValue()]
}

public virtual double getValue(){
//XMLVM_BEGIN_WRAPPER[com.codename1.charts.models.SeriesSelection: double getValue()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r2_o = null;
    _r2_o = this;
    _r0.d = ((global::com.codename1.charts.models.SeriesSelection) _r2_o)._fmValue;
    return _r0.d;
//XMLVM_END_WRAPPER[com.codename1.charts.models.SeriesSelection: double getValue()]
}

//XMLVM_BEGIN_WRAPPER[com.codename1.charts.models.SeriesSelection]
//XMLVM_END_WRAPPER[com.codename1.charts.models.SeriesSelection]

} // end of class: SeriesSelection

} // end of namespace: com.codename1.charts.models
