// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace com.codename1.ui.layouts {
public class GroupLayout_2SpringDelta: global::java.lang.Object {
public int _findex;

public int _fdelta;

public void @this(int n1, int n2){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.layouts.GroupLayout$SpringDelta: void <init>(int, int)]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    _r0_o = this;
    _r1.i = n1;
    _r2.i = n2;
    ((global::java.lang.Object) _r0_o).@this();
    ((global::com.codename1.ui.layouts.GroupLayout_2SpringDelta) _r0_o)._findex = _r1.i;
    ((global::com.codename1.ui.layouts.GroupLayout_2SpringDelta) _r0_o)._fdelta = _r2.i;
    return;
//XMLVM_END_WRAPPER[com.codename1.ui.layouts.GroupLayout$SpringDelta: void <init>(int, int)]
}

public virtual int compareTo(global::java.lang.Object n1){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.layouts.GroupLayout$SpringDelta: int compareTo(java.lang.Object)]
    global::org.xmlvm._nElement _r0;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    _r2_o = this;
    _r3_o = n1;
    _r0.i = ((global::com.codename1.ui.layouts.GroupLayout_2SpringDelta) _r2_o)._fdelta;
    _r1.i = ((global::com.codename1.ui.layouts.GroupLayout_2SpringDelta) _r3_o)._fdelta;
    _r0.i = _r0.i - _r1.i;
    return _r0.i;
//XMLVM_END_WRAPPER[com.codename1.ui.layouts.GroupLayout$SpringDelta: int compareTo(java.lang.Object)]
}

public override global::System.Object toString(){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.layouts.GroupLayout$SpringDelta: java.lang.String toString()]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    _r2_o = this;
    _r0_o = new global::java.lang.StringBuilder();
    ((global::java.lang.StringBuilder) _r0_o).@this();
    _r1_o = base.toString();
    _r0_o = ((global::java.lang.StringBuilder) _r0_o).append((global::java.lang.String) _r1_o);
    // Value=[index=
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)91)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 100)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 120)), unchecked((char) unchecked((uint) 61))}));
    _r0_o = ((global::java.lang.StringBuilder) _r0_o).append((global::java.lang.String) _r1_o);
    _r1.i = ((global::com.codename1.ui.layouts.GroupLayout_2SpringDelta) _r2_o)._findex;
    _r0_o = ((global::java.lang.StringBuilder) _r0_o).append((int) _r1.i);
    // Value=, delta=
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)44)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 100)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 61))}));
    _r0_o = ((global::java.lang.StringBuilder) _r0_o).append((global::java.lang.String) _r1_o);
    _r1.i = ((global::com.codename1.ui.layouts.GroupLayout_2SpringDelta) _r2_o)._fdelta;
    _r0_o = ((global::java.lang.StringBuilder) _r0_o).append((int) _r1.i);
    // Value=]
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)93))}));
    _r0_o = ((global::java.lang.StringBuilder) _r0_o).append((global::java.lang.String) _r1_o);
    _r0_o = ((global::java.lang.StringBuilder) _r0_o).toString();
    return (global::java.lang.String) _r0_o;
//XMLVM_END_WRAPPER[com.codename1.ui.layouts.GroupLayout$SpringDelta: java.lang.String toString()]
}

//XMLVM_BEGIN_WRAPPER[com.codename1.ui.layouts.GroupLayout$SpringDelta]
//XMLVM_END_WRAPPER[com.codename1.ui.layouts.GroupLayout$SpringDelta]

} // end of class: GroupLayout_2SpringDelta

} // end of namespace: com.codename1.ui.layouts
