// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace gnu.xml.xpath {
public abstract class Pattern: global::gnu.xml.xpath.Expr {
public void @this(){
//XMLVM_BEGIN_WRAPPER[gnu.xml.xpath.Pattern: void <init>()]
    global::System.Object _r0_o = null;
    _r0_o = this;
    ((global::gnu.xml.xpath.Expr) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[gnu.xml.xpath.Pattern: void <init>()]
}

public abstract bool matches(global::org.w3c.dom.Node n1);

//XMLVM_BEGIN_WRAPPER[gnu.xml.xpath.Pattern]
//XMLVM_END_WRAPPER[gnu.xml.xpath.Pattern]

} // end of class: Pattern

} // end of namespace: gnu.xml.xpath
