// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace javax.xml.xpath {
public abstract class _iXPathFunctionResolver {

} // end of abstract class: _iXPathFunctionResolver

public interface XPathFunctionResolver {
 global::System.Object resolveFunction(global::javax.xml.@namespace.QName n1, int n2);

//XMLVM_BEGIN_WRAPPER[javax.xml.xpath.XPathFunctionResolver]
//XMLVM_END_WRAPPER[javax.xml.xpath.XPathFunctionResolver]

} // end of interface: XPathFunctionResolver

} // end of namespace: javax.xml.xpath
