// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.io {
public abstract class _iObjectInput {

} // end of abstract class: _iObjectInput

public interface ObjectInput: global::java.io.DataInput {
 int available();

 void close();

 int read();

 int read(global::org.xmlvm._nArrayAdapter<sbyte> n1);

 int read(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2, int n3);

 global::System.Object readObject();

 long skip(long n1);

new  bool readBoolean();

new  sbyte readByte();

new  char readChar();

new  double readDouble();

new  float readFloat();

new  void readFully(global::org.xmlvm._nArrayAdapter<sbyte> n1);

new  void readFully(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2, int n3);

new  int readInt();

new  global::System.Object readLine();

new  long readLong();

new  short readShort();

new  global::System.Object readUTF();

new  int readUnsignedByte();

new  int readUnsignedShort();

new  int skipBytes(int n1);

//XMLVM_BEGIN_WRAPPER[java.io.ObjectInput]
//XMLVM_END_WRAPPER[java.io.ObjectInput]

} // end of interface: ObjectInput

} // end of namespace: java.io
