// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace com.codename1.maps.providers {
public abstract class MapProvider: global::java.lang.Object {
private global::com.codename1.maps.Projection _f_1projection;

private global::com.codename1.ui.geom.Dimension _f_1tileSize;

public void @this(global::com.codename1.maps.Projection n1, global::com.codename1.ui.geom.Dimension n2){
//XMLVM_BEGIN_WRAPPER[com.codename1.maps.providers.MapProvider: void <init>(com.codename1.maps.Projection, com.codename1.ui.geom.Dimension)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    _r2_o = n2;
    ((global::java.lang.Object) _r0_o).@this();
    ((global::com.codename1.maps.providers.MapProvider) _r0_o)._f_1projection = (global::com.codename1.maps.Projection) _r1_o;
    ((global::com.codename1.maps.providers.MapProvider) _r0_o)._f_1tileSize = (global::com.codename1.ui.geom.Dimension) _r2_o;
    return;
//XMLVM_END_WRAPPER[com.codename1.maps.providers.MapProvider: void <init>(com.codename1.maps.Projection, com.codename1.ui.geom.Dimension)]
}

public virtual void tileSize(global::com.codename1.ui.geom.Dimension n1){
//XMLVM_BEGIN_WRAPPER[com.codename1.maps.providers.MapProvider: void tileSize(com.codename1.ui.geom.Dimension)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    return;
//XMLVM_END_WRAPPER[com.codename1.maps.providers.MapProvider: void tileSize(com.codename1.ui.geom.Dimension)]
}

public abstract global::System.Object bboxFor(global::com.codename1.maps.Coord n1, int n2);

public abstract global::System.Object tileFor(global::com.codename1.maps.BoundingBox n1);

public abstract int maxZoomLevel();

public virtual int minZoomLevel(){
//XMLVM_BEGIN_WRAPPER[com.codename1.maps.providers.MapProvider: int minZoomLevel()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0.i = 0;
    return _r0.i;
//XMLVM_END_WRAPPER[com.codename1.maps.providers.MapProvider: int minZoomLevel()]
}

public abstract global::System.Object scale(int n1);

public virtual global::System.Object translate(global::com.codename1.maps.Coord n1, int n2, int n3, int n4){
//XMLVM_BEGIN_WRAPPER[com.codename1.maps.providers.MapProvider: com.codename1.maps.Coord translate(com.codename1.maps.Coord, int, int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::System.Object _r8_o = null;
    global::org.xmlvm._nElement _r9;
    global::System.Object _r9_o = null;
    global::org.xmlvm._nElement _r10;
    global::System.Object _r10_o = null;
    global::org.xmlvm._nElement _r11;
    global::System.Object _r11_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r7_o = this;
    _r8_o = n1;
    _r9.i = n2;
    _r10.i = n3;
    _r11.i = n4;
    _r0_o = ((global::com.codename1.maps.providers.MapProvider) _r7_o).scale((int) _r9.i);
    _r1.d = (double) _r11.i;
    _r3.d = ((global::com.codename1.maps.Coord) _r0_o).getLatitude();
    _r1.d = _r1.d * _r3.d;
    _r3.d = (double) _r10.i;
    _r5.d = ((global::com.codename1.maps.Coord) _r0_o).getLongitude();
    _r3.d = _r3.d * _r5.d;
    _r1_o = ((global::com.codename1.maps.Coord) _r8_o).translate((double) _r1.d, (double) _r3.d);
    return (global::com.codename1.maps.Coord) _r1_o;
//XMLVM_END_WRAPPER[com.codename1.maps.providers.MapProvider: com.codename1.maps.Coord translate(com.codename1.maps.Coord, int, int, int)]
}

public virtual global::System.Object projection(){
//XMLVM_BEGIN_WRAPPER[com.codename1.maps.providers.MapProvider: com.codename1.maps.Projection projection()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0_o = ((global::com.codename1.maps.providers.MapProvider) _r1_o)._f_1projection;
    return (global::com.codename1.maps.Projection) _r0_o;
//XMLVM_END_WRAPPER[com.codename1.maps.providers.MapProvider: com.codename1.maps.Projection projection()]
}

public virtual global::System.Object tileSize(){
//XMLVM_BEGIN_WRAPPER[com.codename1.maps.providers.MapProvider: com.codename1.ui.geom.Dimension tileSize()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0_o = ((global::com.codename1.maps.providers.MapProvider) _r1_o)._f_1tileSize;
    return (global::com.codename1.ui.geom.Dimension) _r0_o;
//XMLVM_END_WRAPPER[com.codename1.maps.providers.MapProvider: com.codename1.ui.geom.Dimension tileSize()]
}

public abstract global::System.Object attribution();

public virtual int maxZoomFor(global::com.codename1.maps.Tile n1){
//XMLVM_BEGIN_WRAPPER[com.codename1.maps.providers.MapProvider: int maxZoomFor(com.codename1.maps.Tile)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::System.Object _r8_o = null;
    global::org.xmlvm._nElement _r9;
    global::System.Object _r9_o = null;
    global::org.xmlvm._nElement _r10;
    global::System.Object _r10_o = null;
    global::org.xmlvm._nElement _r11;
    global::System.Object _r11_o = null;
    global::org.xmlvm._nElement _r12;
    global::System.Object _r12_o = null;
    global::org.xmlvm._nElement _r13;
    global::System.Object _r13_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r12_o = this;
    _r13_o = n1;
    _r8_o = ((global::com.codename1.maps.Tile) _r13_o).dimension();
    _r0.i = ((global::com.codename1.ui.geom.Dimension) _r8_o).getHeight();
    _r8_o = ((global::com.codename1.maps.Tile) _r13_o).dimension();
    _r6.i = ((global::com.codename1.ui.geom.Dimension) _r8_o).getWidth();
    _r8_o = ((global::com.codename1.maps.Tile) _r13_o).getBoundingBox();
    _r1.d = ((global::com.codename1.maps.BoundingBox) _r8_o).latitudeDifference();
    _r8_o = ((global::com.codename1.maps.Tile) _r13_o).getBoundingBox();
    _r3.d = ((global::com.codename1.maps.BoundingBox) _r8_o).longitudeDifference();
    _r7.i = ((global::com.codename1.maps.providers.MapProvider) _r12_o).maxZoomLevel();
    label36:;
    if (_r7.i <= 0) goto label62;
    _r5_o = ((global::com.codename1.maps.providers.MapProvider) _r12_o).scale((int) _r7.i);
    _r8.d = ((global::com.codename1.maps.Coord) _r5_o).getLatitude();
    _r10.d = (double) _r0.i;
    _r8.d = _r8.d * _r10.d;
    _r8.i = _r8.d > _r1.d ? 1 : (_r8.d == _r1.d ? 0 : -1);
    if (_r8.i <= 0) goto label63;
    _r8.d = ((global::com.codename1.maps.Coord) _r5_o).getLongitude();
    _r10.d = (double) _r6.i;
    _r8.d = _r8.d * _r10.d;
    _r8.i = _r8.d > _r3.d ? 1 : (_r8.d == _r3.d ? 0 : -1);
    if (_r8.i <= 0) goto label63;
    label62:;
    return _r7.i;
    label63:;
    _r7.i = _r7.i + -1;
    goto label36;
//XMLVM_END_WRAPPER[com.codename1.maps.providers.MapProvider: int maxZoomFor(com.codename1.maps.Tile)]
}

//XMLVM_BEGIN_WRAPPER[com.codename1.maps.providers.MapProvider]
//XMLVM_END_WRAPPER[com.codename1.maps.providers.MapProvider]

} // end of class: MapProvider

} // end of namespace: com.codename1.maps.providers
