// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace org.bouncycastle.crypto {
public abstract class _iExtendedDigest {

} // end of abstract class: _iExtendedDigest

public interface ExtendedDigest: global::org.bouncycastle.crypto.Digest {
 int getByteLength();

new  int doFinal(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2);

new  global::System.Object getAlgorithmName();

new  int getDigestSize();

new  void reset();

new  void update(sbyte n1);

new  void update(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2, int n3);

//XMLVM_BEGIN_WRAPPER[org.bouncycastle.crypto.ExtendedDigest]
//XMLVM_END_WRAPPER[org.bouncycastle.crypto.ExtendedDigest]

} // end of interface: ExtendedDigest

} // end of namespace: org.bouncycastle.crypto
