// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace gnu.xml.dom.ls {
public class DomLSInput: global::java.lang.Object,global::org.w3c.dom.ls.LSInput {
private global::java.io.InputStream _fin;

private global::java.lang.String _fsystemId;

private global::java.lang.String _fpublicId;

private global::java.lang.String _fbaseURI;

private global::java.lang.String _fencoding;

private bool _fcertifiedText;

public void @this(){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: void <init>()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    ((global::java.lang.Object) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: void <init>()]
}

public virtual global::System.Object getCharacterStream(){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.io.Reader getCharacterStream()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r2_o = this;
    _r0_o = new global::java.io.InputStreamReader();
    _r1_o = ((global::gnu.xml.dom.ls.DomLSInput) _r2_o)._fin;
    ((global::java.io.InputStreamReader) _r0_o).@this((global::java.io.InputStream) _r1_o);
    return (global::java.io.Reader) _r0_o;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.io.Reader getCharacterStream()]
}

public virtual void setCharacterStream(global::java.io.Reader n1){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setCharacterStream(java.io.Reader)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r2_o = n1;
    _r0_o = new global::gnu.xml.dom.ls.ReaderInputStream();
    ((global::gnu.xml.dom.ls.ReaderInputStream) _r0_o).@this((global::java.io.Reader) _r2_o);
    ((global::gnu.xml.dom.ls.DomLSInput) _r1_o)._fin = (global::java.io.InputStream) _r0_o;
    return;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setCharacterStream(java.io.Reader)]
}

public virtual global::System.Object getByteStream(){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.io.InputStream getByteStream()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0_o = ((global::gnu.xml.dom.ls.DomLSInput) _r1_o)._fin;
    return (global::java.io.InputStream) _r0_o;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.io.InputStream getByteStream()]
}

public virtual void setByteStream(global::java.io.InputStream n1){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setByteStream(java.io.InputStream)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::gnu.xml.dom.ls.DomLSInput) _r0_o)._fin = (global::java.io.InputStream) _r1_o;
    return;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setByteStream(java.io.InputStream)]
}

public virtual global::System.Object getStringData(){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.lang.String getStringData()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r5_o = this;
    _r0_o = new global::gnu.java.lang.CPStringBuilder();
    ((global::gnu.java.lang.CPStringBuilder) _r0_o).@this();
    _r1_o = ((global::gnu.xml.dom.ls.DomLSInput) _r5_o).getCharacterStream();
    _r2.i = 4096;
    try {
    _r2_o = new global::org.xmlvm._nArrayAdapter<char>(new char[_r2.i]);
    _r3.i = ((global::java.io.Reader) _r1_o).read((global::org.xmlvm._nArrayAdapter<char>) _r2_o);
    }
    catch (global::System.Exception e) {
 global::org.xmlvm._nExceptionAdapter ex = e as global::org.xmlvm._nExceptionAdapter ?? new global::org.xmlvm._nExceptionAdapter(e.ToString(), e.ToJavaException());
        global::System.Object _java_exception = ex.getJavaException();
        if (_java_exception is global::java.io.IOException) {
            _ex = ex;
            goto label34;
        }
        throw ex;
    } // end catch
    label17:;
    _r4.i = -1;
    if (_r3.i != _r4.i) goto label25;
    _r0_o = ((global::gnu.java.lang.CPStringBuilder) _r0_o).toString();
    label24:;
    return (global::java.lang.String) _r0_o;
    label25:;
    _r4.i = 0;
    try {
    ((global::gnu.java.lang.CPStringBuilder) _r0_o).append((global::org.xmlvm._nArrayAdapter<char>) _r2_o, (int) _r4.i, (int) _r3.i);
    _r3.i = ((global::java.io.Reader) _r1_o).read((global::org.xmlvm._nArrayAdapter<char>) _r2_o);
    }
    catch (global::System.Exception e) {
 global::org.xmlvm._nExceptionAdapter ex = e as global::org.xmlvm._nExceptionAdapter ?? new global::org.xmlvm._nExceptionAdapter(e.ToString(), e.ToJavaException());
        global::System.Object _java_exception = ex.getJavaException();
        if (_java_exception is global::java.io.IOException) {
            _ex = ex;
            goto label34;
        }
        throw ex;
    } // end catch
    goto label17;
    label34:;
    _r0_o = _ex.getJavaException();
    _ex = null;
    _r0_o = null;
    goto label24;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.lang.String getStringData()]
}

public virtual void setStringData(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setStringData(java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r2_o = this;
    _r3_o = n1;
    _r0_o = new global::gnu.xml.dom.ls.ReaderInputStream();
    _r1_o = new global::java.io.StringReader();
    ((global::java.io.StringReader) _r1_o).@this((global::java.lang.String) _r3_o);
    ((global::gnu.xml.dom.ls.ReaderInputStream) _r0_o).@this((global::java.io.Reader) _r1_o);
    ((global::gnu.xml.dom.ls.DomLSInput) _r2_o)._fin = (global::java.io.InputStream) _r0_o;
    return;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setStringData(java.lang.String)]
}

public virtual global::System.Object getSystemId(){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.lang.String getSystemId()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0_o = ((global::gnu.xml.dom.ls.DomLSInput) _r1_o)._fsystemId;
    return (global::java.lang.String) _r0_o;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.lang.String getSystemId()]
}

public virtual void setSystemId(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setSystemId(java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::gnu.xml.dom.ls.DomLSInput) _r0_o)._fsystemId = (global::java.lang.String) _r1_o;
    return;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setSystemId(java.lang.String)]
}

public virtual global::System.Object getPublicId(){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.lang.String getPublicId()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0_o = ((global::gnu.xml.dom.ls.DomLSInput) _r1_o)._fpublicId;
    return (global::java.lang.String) _r0_o;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.lang.String getPublicId()]
}

public virtual void setPublicId(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setPublicId(java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::gnu.xml.dom.ls.DomLSInput) _r0_o)._fpublicId = (global::java.lang.String) _r1_o;
    return;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setPublicId(java.lang.String)]
}

public virtual global::System.Object getBaseURI(){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.lang.String getBaseURI()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0_o = ((global::gnu.xml.dom.ls.DomLSInput) _r1_o)._fbaseURI;
    return (global::java.lang.String) _r0_o;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.lang.String getBaseURI()]
}

public virtual void setBaseURI(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setBaseURI(java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::gnu.xml.dom.ls.DomLSInput) _r0_o)._fbaseURI = (global::java.lang.String) _r1_o;
    return;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setBaseURI(java.lang.String)]
}

public virtual global::System.Object getEncoding(){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.lang.String getEncoding()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0_o = ((global::gnu.xml.dom.ls.DomLSInput) _r1_o)._fencoding;
    return (global::java.lang.String) _r0_o;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: java.lang.String getEncoding()]
}

public virtual void setEncoding(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setEncoding(java.lang.String)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::gnu.xml.dom.ls.DomLSInput) _r0_o)._fencoding = (global::java.lang.String) _r1_o;
    return;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setEncoding(java.lang.String)]
}

public virtual bool getCertifiedText(){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: boolean getCertifiedText()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r0.i = ((global::gnu.xml.dom.ls.DomLSInput) _r1_o)._fcertifiedText ? 1 : 0;
    return _r0.i!=0;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: boolean getCertifiedText()]
}

public virtual void setCertifiedText(bool n1){
//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setCertifiedText(boolean)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1.i = n1 ? 1 : 0;
    ((global::gnu.xml.dom.ls.DomLSInput) _r0_o)._fcertifiedText = 0!=_r1.i;
    return;
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput: void setCertifiedText(boolean)]
}

//XMLVM_BEGIN_WRAPPER[gnu.xml.dom.ls.DomLSInput]
//XMLVM_END_WRAPPER[gnu.xml.dom.ls.DomLSInput]

} // end of class: DomLSInput

} // end of namespace: gnu.xml.dom.ls
