// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace gnu.xml.stream {
public class XMLParser_2ExternalIds: global::java.lang.Object {
public global::java.lang.String _fpublicId;

public global::java.lang.String _fsystemId;

public global::java.lang.String _fnotationName;

public global::gnu.xml.stream.XMLParser _fthis_20;

public void @this(global::gnu.xml.stream.XMLParser n1){
//XMLVM_BEGIN_WRAPPER[gnu.xml.stream.XMLParser$ExternalIds: void <init>(gnu.xml.stream.XMLParser)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::gnu.xml.stream.XMLParser_2ExternalIds) _r0_o)._fthis_20 = (global::gnu.xml.stream.XMLParser) _r1_o;
    ((global::java.lang.Object) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[gnu.xml.stream.XMLParser$ExternalIds: void <init>(gnu.xml.stream.XMLParser)]
}

//XMLVM_BEGIN_WRAPPER[gnu.xml.stream.XMLParser$ExternalIds]
//XMLVM_END_WRAPPER[gnu.xml.stream.XMLParser$ExternalIds]

} // end of class: XMLParser_2ExternalIds

} // end of namespace: gnu.xml.stream
