// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
using System;
using System.IO;
using System.Threading.Tasks;
namespace org.apache.harmony.luni.platform {
public class OSFileSystem: global::java.lang.Object,global::org.apache.harmony.luni.platform.IFileSystem {

static OSFileSystem() {
    @static();
}

private static global::org.apache.harmony.luni.platform.OSFileSystem _fsingleton;

public static int _fSHARED_1LOCK_1TYPE = org.apache.harmony.luni.platform._iIFileSystem._fSHARED_1LOCK_1TYPE;

public static int _fEXCLUSIVE_1LOCK_1TYPE = org.apache.harmony.luni.platform._iIFileSystem._fEXCLUSIVE_1LOCK_1TYPE;

public static int _fSEEK_1SET = org.apache.harmony.luni.platform._iIFileSystem._fSEEK_1SET;

public static int _fSEEK_1CUR = org.apache.harmony.luni.platform._iIFileSystem._fSEEK_1CUR;

public static int _fSEEK_1END = org.apache.harmony.luni.platform._iIFileSystem._fSEEK_1END;

public static int _fO_1RDONLY = org.apache.harmony.luni.platform._iIFileSystem._fO_1RDONLY;

public static int _fO_1WRONLY = org.apache.harmony.luni.platform._iIFileSystem._fO_1WRONLY;

public static int _fO_1RDWR = org.apache.harmony.luni.platform._iIFileSystem._fO_1RDWR;

public static int _fO_1RDWRSYNC = org.apache.harmony.luni.platform._iIFileSystem._fO_1RDWRSYNC;

public static int _fO_1APPEND = org.apache.harmony.luni.platform._iIFileSystem._fO_1APPEND;

public static int _fO_1CREAT = org.apache.harmony.luni.platform._iIFileSystem._fO_1CREAT;

public static int _fO_1EXCL = org.apache.harmony.luni.platform._iIFileSystem._fO_1EXCL;

public static int _fO_1NOCTTY = org.apache.harmony.luni.platform._iIFileSystem._fO_1NOCTTY;

public static int _fO_1NONBLOCK = org.apache.harmony.luni.platform._iIFileSystem._fO_1NONBLOCK;

public static int _fO_1TRUNC = org.apache.harmony.luni.platform._iIFileSystem._fO_1TRUNC;

public static void @static(){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void <clinit>()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    global::org.apache.harmony.luni.platform.OSFileSystem.oneTimeInitializationImpl();
    _r0_o = new global::org.apache.harmony.luni.platform.OSFileSystem();
    ((global::org.apache.harmony.luni.platform.OSFileSystem) _r0_o).@this();
    global::org.apache.harmony.luni.platform.OSFileSystem._fsingleton = (global::org.apache.harmony.luni.platform.OSFileSystem) _r0_o;
    return;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void <clinit>()]
}

public static global::System.Object getOSFileSystem(){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: org.apache.harmony.luni.platform.OSFileSystem getOSFileSystem()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = global::org.apache.harmony.luni.platform.OSFileSystem._fsingleton;
    return (global::org.apache.harmony.luni.platform.OSFileSystem) _r0_o;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: org.apache.harmony.luni.platform.OSFileSystem getOSFileSystem()]
}

private void @this(){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void <init>()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    ((global::java.lang.Object) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void <init>()]
}

private static void oneTimeInitializationImpl(){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void oneTimeInitializationImpl()]
      //nothing to do
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void oneTimeInitializationImpl()]
}

private void validateLockArgs(int n1, long n2, long n3){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void validateLockArgs(int, long, long)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::System.Object _r8_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r3_o = this;
    _r4.i = n1;
    _r5.l = n2;
    _r7.l = n3;
    _r1.l = 0L;
    _r0.i = 1;
    if (_r4.i == _r0.i) goto label16;
    _r0.i = 2;
    if (_r4.i == _r0.i) goto label16;
    _r0_o = new global::java.lang.IllegalArgumentException();
    // Value=Illegal lock type requested.
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)73)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 103)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 99)), unchecked((char) unchecked((uint) 107)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 121)), unchecked((char) unchecked((uint) 112)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 113)), unchecked((char) unchecked((uint) 117)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 115)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 100)), unchecked((char) unchecked((uint) 46))}));
    ((global::java.lang.IllegalArgumentException) _r0_o).@this((global::java.lang.String) _r1_o);
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r0_o);
    label16:;
    _r0.i = _r5.l > _r1.l ? 1 : (_r5.l == _r1.l ? 0 : -1);
    if (_r0.i >= 0) goto label28;
    _r0_o = new global::java.lang.IllegalArgumentException();
    // Value=Lock start position must be non-negative
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)76)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 99)), unchecked((char) unchecked((uint) 107)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 115)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 114)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 112)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 115)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 117)), unchecked((char) unchecked((uint) 115)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 98)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 45)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 103)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 118)), unchecked((char) unchecked((uint) 101))}));
    ((global::java.lang.IllegalArgumentException) _r0_o).@this((global::java.lang.String) _r1_o);
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r0_o);
    label28:;
    _r0.i = _r7.l > _r1.l ? 1 : (_r7.l == _r1.l ? 0 : -1);
    if (_r0.i >= 0) goto label40;
    _r0_o = new global::java.lang.IllegalArgumentException();
    // Value=Lock length must be non-negative
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)76)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 99)), unchecked((char) unchecked((uint) 107)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 108)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 103)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 104)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 109)), unchecked((char) unchecked((uint) 117)), unchecked((char) unchecked((uint) 115)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 98)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 32)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 111)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 45)), unchecked((char) unchecked((uint) 110)), unchecked((char) unchecked((uint) 101)), unchecked((char) unchecked((uint) 103)), unchecked((char) unchecked((uint) 97)), unchecked((char) unchecked((uint) 116)), unchecked((char) unchecked((uint) 105)), unchecked((char) unchecked((uint) 118)), unchecked((char) unchecked((uint) 101))}));
    ((global::java.lang.IllegalArgumentException) _r0_o).@this((global::java.lang.String) _r1_o);
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.IllegalArgumentException) _r0_o);
    label40:;
    return;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void validateLockArgs(int, long, long)]
}

private int lockImpl(long n1, long n2, long n3, int n4, bool n5){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: int lockImpl(long, long, long, int, boolean)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: int lockImpl(long, long, long, int, boolean)]
}

public virtual int getAllocGranularity(){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: int getAllocGranularity()]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: int getAllocGranularity()]
}

public virtual bool @lock(long n1, long n2, long n3, int n4, bool n5){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: boolean lock(long, long, long, int, boolean)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::System.Object _r8_o = null;
    global::org.xmlvm._nElement _r9;
    global::System.Object _r9_o = null;
    global::org.xmlvm._nElement _r10;
    global::System.Object _r10_o = null;
    global::org.xmlvm._nElement _r11;
    global::System.Object _r11_o = null;
    global::org.xmlvm._nElement _r12;
    global::System.Object _r12_o = null;
    global::org.xmlvm._nElement _r13;
    global::System.Object _r13_o = null;
    global::org.xmlvm._nElement _r14;
    global::System.Object _r14_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r6_o = this;
    _r7.l = n1;
    _r9.l = n2;
    _r11.l = n3;
    _r13.i = n4;
    _r14.i = n5 ? 1 : 0;
    _r0_o = _r6_o;
    _r1.i = _r13.i;
    _r2.l = _r9.l;
    _r4.l = _r11.l;
    ((global::org.apache.harmony.luni.platform.OSFileSystem) _r0_o).validateLockArgs((int) _r1.i, (long) _r2.l, (long) _r4.l);
    _r0.i = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r6_o).lockImpl((long) _r7.l, (long) _r9.l, (long) _r11.l, (int) _r13.i, 0!=_r14.i);
    _r1.i = -1;
    if (_r0.i == _r1.i) goto label16;
    _r0.i = 1;
    label15:;
    return _r0.i!=0;
    label16:;
    _r0.i = 0;
    goto label15;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: boolean lock(long, long, long, int, boolean)]
}

private int unlockImpl(long n1, long n2, long n3){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: int unlockImpl(long, long, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: int unlockImpl(long, long, long)]
}

public virtual void unlock(long n1, long n2, long n3){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void unlock(long, long, long)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::System.Object _r8_o = null;
    global::org.xmlvm._nElement _r9;
    global::System.Object _r9_o = null;
    global::org.xmlvm._nElement _r10;
    global::System.Object _r10_o = null;
    global::org.xmlvm._nElement _r11;
    global::System.Object _r11_o = null;
    global::org.xmlvm._nElement _r12;
    global::System.Object _r12_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r6_o = this;
    _r7.l = n1;
    _r9.l = n2;
    _r11.l = n3;
    _r1.i = 1;
    _r0_o = _r6_o;
    _r2.l = _r9.l;
    _r4.l = _r11.l;
    ((global::org.apache.harmony.luni.platform.OSFileSystem) _r0_o).validateLockArgs((int) _r1.i, (long) _r2.l, (long) _r4.l);
    _r0.i = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r6_o).unlockImpl((long) _r7.l, (long) _r9.l, (long) _r11.l);
    _r1.i = -1;
    if (_r0.i != _r1.i) goto label20;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label20:;
    return;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void unlock(long, long, long)]
}

private int fflushImpl(long n1, bool n2){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: int fflushImpl(long, boolean)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: int fflushImpl(long, boolean)]
}

public virtual void fflush(long n1, bool n2){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void fflush(long, boolean)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r2_o = this;
    _r3.l = n1;
    _r5.i = n2 ? 1 : 0;
    _r0.i = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r2_o).fflushImpl((long) _r3.l, 0!=_r5.i);
    _r1.i = -1;
    if (_r0.i != _r1.i) goto label13;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label13:;
    return;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void fflush(long, boolean)]
}

private long seekImpl(long n1, long n2, int n3){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long seekImpl(long, long, int)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long seekImpl(long, long, int)]
}

public virtual long seek(long n1, long n2, int n3){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long seek(long, long, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::System.Object _r8_o = null;
    global::org.xmlvm._nElement _r9;
    global::System.Object _r9_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r4_o = this;
    _r5.l = n1;
    _r7.l = n2;
    _r9.i = n3;
    _r0.l = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r4_o).seekImpl((long) _r5.l, (long) _r7.l, (int) _r9.i);
    _r2.l = -1L;
    _r2.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r2.i != 0) goto label16;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label16:;
    return _r0.l;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long seek(long, long, int)]
}

private long readDirectImpl(long n1, long n2, int n3, int n4){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long readDirectImpl(long, long, int, int)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long readDirectImpl(long, long, int, int)]
}

public virtual long readDirect(long n1, long n2, int n3, int n4){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long readDirect(long, long, int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::System.Object _r8_o = null;
    global::org.xmlvm._nElement _r9;
    global::System.Object _r9_o = null;
    global::org.xmlvm._nElement _r10;
    global::System.Object _r10_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r4_o = this;
    _r5.l = n1;
    _r7.l = n2;
    _r9.i = n3;
    _r10.i = n4;
    _r0.l = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r4_o).readDirectImpl((long) _r5.l, (long) _r7.l, (int) _r9.i, (int) _r10.i);
    _r2.l = -1L;
    _r2.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r2.i >= 0) goto label16;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label16:;
    return _r0.l;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long readDirect(long, long, int, int)]
}

private long writeDirectImpl(long n1, long n2, int n3, int n4){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long writeDirectImpl(long, long, int, int)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long writeDirectImpl(long, long, int, int)]
}

public virtual long writeDirect(long n1, long n2, int n3, int n4){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long writeDirect(long, long, int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::System.Object _r8_o = null;
    global::org.xmlvm._nElement _r9;
    global::System.Object _r9_o = null;
    global::org.xmlvm._nElement _r10;
    global::System.Object _r10_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r4_o = this;
    _r5.l = n1;
    _r7.l = n2;
    _r9.i = n3;
    _r10.i = n4;
    _r0.l = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r4_o).writeDirectImpl((long) _r5.l, (long) _r7.l, (int) _r9.i, (int) _r10.i);
    _r2.l = 0L;
    _r2.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r2.i >= 0) goto label16;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label16:;
    return _r0.l;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long writeDirect(long, long, int, int)]
}

private long readImpl(long n1, global::org.xmlvm._nArrayAdapter<sbyte> n2, int n3, int n4){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long readImpl(long, byte[], int, int)]
#if CONSOLE
    throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
#else 
    Task<Stream> t = readImplAsync(n1, n2, n3, n4);
    Stream stream = t.Result;
    return stream.Read((byte[])(global::System.Array)n2.getCSharpArray(), n3, n4);
#endif
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long readImpl(long, byte[], int, int)]
}

private async Task<Stream> readImplAsync(long n1, global::org.xmlvm._nArrayAdapter<sbyte> n2, int n3, int n4)
{
    var randomAccessStream = await files[n1].OpenReadAsync();
    return randomAccessStream.AsStreamForRead();
}

public virtual long read(long n1, global::org.xmlvm._nArrayAdapter<sbyte> n2, int n3, int n4){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long read(long, byte[], int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::System.Object _r8_o = null;
    global::org.xmlvm._nElement _r9;
    global::System.Object _r9_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r4_o = this;
    _r5.l = n1;
    _r7_o = n2;
    _r8.i = n3;
    _r9.i = n4;
    if (_r7_o != null) goto label8;
    _r0_o = new global::java.lang.NullPointerException();
    ((global::java.lang.NullPointerException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.NullPointerException) _r0_o);
    label8:;
    _r0.l = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r4_o).readImpl((long) _r5.l, (global::org.xmlvm._nArrayAdapter<sbyte>) _r7_o, (int) _r8.i, (int) _r9.i);
    _r2.l = -1L;
    _r2.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r2.i >= 0) goto label24;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label24:;
    return _r0.l;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long read(long, byte[], int, int)]
}

private long writeImpl(long n1, global::org.xmlvm._nArrayAdapter<sbyte> n2, int n3, int n4){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long writeImpl(long, byte[], int, int)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long writeImpl(long, byte[], int, int)]
}

public virtual long write(long n1, global::org.xmlvm._nArrayAdapter<sbyte> n2, int n3, int n4){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long write(long, byte[], int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::System.Object _r8_o = null;
    global::org.xmlvm._nElement _r9;
    global::System.Object _r9_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r4_o = this;
    _r5.l = n1;
    _r7_o = n2;
    _r8.i = n3;
    _r9.i = n4;
    _r0.l = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r4_o).writeImpl((long) _r5.l, (global::org.xmlvm._nArrayAdapter<sbyte>) _r7_o, (int) _r8.i, (int) _r9.i);
    _r2.l = 0L;
    _r2.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r2.i >= 0) goto label16;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label16:;
    return _r0.l;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long write(long, byte[], int, int)]
}

public virtual long readv(long n1, global::org.xmlvm._nArrayAdapter<long> n2, global::org.xmlvm._nArrayAdapter<int> n3, global::org.xmlvm._nArrayAdapter<int> n4, int n5){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long readv(long, long[], int[], int[], int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::System.Object _r8_o = null;
    global::org.xmlvm._nElement _r9;
    global::System.Object _r9_o = null;
    global::org.xmlvm._nElement _r10;
    global::System.Object _r10_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r4_o = this;
    _r5.l = n1;
    _r7_o = n2;
    _r8_o = n3;
    _r9_o = n4;
    _r10.i = n5;
    _r0.l = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r4_o).readvImpl((long) _r5.l, (global::org.xmlvm._nArrayAdapter<long>) _r7_o, (global::org.xmlvm._nArrayAdapter<int>) _r8_o, (global::org.xmlvm._nArrayAdapter<int>) _r9_o, (int) _r10.i);
    _r2.l = -1L;
    _r2.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r2.i >= 0) goto label16;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label16:;
    return _r0.l;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long readv(long, long[], int[], int[], int)]
}

private long readvImpl(long n1, global::org.xmlvm._nArrayAdapter<long> n2, global::org.xmlvm._nArrayAdapter<int> n3, global::org.xmlvm._nArrayAdapter<int> n4, int n5){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long readvImpl(long, long[], int[], int[], int)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long readvImpl(long, long[], int[], int[], int)]
}

public virtual long writev(long n1, global::org.xmlvm._nArrayAdapter<global::System.Object> n2, global::org.xmlvm._nArrayAdapter<int> n3, global::org.xmlvm._nArrayAdapter<int> n4, int n5){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long writev(long, java.lang.Object[], int[], int[], int)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long writev(long, java.lang.Object[], int[], int[], int)]
}

private int closeImpl(long n1){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: int closeImpl(long)]
#if CONSOLE
    throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
#else 
    //files[n1].Stream.Close();
    return 0;
#endif
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: int closeImpl(long)]
}

public virtual void close(long n1){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void close(long)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r2_o = this;
    _r3.l = n1;
    _r0.i = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r2_o).closeImpl((long) _r3.l);
    _r1.i = -1;
    if (_r0.i != _r1.i) goto label13;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label13:;
    return;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void close(long)]
}

public virtual void truncate(long n1, long n2){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void truncate(long, long)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r1_o = this;
    _r2.l = n1;
    _r4.l = n2;
    _r0.i = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r1_o).truncateImpl((long) _r2.l, (long) _r4.l);
    if (_r0.i >= 0) goto label12;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label12:;
    return;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: void truncate(long, long)]
}

private int truncateImpl(long n1, long n2){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: int truncateImpl(long, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: int truncateImpl(long, long)]
}

public virtual long open(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long open(byte[], int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r4_o = this;
    _r5_o = n1;
    _r6.i = n2;
    if (_r5_o != null) goto label8;
    _r0_o = new global::java.lang.NullPointerException();
    ((global::java.lang.NullPointerException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.NullPointerException) _r0_o);
    label8:;
    _r0.l = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r4_o).openImpl((global::org.xmlvm._nArrayAdapter<sbyte>) _r5_o, (int) _r6.i);
    _r2.l = 0L;
    _r2.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r2.i >= 0) goto label51;
    try {
    _r0_o = new global::java.io.FileNotFoundException();
    _r1_o = new global::java.lang.String();
    // Value=UTF-8
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String)_r2_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)85)), unchecked((char) unchecked((uint) 84)), unchecked((char) unchecked((uint) 70)), unchecked((char) unchecked((uint) 45)), unchecked((char) unchecked((uint) 56))}));
    ((global::java.lang.String) _r1_o).@this((global::org.xmlvm._nArrayAdapter<sbyte>) _r5_o, (global::java.lang.String) _r2_o);
    ((global::java.io.FileNotFoundException) _r0_o).@this((global::java.lang.String) _r1_o);
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.FileNotFoundException) _r0_o);
    }
    catch (global::System.Exception e) {
 global::org.xmlvm._nExceptionAdapter ex = e as global::org.xmlvm._nExceptionAdapter ?? new global::org.xmlvm._nExceptionAdapter(e.ToString(), e.ToJavaException());
        global::System.Object _java_exception = ex.getJavaException();
        if (_java_exception is global::java.io.UnsupportedEncodingException) {
            _ex = ex;
            goto label31;
        }
        throw ex;
    } // end catch
    label31:;
    _r0_o = _ex.getJavaException();
    _ex = null;
    _r1_o = new global::java.io.FileNotFoundException();
    _r2_o = new global::java.lang.String();
    ((global::java.lang.String) _r2_o).@this((global::org.xmlvm._nArrayAdapter<sbyte>) _r5_o);
    ((global::java.io.FileNotFoundException) _r1_o).@this((global::java.lang.String) _r2_o);
    ((global::java.io.UnsupportedEncodingException) _r0_o).initCause((global::java.lang.Throwable) _r1_o);
    _r1_o = new global::java.lang.AssertionError();
    ((global::java.lang.AssertionError) _r1_o).@this((global::java.lang.Object) _r0_o);
    throw new global::org.xmlvm._nExceptionAdapter((global::java.lang.AssertionError) _r1_o);
    label51:;
    return _r0.l;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long open(byte[], int)]
}

private long openImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2)
{
    Task<long> t = openImplAsync(n1, n2);
    return t.Result;
}
private async Task<long> openImplAsync(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long openImpl(byte[], int)]
#if CONSOLE
    throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
#else 
    global::java.lang.String path = new global::java.lang.String();
    path.@this(n1);
    long thisIndex = descriptor;
    descriptor++;
    global::System.String nativePath = global::org.xmlvm._nUtil.toNativeString(path);
    if (nativePath.StartsWith("/"))
    {
        nativePath = nativePath.Substring(1);
    }
    global::System.Uri uri = new global::System.Uri(nativePath, global::System.UriKind.Relative);
    files[thisIndex] = await global::Windows.Storage.StorageFile.GetFileFromApplicationUriAsync(uri);
    filesProps[thisIndex] = await files[thisIndex].GetBasicPropertiesAsync();
    filesStreams[thisIndex] = await files[thisIndex].OpenAsync(Windows.Storage.FileAccessMode.ReadWrite);
    return thisIndex;
#endif
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long openImpl(byte[], int)]
}

public virtual long transfer(long n1, global::java.io.FileDescriptor n2, long n3, long n4){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long transfer(long, java.io.FileDescriptor, long, long)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nElement _r8;
    global::System.Object _r8_o = null;
    global::org.xmlvm._nElement _r9;
    global::System.Object _r9_o = null;
    global::org.xmlvm._nElement _r10;
    global::System.Object _r10_o = null;
    global::org.xmlvm._nElement _r11;
    global::System.Object _r11_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r4_o = this;
    _r5.l = n1;
    _r7_o = n2;
    _r8.l = n3;
    _r10.l = n4;
    _r0.l = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r4_o).transferImpl((long) _r5.l, (global::java.io.FileDescriptor) _r7_o, (long) _r8.l, (long) _r10.l);
    _r2.l = 0L;
    _r2.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r2.i >= 0) goto label16;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label16:;
    return _r0.l;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long transfer(long, java.io.FileDescriptor, long, long)]
}

private long transferImpl(long n1, global::java.io.FileDescriptor n2, long n3, long n4){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long transferImpl(long, java.io.FileDescriptor, long, long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long transferImpl(long, java.io.FileDescriptor, long, long)]
}

public virtual long ttyAvailable(){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long ttyAvailable()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r4_o = this;
    _r0.l = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r4_o).ttyAvailableImpl();
    _r2.l = 0L;
    _r2.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r2.i >= 0) goto label16;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label16:;
    return _r0.l;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long ttyAvailable()]
}

private long ttyAvailableImpl(){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long ttyAvailableImpl()]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long ttyAvailableImpl()]
}

public virtual long available(long n1){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long available(long)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r4_o = this;
    _r5.l = n1;
    _r0.l = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r4_o).availableImpl((long) _r5.l);
    _r2.l = 0L;
    _r2.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r2.i >= 0) goto label16;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label16:;
    return _r0.l;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long available(long)]
}

private long availableImpl(long n1){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long availableImpl(long)]
#if CONSOLE
    throw new org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
#else 
    return (long)(filesStreams[n1].Size - filesStreams[n1].Position);
#endif
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long availableImpl(long)]
}

public virtual long size(long n1){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long size(long)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r4_o = this;
    _r5.l = n1;
    _r0.l = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r4_o).sizeImpl((long) _r5.l);
    _r2.l = 0L;
    _r2.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r2.i >= 0) goto label16;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label16:;
    return _r0.l;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long size(long)]
}

private long sizeImpl(long n1){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long sizeImpl(long)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long sizeImpl(long)]
}

public virtual long ttyRead(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2, int n3){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long ttyRead(byte[], int, int)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r4_o = null;
    global::org.xmlvm._nElement _r5;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r7_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r4_o = this;
    _r5_o = n1;
    _r6.i = n2;
    _r7.i = n3;
    _r0.l = ((global::org.apache.harmony.luni.platform.OSFileSystem) _r4_o).ttyReadImpl((global::org.xmlvm._nArrayAdapter<sbyte>) _r5_o, (int) _r6.i, (int) _r7.i);
    _r2.l = 0L;
    _r2.i = _r0.l > _r2.l ? 1 : (_r0.l == _r2.l ? 0 : -1);
    if (_r2.i >= 0) goto label16;
    _r0_o = new global::java.io.IOException();
    ((global::java.io.IOException) _r0_o).@this();
    throw new global::org.xmlvm._nExceptionAdapter((global::java.io.IOException) _r0_o);
    label16:;
    return _r0.l;
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long ttyRead(byte[], int, int)]
}

private long ttyReadImpl(global::org.xmlvm._nArrayAdapter<sbyte> n1, int n2, int n3){
//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long ttyReadImpl(byte[], int, int)]
      throw new global::org.xmlvm._nNotYetImplementedException("native/wrapper method not yet implemented");
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem: long ttyReadImpl(byte[], int, int)]
}

//XMLVM_BEGIN_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem]
#if CONSOLE

#else 
	private long descriptor;
    private global::System.Collections.Generic.Dictionary<long, global::Windows.Storage.StorageFile> files = new System.Collections.Generic.Dictionary<long, global::Windows.Storage.StorageFile>();
    private global::System.Collections.Generic.Dictionary<long, global::Windows.Storage.FileProperties.BasicProperties> filesProps = new System.Collections.Generic.Dictionary<long, global::Windows.Storage.FileProperties.BasicProperties>();
    private global::System.Collections.Generic.Dictionary<long, global::Windows.Storage.Streams.IRandomAccessStream> filesStreams = new System.Collections.Generic.Dictionary<long, global::Windows.Storage.Streams.IRandomAccessStream>();
#endif
//XMLVM_END_WRAPPER[org.apache.harmony.luni.platform.OSFileSystem]

} // end of class: OSFileSystem

} // end of namespace: org.apache.harmony.luni.platform
