// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.net {
public class BindException: global::java.net.SocketException {
private static long _fserialVersionUID = -5945005768251722951L;

public void @this(){
//XMLVM_BEGIN_WRAPPER[java.net.BindException: void <init>()]
    global::System.Object _r0_o = null;
    _r0_o = this;
    ((global::java.net.SocketException) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[java.net.BindException: void <init>()]
}

public void @this(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[java.net.BindException: void <init>(java.lang.String)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::java.net.SocketException) _r0_o).@this((global::java.lang.String) _r1_o);
    return;
//XMLVM_END_WRAPPER[java.net.BindException: void <init>(java.lang.String)]
}

//XMLVM_BEGIN_WRAPPER[java.net.BindException]
//XMLVM_END_WRAPPER[java.net.BindException]

} // end of class: BindException

} // end of namespace: java.net
