// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace com.codename1.ui.html {
public class HTMLInputFormat_21: global::com.codename1.ui.TextField {
public global::com.codename1.ui.html.HTMLInputFormat _fthis_20;

public void @this(global::com.codename1.ui.html.HTMLInputFormat n1, global::java.lang.String n2){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.html.HTMLInputFormat$1: void <init>(com.codename1.ui.html.HTMLInputFormat, java.lang.String)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    _r0_o = this;
    _r1_o = n1;
    _r2_o = n2;
    ((global::com.codename1.ui.html.HTMLInputFormat_21) _r0_o)._fthis_20 = (global::com.codename1.ui.html.HTMLInputFormat) _r1_o;
    ((global::com.codename1.ui.TextField) _r0_o).@this((global::java.lang.String) _r2_o);
    return;
//XMLVM_END_WRAPPER[com.codename1.ui.html.HTMLInputFormat$1: void <init>(com.codename1.ui.html.HTMLInputFormat, java.lang.String)]
}

public override void showSymbolDialog(){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.html.HTMLInputFormat$1: void showSymbolDialog()]
    global::System.Object _r0_o = null;
    _r0_o = this;
    return;
//XMLVM_END_WRAPPER[com.codename1.ui.html.HTMLInputFormat$1: void showSymbolDialog()]
}

//XMLVM_BEGIN_WRAPPER[com.codename1.ui.html.HTMLInputFormat$1]
//XMLVM_END_WRAPPER[com.codename1.ui.html.HTMLInputFormat$1]

} // end of class: HTMLInputFormat_21

} // end of namespace: com.codename1.ui.html
