// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace com.codename1.ui.html {
public class HTMLComponent_26: global::java.lang.Object,global::java.lang.Runnable {
public global::com.codename1.ui.html.HTMLComponent _fthis_20;

public void @this(global::com.codename1.ui.html.HTMLComponent n1){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.html.HTMLComponent$6: void <init>(com.codename1.ui.html.HTMLComponent)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::com.codename1.ui.html.HTMLComponent_26) _r0_o)._fthis_20 = (global::com.codename1.ui.html.HTMLComponent) _r1_o;
    ((global::java.lang.Object) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[com.codename1.ui.html.HTMLComponent$6: void <init>(com.codename1.ui.html.HTMLComponent)]
}

public virtual void run(){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.html.HTMLComponent$6: void run()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nExceptionAdapter _ex = null;
    _r3_o = this;
    _r0_o = ((global::com.codename1.ui.html.HTMLComponent_26) _r3_o)._fthis_20;
    _r0_o = global::com.codename1.ui.html.HTMLComponent.access_2300((global::com.codename1.ui.html.HTMLComponent) _r0_o);
    _r1_o = ((global::com.codename1.ui.html.HTMLComponent_26) _r3_o)._fthis_20;
    _r2_o = ((global::com.codename1.ui.html.HTMLComponent_26) _r3_o)._fthis_20;
    _r2_o = global::com.codename1.ui.html.HTMLComponent.access_2400((global::com.codename1.ui.html.HTMLComponent) _r2_o);
    ((global::com.codename1.ui.html.HTMLCallback) _r0_o).titleUpdated((global::com.codename1.ui.html.HTMLComponent) _r1_o, (global::java.lang.String) _r2_o);
    return;
//XMLVM_END_WRAPPER[com.codename1.ui.html.HTMLComponent$6: void run()]
}

//XMLVM_BEGIN_WRAPPER[com.codename1.ui.html.HTMLComponent$6]
//XMLVM_END_WRAPPER[com.codename1.ui.html.HTMLComponent$6]

} // end of class: HTMLComponent_26

} // end of namespace: com.codename1.ui.html
