// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace com.codename1.ui.events {
public abstract class _iStyleListener {

} // end of abstract class: _iStyleListener

public interface StyleListener {
 void styleChanged(global::java.lang.String n1, global::com.codename1.ui.plaf.Style n2);

//XMLVM_BEGIN_WRAPPER[com.codename1.ui.events.StyleListener]
//XMLVM_END_WRAPPER[com.codename1.ui.events.StyleListener]

} // end of interface: StyleListener

} // end of namespace: com.codename1.ui.events
