// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace com.codename1.ui {
public class URLImage_22: global::java.lang.Object,global::com.codename1.ui.URLImage_2ImageAdapter {
new public void @this(){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.URLImage$2: void <init>()]
    global::System.Object _r0_o = null;
    _r0_o = this;
    ((global::java.lang.Object) _r0_o).@this();
    return;
//XMLVM_END_WRAPPER[com.codename1.ui.URLImage$2: void <init>()]
}

public virtual global::System.Object adaptImage(global::com.codename1.ui.EncodedImage n1, global::com.codename1.ui.EncodedImage n2){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.URLImage$2: com.codename1.ui.EncodedImage adaptImage(com.codename1.ui.EncodedImage, com.codename1.ui.EncodedImage)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    global::System.Object _r4_o = null;
    _r2_o = this;
    _r3_o = n1;
    _r4_o = n2;
    _r0.i = ((global::com.codename1.ui.EncodedImage) _r3_o).getWidth();
    _r1.i = ((global::com.codename1.ui.EncodedImage) _r4_o).getWidth();
    if (_r0.i != _r1.i) goto label20;
    _r0.i = ((global::com.codename1.ui.EncodedImage) _r3_o).getHeight();
    _r1.i = ((global::com.codename1.ui.EncodedImage) _r4_o).getHeight();
    if (_r0.i == _r1.i) goto label33;
    label20:;
    _r0.i = ((global::com.codename1.ui.EncodedImage) _r4_o).getWidth();
    _r1.i = ((global::com.codename1.ui.EncodedImage) _r4_o).getHeight();
    _r0_o = ((global::com.codename1.ui.EncodedImage) _r3_o).scaledEncoded((int) _r0.i, (int) _r1.i);
    label32:;
    return (global::com.codename1.ui.EncodedImage) _r0_o;
    label33:;
    _r0_o = _r3_o;
    goto label32;
//XMLVM_END_WRAPPER[com.codename1.ui.URLImage$2: com.codename1.ui.EncodedImage adaptImage(com.codename1.ui.EncodedImage, com.codename1.ui.EncodedImage)]
}

public virtual bool isAsyncAdapter(){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.URLImage$2: boolean isAsyncAdapter()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r1_o = null;
    _r1_o = this;
    _r0.i = 0;
    return _r0.i!=0;
//XMLVM_END_WRAPPER[com.codename1.ui.URLImage$2: boolean isAsyncAdapter()]
}

//XMLVM_BEGIN_WRAPPER[com.codename1.ui.URLImage$2]
//XMLVM_END_WRAPPER[com.codename1.ui.URLImage$2]

} // end of class: URLImage_22

} // end of namespace: com.codename1.ui
