// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace com.codename1.ui.painter {
public class PainterChain: global::java.lang.Object,global::com.codename1.ui.Painter {
private global::org.xmlvm._nArrayAdapter<global::System.Object> _fchain;

public void @this(global::org.xmlvm._nArrayAdapter<global::System.Object> n1){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.painter.PainterChain: void <init>(com.codename1.ui.Painter[])]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    _r0_o = this;
    _r1_o = n1;
    ((global::java.lang.Object) _r0_o).@this();
    ((global::com.codename1.ui.painter.PainterChain) _r0_o)._fchain = (global::org.xmlvm._nArrayAdapter<global::System.Object>) _r1_o;
    return;
//XMLVM_END_WRAPPER[com.codename1.ui.painter.PainterChain: void <init>(com.codename1.ui.Painter[])]
}

public void @this(global::com.codename1.ui.Painter n1){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.painter.PainterChain: void <init>(com.codename1.ui.Painter)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    _r2_o = this;
    _r3_o = n1;
    ((global::java.lang.Object) _r2_o).@this();
    _r0.i = 1;
    _r0_o = new global::org.xmlvm._nArrayAdapter<global::System.Object>(new global::System.Object[_r0.i]);
    _r1.i = 0;
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r3_o;
    ((global::com.codename1.ui.painter.PainterChain) _r2_o)._fchain = (global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o;
    return;
//XMLVM_END_WRAPPER[com.codename1.ui.painter.PainterChain: void <init>(com.codename1.ui.Painter)]
}

public virtual global::System.Object addPainter(global::com.codename1.ui.Painter n1){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.painter.PainterChain: com.codename1.ui.painter.PainterChain addPainter(com.codename1.ui.Painter)]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    _r4_o = this;
    _r5_o = n1;
    _r3.i = 0;
    _r1_o = ((global::com.codename1.ui.painter.PainterChain) _r4_o)._fchain;
    _r1.i = ((global::org.xmlvm._nIArray) _r1_o).Length;
    if (_r1.i == 0) goto label32;
    _r1_o = ((global::com.codename1.ui.painter.PainterChain) _r4_o)._fchain;
    _r1.i = ((global::org.xmlvm._nIArray) _r1_o).Length;
    _r1.i = _r1.i + 1;
    _r0_o = new global::org.xmlvm._nArrayAdapter<global::System.Object>(new global::System.Object[_r1.i]);
    _r1_o = ((global::com.codename1.ui.painter.PainterChain) _r4_o)._fchain;
    _r2_o = ((global::com.codename1.ui.painter.PainterChain) _r4_o)._fchain;
    _r2.i = ((global::org.xmlvm._nIArray) _r2_o).Length;
    global::java.lang.System.arraycopy((global::java.lang.Object) _r1_o, (int) _r3.i, (global::java.lang.Object) _r0_o, (int) _r3.i, (int) _r2.i);
    _r1_o = ((global::com.codename1.ui.painter.PainterChain) _r4_o)._fchain;
    _r1.i = ((global::org.xmlvm._nIArray) _r1_o).Length;
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r1.i] = _r5_o;
    _r1_o = new global::com.codename1.ui.painter.PainterChain();
    ((global::com.codename1.ui.painter.PainterChain) _r1_o).@this((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o);
    label31:;
    return (global::com.codename1.ui.painter.PainterChain) _r1_o;
    label32:;
    _r1_o = new global::com.codename1.ui.painter.PainterChain();
    _r2.i = 1;
    _r2_o = new global::org.xmlvm._nArrayAdapter<global::System.Object>(new global::System.Object[_r2.i]);
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r2_o)[_r3.i] = _r5_o;
    ((global::com.codename1.ui.painter.PainterChain) _r1_o).@this((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r2_o);
    goto label31;
//XMLVM_END_WRAPPER[com.codename1.ui.painter.PainterChain: com.codename1.ui.painter.PainterChain addPainter(com.codename1.ui.Painter)]
}

public virtual global::System.Object prependPainter(global::com.codename1.ui.Painter n1){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.painter.PainterChain: com.codename1.ui.painter.PainterChain prependPainter(com.codename1.ui.Painter)]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r5_o = null;
    global::System.Object _r6_o = null;
    _r5_o = this;
    _r6_o = n1;
    _r4.i = 0;
    _r1_o = ((global::com.codename1.ui.painter.PainterChain) _r5_o)._fchain;
    _r1.i = ((global::org.xmlvm._nIArray) _r1_o).Length;
    _r1.i = _r1.i + 1;
    _r0_o = new global::org.xmlvm._nArrayAdapter<global::System.Object>(new global::System.Object[_r1.i]);
    _r1_o = ((global::com.codename1.ui.painter.PainterChain) _r5_o)._fchain;
    _r2.i = 1;
    _r3_o = ((global::com.codename1.ui.painter.PainterChain) _r5_o)._fchain;
    _r3.i = ((global::org.xmlvm._nIArray) _r3_o).Length;
    global::java.lang.System.arraycopy((global::java.lang.Object) _r1_o, (int) _r2.i, (global::java.lang.Object) _r0_o, (int) _r4.i, (int) _r3.i);
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r4.i] = _r6_o;
    _r1_o = new global::com.codename1.ui.painter.PainterChain();
    ((global::com.codename1.ui.painter.PainterChain) _r1_o).@this((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o);
    return (global::com.codename1.ui.painter.PainterChain) _r1_o;
//XMLVM_END_WRAPPER[com.codename1.ui.painter.PainterChain: com.codename1.ui.painter.PainterChain prependPainter(com.codename1.ui.Painter)]
}

public virtual void paint(global::com.codename1.ui.Graphics n1, global::com.codename1.ui.geom.Rectangle n2){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.painter.PainterChain: void paint(com.codename1.ui.Graphics, com.codename1.ui.geom.Rectangle)]
    global::org.xmlvm._nElement _r0;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    global::System.Object _r3_o = null;
    global::System.Object _r4_o = null;
    _r2_o = this;
    _r3_o = n1;
    _r4_o = n2;
    _r0.i = 0;
    label1:;
    _r1_o = ((global::com.codename1.ui.painter.PainterChain) _r2_o)._fchain;
    _r1.i = ((global::org.xmlvm._nIArray) _r1_o).Length;
    if (_r0.i >= _r1.i) goto label16;
    _r1_o = ((global::com.codename1.ui.painter.PainterChain) _r2_o)._fchain;
    _r1_o = ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r1_o)[_r0.i];
    ((global::com.codename1.ui.Painter) _r1_o).paint((global::com.codename1.ui.Graphics) _r3_o, (global::com.codename1.ui.geom.Rectangle) _r4_o);
    _r0.i = _r0.i + 1;
    goto label1;
    label16:;
    return;
//XMLVM_END_WRAPPER[com.codename1.ui.painter.PainterChain: void paint(com.codename1.ui.Graphics, com.codename1.ui.geom.Rectangle)]
}

public static void installGlassPane(global::com.codename1.ui.Form n1, global::com.codename1.ui.Painter n2){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.painter.PainterChain: void installGlassPane(com.codename1.ui.Form, com.codename1.ui.Painter)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    _r4_o = n1;
    _r5_o = n2;
    _r0_o = ((global::com.codename1.ui.Form) _r4_o).getGlassPane();
    if (_r0_o != null) goto label10;
    ((global::com.codename1.ui.Form) _r4_o).setGlassPane((global::com.codename1.ui.Painter) _r5_o);
    label9:;
    return;
    label10:;
    _r2.i = ((_r0_o != null) && (_r0_o is global::com.codename1.ui.painter.PainterChain)) ? 1 : 0;
    if (_r2.i == 0) goto label24;
    _r2_o = ((global::com.codename1.ui.painter.PainterChain) _r0_o).addPainter((global::com.codename1.ui.Painter) _r5_o);
    ((global::com.codename1.ui.Form) _r4_o).setGlassPane((global::com.codename1.ui.Painter) _r2_o);
    goto label9;
    label24:;
    _r1_o = new global::com.codename1.ui.painter.PainterChain();
    _r2.i = 2;
    _r2_o = new global::org.xmlvm._nArrayAdapter<global::System.Object>(new global::System.Object[_r2.i]);
    _r3.i = 0;
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r2_o)[_r3.i] = _r0_o;
    _r3.i = 1;
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r2_o)[_r3.i] = _r5_o;
    ((global::com.codename1.ui.painter.PainterChain) _r1_o).@this((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r2_o);
    ((global::com.codename1.ui.Form) _r4_o).setGlassPane((global::com.codename1.ui.Painter) _r1_o);
    goto label9;
//XMLVM_END_WRAPPER[com.codename1.ui.painter.PainterChain: void installGlassPane(com.codename1.ui.Form, com.codename1.ui.Painter)]
}

public virtual global::System.Object getChain(){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.painter.PainterChain: com.codename1.ui.Painter[] getChain()]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    _r1_o = this;
    _r0_o = ((global::com.codename1.ui.painter.PainterChain) _r1_o)._fchain;
    return (global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o;
//XMLVM_END_WRAPPER[com.codename1.ui.painter.PainterChain: com.codename1.ui.Painter[] getChain()]
}

public static void removeGlassPane(global::com.codename1.ui.Form n1, global::com.codename1.ui.Painter n2){
//XMLVM_BEGIN_WRAPPER[com.codename1.ui.painter.PainterChain: void removeGlassPane(com.codename1.ui.Form, com.codename1.ui.Painter)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r3_o = null;
    global::System.Object _r4_o = null;
    global::System.Object _r5_o = null;
    global::org.xmlvm._nElement _r6;
    global::System.Object _r6_o = null;
    global::org.xmlvm._nElement _r7;
    global::System.Object _r8_o = null;
    global::System.Object _r9_o = null;
    global::System.Object _r10_o = null;
    _r9_o = n1;
    _r10_o = n2;
    _r8_o = null;
    _r1_o = ((global::com.codename1.ui.Form) _r9_o).getGlassPane();
    if (_r1_o != null) goto label8;
    label7:;
    return;
    label8:;
    if (_r1_o != _r10_o) goto label14;
    ((global::com.codename1.ui.Form) _r9_o).setGlassPane((global::com.codename1.ui.Painter) _r8_o);
    goto label7;
    label14:;
    _r6.i = ((_r1_o != null) && (_r1_o is global::com.codename1.ui.painter.PainterChain)) ? 1 : 0;
    if (_r6.i == 0) goto label7;
    _r0_o = _r1_o;
    _r4_o = _r0_o;
    _r6_o = ((global::com.codename1.ui.painter.PainterChain) _r4_o)._fchain;
    _r6.i = ((global::org.xmlvm._nIArray) _r6_o).Length;
    _r7.i = 1;
    if (_r6.i != _r7.i) goto label32;
    ((global::com.codename1.ui.Form) _r9_o).setGlassPane((global::com.codename1.ui.Painter) _r8_o);
    goto label7;
    label32:;
    _r5_o = new global::java.util.Vector();
    ((global::java.util.Vector) _r5_o).@this();
    _r2.i = 0;
    label38:;
    _r6_o = ((global::com.codename1.ui.painter.PainterChain) _r4_o)._fchain;
    _r6.i = ((global::org.xmlvm._nIArray) _r6_o).Length;
    if (_r2.i >= _r6.i) goto label59;
    _r6_o = ((global::com.codename1.ui.painter.PainterChain) _r4_o)._fchain;
    _r6_o = ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r6_o)[_r2.i];
    if (_r6_o == _r10_o) goto label56;
    _r6_o = ((global::com.codename1.ui.painter.PainterChain) _r4_o)._fchain;
    _r6_o = ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r6_o)[_r2.i];
    ((global::java.util.Vector) _r5_o).addElement((global::java.lang.Object) _r6_o);
    label56:;
    _r2.i = _r2.i + 1;
    goto label38;
    label59:;
    _r6.i = ((global::java.util.Vector) _r5_o).size();
    if (_r6.i != 0) goto label69;
    ((global::com.codename1.ui.Form) _r9_o).setGlassPane((global::com.codename1.ui.Painter) _r8_o);
    goto label7;
    label69:;
    _r6.i = ((global::java.util.Vector) _r5_o).size();
    _r3_o = new global::org.xmlvm._nArrayAdapter<global::System.Object>(new global::System.Object[_r6.i]);
    _r2.i = 0;
    label76:;
    _r6.i = ((global::org.xmlvm._nIArray) _r3_o).Length;
    if (_r2.i >= _r6.i) goto label90;
    _r6_o = ((global::java.util.Vector) _r5_o).elementAt((int) _r2.i);
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r3_o)[_r2.i] = _r6_o;
    _r2.i = _r2.i + 1;
    goto label76;
    label90:;
    ((global::com.codename1.ui.painter.PainterChain) _r4_o)._fchain = (global::org.xmlvm._nArrayAdapter<global::System.Object>) _r3_o;
    ((global::com.codename1.ui.Form) _r9_o).repaint();
    goto label7;
//XMLVM_END_WRAPPER[com.codename1.ui.painter.PainterChain: void removeGlassPane(com.codename1.ui.Form, com.codename1.ui.Painter)]
}

//XMLVM_BEGIN_WRAPPER[com.codename1.ui.painter.PainterChain]
//XMLVM_END_WRAPPER[com.codename1.ui.painter.PainterChain]

} // end of class: PainterChain

} // end of namespace: com.codename1.ui.painter
