// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace com.codename1.charts.compat {
public class Paint_2Style: global::java.lang.Enum {

static Paint_2Style() {
    @static();
}

public static global::com.codename1.charts.compat.Paint_2Style _fFILL;

public static global::com.codename1.charts.compat.Paint_2Style _fFILL_1AND_1STROKE;

public static global::com.codename1.charts.compat.Paint_2Style _fSTROKE;

private static global::org.xmlvm._nArrayAdapter<global::System.Object> _f_2VALUES;

public static global::System.Object values(){
//XMLVM_BEGIN_WRAPPER[com.codename1.charts.compat.Paint$Style: com.codename1.charts.compat.Paint$Style[] values()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r2_o = null;
    global::org.xmlvm._nElement _r3;
    _r3.i = 0;
    _r0_o = global::com.codename1.charts.compat.Paint_2Style._f_2VALUES;
    _r0.i = ((global::org.xmlvm._nIArray) _r0_o).Length;
    _r0_o = new global::org.xmlvm._nArrayAdapter<global::System.Object>(new global::System.Object[_r0.i]);
    _r1_o = global::com.codename1.charts.compat.Paint_2Style._f_2VALUES;
    _r2_o = global::com.codename1.charts.compat.Paint_2Style._f_2VALUES;
    _r2.i = ((global::org.xmlvm._nIArray) _r2_o).Length;
    global::java.lang.System.arraycopy((global::java.lang.Object) _r1_o, (int) _r3.i, (global::java.lang.Object) _r0_o, (int) _r3.i, (int) _r2.i);
    return (global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o;
//XMLVM_END_WRAPPER[com.codename1.charts.compat.Paint$Style: com.codename1.charts.compat.Paint$Style[] values()]
}

public static global::System.Object valueOf(global::java.lang.String n1){
//XMLVM_BEGIN_WRAPPER[com.codename1.charts.compat.Paint$Style: com.codename1.charts.compat.Paint$Style valueOf(java.lang.String)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    _r1_o = n1;
    _r0_o = global::org.xmlvm._nTIB.getClass(typeof(global::com.codename1.charts.compat.Paint_2Style));
    _r1_o = global::java.lang.Enum.valueOf((global::java.lang.Class) _r0_o, (global::java.lang.String) _r1_o);
    return (global::com.codename1.charts.compat.Paint_2Style) _r1_o;
//XMLVM_END_WRAPPER[com.codename1.charts.compat.Paint$Style: com.codename1.charts.compat.Paint$Style valueOf(java.lang.String)]
}

new private void @this(global::java.lang.String n1, int n2){
//XMLVM_BEGIN_WRAPPER[com.codename1.charts.compat.Paint$Style: void <init>(java.lang.String, int)]
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    _r0_o = this;
    _r1_o = n1;
    _r2.i = n2;
    ((global::java.lang.Enum) _r0_o).@this((global::java.lang.String) _r1_o, (int) _r2.i);
    return;
//XMLVM_END_WRAPPER[com.codename1.charts.compat.Paint$Style: void <init>(java.lang.String, int)]
}

new public static void @static(){
//XMLVM_BEGIN_WRAPPER[com.codename1.charts.compat.Paint$Style: void <clinit>()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r0_o = null;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::org.xmlvm._nElement _r3;
    global::org.xmlvm._nElement _r4;
    _r4.i = 2;
    _r3.i = 1;
    _r2.i = 0;
    _r0_o = new global::com.codename1.charts.compat.Paint_2Style();
    // Value=FILL
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)70)), unchecked((char) unchecked((uint) 73)), unchecked((char) unchecked((uint) 76)), unchecked((char) unchecked((uint) 76))}));
    ((global::com.codename1.charts.compat.Paint_2Style) _r0_o).@this((global::java.lang.String) _r1_o, (int) _r2.i);
    global::com.codename1.charts.compat.Paint_2Style._fFILL = (global::com.codename1.charts.compat.Paint_2Style) _r0_o;
    _r0_o = new global::com.codename1.charts.compat.Paint_2Style();
    // Value=FILL_AND_STROKE
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)70)), unchecked((char) unchecked((uint) 73)), unchecked((char) unchecked((uint) 76)), unchecked((char) unchecked((uint) 76)), unchecked((char) unchecked((uint) 95)), unchecked((char) unchecked((uint) 65)), unchecked((char) unchecked((uint) 78)), unchecked((char) unchecked((uint) 68)), unchecked((char) unchecked((uint) 95)), unchecked((char) unchecked((uint) 83)), unchecked((char) unchecked((uint) 84)), unchecked((char) unchecked((uint) 82)), unchecked((char) unchecked((uint) 79)), unchecked((char) unchecked((uint) 75)), unchecked((char) unchecked((uint) 69))}));
    ((global::com.codename1.charts.compat.Paint_2Style) _r0_o).@this((global::java.lang.String) _r1_o, (int) _r3.i);
    global::com.codename1.charts.compat.Paint_2Style._fFILL_1AND_1STROKE = (global::com.codename1.charts.compat.Paint_2Style) _r0_o;
    _r0_o = new global::com.codename1.charts.compat.Paint_2Style();
    // Value=STROKE
    _r1_o = new global::java.lang.String();
    ((global::java.lang.String)_r1_o).@this(new global::org.xmlvm._nArrayAdapter<char>(new char[] {unchecked((char) unchecked((uint)83)), unchecked((char) unchecked((uint) 84)), unchecked((char) unchecked((uint) 82)), unchecked((char) unchecked((uint) 79)), unchecked((char) unchecked((uint) 75)), unchecked((char) unchecked((uint) 69))}));
    ((global::com.codename1.charts.compat.Paint_2Style) _r0_o).@this((global::java.lang.String) _r1_o, (int) _r4.i);
    global::com.codename1.charts.compat.Paint_2Style._fSTROKE = (global::com.codename1.charts.compat.Paint_2Style) _r0_o;
    _r0.i = 3;
    _r0_o = new global::org.xmlvm._nArrayAdapter<global::System.Object>(new global::System.Object[_r0.i]);
    _r1_o = global::com.codename1.charts.compat.Paint_2Style._fFILL;
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r2.i] = _r1_o;
    _r1_o = global::com.codename1.charts.compat.Paint_2Style._fFILL_1AND_1STROKE;
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r3.i] = _r1_o;
    _r1_o = global::com.codename1.charts.compat.Paint_2Style._fSTROKE;
    ((global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o)[_r4.i] = _r1_o;
    global::com.codename1.charts.compat.Paint_2Style._f_2VALUES = (global::org.xmlvm._nArrayAdapter<global::System.Object>) _r0_o;
    return;
//XMLVM_END_WRAPPER[com.codename1.charts.compat.Paint$Style: void <clinit>()]
}

//XMLVM_BEGIN_WRAPPER[com.codename1.charts.compat.Paint$Style]
//XMLVM_END_WRAPPER[com.codename1.charts.compat.Paint$Style]

} // end of class: Paint_2Style

} // end of namespace: com.codename1.charts.compat
