// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.util.regex {
public class AbstractCharClass_2LazyRange: global::java.util.regex.AbstractCharClass_2LazyCharClass {
public int _fstart;

public int _fend;

public void @this(int n1, int n2){
//XMLVM_BEGIN_WRAPPER[java.util.regex.AbstractCharClass$LazyRange: void <init>(int, int)]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    _r0_o = this;
    _r1.i = n1;
    _r2.i = n2;
    ((global::java.util.regex.AbstractCharClass_2LazyCharClass) _r0_o).@this();
    ((global::java.util.regex.AbstractCharClass_2LazyRange) _r0_o)._fstart = _r1.i;
    ((global::java.util.regex.AbstractCharClass_2LazyRange) _r0_o)._fend = _r2.i;
    return;
//XMLVM_END_WRAPPER[java.util.regex.AbstractCharClass$LazyRange: void <init>(int, int)]
}

public override global::System.Object computeValue(){
//XMLVM_BEGIN_WRAPPER[java.util.regex.AbstractCharClass$LazyRange: java.util.regex.AbstractCharClass computeValue()]
    global::System.Object _r0_o = null;
    global::org.xmlvm._nElement _r1;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r3_o = null;
    _r3_o = this;
    _r0_o = new global::java.util.regex.CharClass();
    ((global::java.util.regex.CharClass) _r0_o).@this();
    _r1.i = ((global::java.util.regex.AbstractCharClass_2LazyRange) _r3_o)._fstart;
    _r2.i = ((global::java.util.regex.AbstractCharClass_2LazyRange) _r3_o)._fend;
    _r0_o = ((global::java.util.regex.CharClass) _r0_o).add((int) _r1.i, (int) _r2.i);
    return (global::java.util.regex.AbstractCharClass) _r0_o;
//XMLVM_END_WRAPPER[java.util.regex.AbstractCharClass$LazyRange: java.util.regex.AbstractCharClass computeValue()]
}

//XMLVM_BEGIN_WRAPPER[java.util.regex.AbstractCharClass$LazyRange]
//XMLVM_END_WRAPPER[java.util.regex.AbstractCharClass$LazyRange]

} // end of class: AbstractCharClass_2LazyRange

} // end of namespace: java.util.regex
