// Automatically generated by xmlvm2csharp (do not edit).

using org.xmlvm;
namespace java.util.regex {
public abstract class LeafSet: global::java.util.regex.AbstractSet {
public int _fcharCount;

public void @this(global::java.util.regex.AbstractSet n1){
//XMLVM_BEGIN_WRAPPER[java.util.regex.LeafSet: void <init>(java.util.regex.AbstractSet)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    _r1_o = this;
    _r2_o = n1;
    _r0.i = 1;
    ((global::java.util.regex.AbstractSet) _r1_o).@this((global::java.util.regex.AbstractSet) _r2_o);
    ((global::java.util.regex.LeafSet) _r1_o)._fcharCount = _r0.i;
    ((global::java.util.regex.LeafSet) _r1_o).setType((int) _r0.i);
    return;
//XMLVM_END_WRAPPER[java.util.regex.LeafSet: void <init>(java.util.regex.AbstractSet)]
}

public void @this(){
//XMLVM_BEGIN_WRAPPER[java.util.regex.LeafSet: void <init>()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r1_o = null;
    _r1_o = this;
    ((global::java.util.regex.AbstractSet) _r1_o).@this();
    _r0.i = 1;
    ((global::java.util.regex.LeafSet) _r1_o)._fcharCount = _r0.i;
    return;
//XMLVM_END_WRAPPER[java.util.regex.LeafSet: void <init>()]
}

public abstract int accepts(int n1, global::java.lang.CharSequence n2);

public override int matches(int n1, global::java.lang.CharSequence n2, global::java.util.regex.MatchResultImpl n3){
//XMLVM_BEGIN_WRAPPER[java.util.regex.LeafSet: int matches(int, java.lang.CharSequence, java.util.regex.MatchResultImpl)]
    global::org.xmlvm._nElement _r0;
    global::org.xmlvm._nElement _r1;
    global::System.Object _r1_o = null;
    global::org.xmlvm._nElement _r2;
    global::System.Object _r3_o = null;
    global::org.xmlvm._nElement _r4;
    global::System.Object _r5_o = null;
    global::System.Object _r6_o = null;
    _r3_o = this;
    _r4.i = n1;
    _r5_o = n2;
    _r6_o = n3;
    _r2.i = -1;
    _r0.i = ((global::java.util.regex.LeafSet) _r3_o).charCount();
    _r0.i = _r0.i + _r4.i;
    _r1.i = ((global::java.util.regex.MatchResultImpl) _r6_o).getRightBound();
    if (_r0.i <= _r1.i) goto label17;
    _r0.i = 1;
    ((global::java.util.regex.MatchResultImpl) _r6_o)._fhitEnd = 0!=_r0.i;
    _r0.i = _r2.i;
    label16:;
    return _r0.i;
    label17:;
    _r0.i = ((global::java.util.regex.LeafSet) _r3_o).accepts((int) _r4.i, (global::java.lang.CharSequence) _r5_o);
    if (_r0.i >= 0) goto label25;
    _r0.i = _r2.i;
    goto label16;
    label25:;
    _r1_o = ((global::java.util.regex.LeafSet) _r3_o)._fnext;
    _r0.i = _r0.i + _r4.i;
    _r0.i = ((global::java.util.regex.AbstractSet) _r1_o).matches((int) _r0.i, (global::java.lang.CharSequence) _r5_o, (global::java.util.regex.MatchResultImpl) _r6_o);
    goto label16;
//XMLVM_END_WRAPPER[java.util.regex.LeafSet: int matches(int, java.lang.CharSequence, java.util.regex.MatchResultImpl)]
}

public virtual int charCount(){
//XMLVM_BEGIN_WRAPPER[java.util.regex.LeafSet: int charCount()]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r1_o = null;
    _r1_o = this;
    _r0.i = ((global::java.util.regex.LeafSet) _r1_o)._fcharCount;
    return _r0.i;
//XMLVM_END_WRAPPER[java.util.regex.LeafSet: int charCount()]
}

public override bool hasConsumed(global::java.util.regex.MatchResultImpl n1){
//XMLVM_BEGIN_WRAPPER[java.util.regex.LeafSet: boolean hasConsumed(java.util.regex.MatchResultImpl)]
    global::org.xmlvm._nElement _r0;
    global::System.Object _r1_o = null;
    global::System.Object _r2_o = null;
    _r1_o = this;
    _r2_o = n1;
    _r0.i = 1;
    return _r0.i!=0;
//XMLVM_END_WRAPPER[java.util.regex.LeafSet: boolean hasConsumed(java.util.regex.MatchResultImpl)]
}

//XMLVM_BEGIN_WRAPPER[java.util.regex.LeafSet]
//XMLVM_END_WRAPPER[java.util.regex.LeafSet]

} // end of class: LeafSet

} // end of namespace: java.util.regex
